### ISSUE TITLE
mappublicIp unknown option

### ISSUE THREAD

**Issue by pkutishch** [kubernetes-incubator/kube-aws#1044]
How i can force kube-aws disable allocating public IPs? When setting option to false it says that not valid key found. 

```
# Uncomment to provision nodes without a public IP. This assumes your VPC route table is setup to route to the internet via a NAT gateway.
# If you did not set vpcId and routeTableId the cluster will not bootstrap.
#mapPublicIPs: false
```

moreover using private IP i cannot bootstrap cluster because ETCd cannot be provisioned of some problems with ControlPlane:

```
Nov 28 16:00:52 ip-10-25-20-128.eu-west-1.compute.internal bash[957]: [  344.223834] awscli[5]: fatal error: HTTPSConnectionPool(host='s3-eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /kube-aws-test-1.8/kube-aws/clusters/testing-18/exported/stacks/control-plane/userdata-etcd-4bf2fa8a5a679913d7c2a157db1e7ad14efb0f9afbbbd81e98a469be0e5e8289 (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7fd92abfec90>, 'Connection to s3-eu-west-1.amazonaws.com timed out. (connect timeout=60)'))
```

```
kube-aws version
kube-aws version v0.9.9-rc.3
```

Any help would be much appreciated.

**Comment by mumoshu** [comment]
@pkutishch Hi, thanks for trying kube-aws!
Would you mind trying `subnets[].private:` instead?
The subnets section with it would look like:

```yaml
subnets:
- name: mysubnet1
   private: true
```

**Comment by pkutishch** [comment]
@mumoshu Hi thanks for very fast response.

my subnets sections looks like this

```
subnets:
#   #
#   # Managed public subnet managed by kube-aws
#   #
#   - name: ManagedPublicSubnet1
#     # Set to false if this subnet is public
#     # private: false
#     availabilityZone: eu-west-1a
#     instanceCIDR: "10.0.0.0/24"
#
#   #
#   # Managed private subnet managed by kube-aws
#   #
   - name: ManagedPrivateSubnet1
#     # Set to true if this subnet is private
     private: true
     availabilityZone: eu-west-1a
     instanceCIDR: "10.25.20.0/24"
     natGateway:
       id: "nat-id"
```

But anyway i can see that it provision EIP assigning it to nothing and for some reasons i can access any resource in internet except my s3 endpoint. 

Thank you

**Comment by pkutishch** [comment]
@mumoshu

> Btw, are you still seeing it included in the default cluster.yaml? If that's the case, sorry for the inconvenience! We should remove it from the default yaml.

 yes it still in default cluster.yaml

**Comment by pkutishch** [comment]
@mumoshu just checked #929 i've actually tried to put this param inside network, but ControlPlane allocates EIP anyway and as i mentioned assign it to nothing. 
The mostly my problem is that ControlPlane cannot provision etcd/workers etc... i could see that it starts rkt container with awscli and it fails as unable to reach s3 bucket endpoint

**Comment by pkutishch** [comment]
BTW just checked with public network it completely ignores option which disables EIP assignments.
```
   - name: ManagedPrivateSubnet1
#     # Set to true if this subnet is private
     private: false
     availabilityZone: eu-west-1a
     instanceCIDR: "10.25.20.0/24"
     mapPublicIPs: false
```

and instance anyway got provisioned with EIP, all of instances despite of settings above.
and with public network settings it able to reach s3 bucket ep. 
Now we're on old version which has k8s 1,4 onboard and we able to have it work on private subnet.
Please check that

**Comment by mumoshu** [comment]
@pkutishch Thanks for the info!

If you'd like not to rely on EIP for some reason, would you mind trying `etcd.memberIdentityProvider: eni`?
EIP is used to provide etcd nodes reliable network identities, so that the underlying EC2 instance of each etcd node can be terminated/recreated without reconfiguring etcd cluster membership(which is hard to do safely)

Also regarding S3 connectivity, could you verify that your network ACLs or SG egress is not blocking access to S3 via Internet, and your NAT gateway is deployed in a public subnet, you are not setting your own DNS in VPC  DHCP options(i.e. you are relying on Amazon DNS provided to your VPC by default)?

**Comment by pkutishch** [comment]
@mumoshu Thanks for your reply, yes my nat gatewey configured properly, and i can access s3 bucket from my local machine over internet, moreover all inet resources available from ec2 except s3.
Yes, my local machine and ec2 instance resolving the same IP for s3 endpoint.

but when set up in subnet settings not to map public IPs it sets it up to all resources, worker, controller and etcd this is in case with public network only, with private this option work but controlplane doesnt.

**Comment by pkutishch** [comment]
Played around ```eni``` option but still the same, with private network etcd doesn't work with public network it ingnores ```mapPublicIPs``` option and provision EIP aniway

**Comment by mumoshu** [comment]
Hi!
Just trying to understand whats going on but are you sure you are not
reusing existing subnets by specifying subnets[].id?
Also, mapPublicIps is noop anyway.
2017年11月29日(水) 21:03 Pavlo Kutishchev <notifications@github.com>:

**Comment by pkutishch** [comment]
Hi, nope, below my config section:
Subnet being created by kube-aws
```
subnets:
   - name: ManagedPrivateSubnet1
#     # Set to true if this subnet is private
     private: false
     availabilityZone: eu-west-1a
     instanceCIDR: "10.25.20.0/24"
     mapPublicIPs: false
```
