### ISSUE TITLE
Mounting of additional NVMe volumes

### ISSUE THREAD

**Issue by Huron** [kubernetes-incubator/kube-aws#1048]
I've added configuration for additional volume for workers
```
      volumeMounts:
      - type: "gp2"
        size: 60
        availabilityZone: us-east-1a
        device: "/dev/xvdf"
        path: "/var/lib/docker"

```
The worker instance has this device
![image](https://user-images.githubusercontent.com/693433/33478304-88bb707c-d691-11e7-89df-9708f96f1bb1.png)
![image](https://user-images.githubusercontent.com/693433/33478333-9cca08b2-d691-11e7-8093-db7606e9de5b.png)
But it  is not mounted in the filesistem.
```
ip-10-0-0-21 core # mount | grep /dev/nvme1n1
ip-10-0-0-21 core #
```

I assume that this is due to different device names in the instance and in coreos: /dev/xvdf and /dev/nvme1n1. Also the device has no partitions and any file system.

Have I to add the systemd mount unit for mount this device manually?
