### ISSUE TITLE
Option to customise tiller or disable it

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#1052]
I'd like to configure Tiller with `--history-max` from https://docs.helm.sh/helm/#helm-init amongst other things but the kube-aws deployment is enabled by default and keeps overriding the changes. It seems the only way to customise or disable it is change the cloud config and then be forced to resolve conflicts each time we move to a new kube-aws version.

We should avoid building Tiller options into kube-aws. IMO it's better to install Tiller using the helm CLI rather than the direct way we have now but maybe there's some advantage to doing it that way? 

What options do we have to enable the customisation above? For now I might just delete Tiller from our cloud-config-controller. Maybe just a way to disable our default deploy would be enough.

**Comment by mumoshu** [comment]
@c-knowles 

> IMO it's better to install Tiller using the helm CLI rather than the direct way we have now but maybe there's some advantage to doing it that way?

As far as I remember, [we two had discussed and concluded](https://github.com/kubernetes-incubator/kube-aws/issues/509#issuecomment-296019218) that installing tiller by default would allow us to utilize helm charts for components installed by kube-aws, but probably I misunderstood your intention at that time? 😄 
 
I'm ok with adding `addons.tiller.enabled` which is `false` by default to control the tiller installation, because we don't rely on helm charts(at least by default).

**Comment by c-knowles** [comment]
@mumoshu what I mean to say is that there is a difference in install mechanism. Installing tiller via the helm init should allow a user to change the tiller options without kube-aws overriding it but afaik there is no way to prevent our current more raw mechanism from doing the same. I'm open to options, I think we have at least these:
1. Option to disable tiller default deploy, but I think this will not work if we want to do as we concluded before
1. Ensure tiller upgrades or options changed do not get overridden, possible using helm init but maybe there is another way using the container we have now?
1. Allow customisations in kube-aws, -1 for this from me as I think we don't want to go down that road

**Comment by mumoshu** [comment]
For 3., I guess in an extremest case we could do:

```
addons:
  tiller:
    canaryImage: false
    historyMax: 0
    localRepoURL:
    netHost:
    override:
    stableRepoURL:
    upgrade: false
```

to set up a fully customized cluster-wide tiller in kube-system namspace while
recommending users to [install a locked-down tiller per non-system namespace](https://github.com/michelleN/helm-secure-tiller#example-workflow) manually after the cluster started.

**Comment by c-knowles** [comment]
I’m keen to avoid plumbing in all the Helm options. Could we just have something like a map of user args like `addons.tiller.extraArgs{}`.

**Comment by mumoshu** [comment]
What would be included in extraArgs for example?
Probably I'm ok if extraArgs was for the last resort until kube-aws supports each key i.e. it would look like

```yaml
addons:
  tiller:
    enabled: true
    canaryImage: false
    historyMax: 0
    localRepoURL:
    netHost:
    override:
    stableRepoURL:
    extraArgs:
    - --foo=bar
    upgrade: false
```
