### ISSUE TITLE
Integration with external-dns

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1056]
If this is the defacto, only versatile solution in this area, I'd rather like to add an out-of-box support for it.

https://github.com/kubernetes-incubator/external-dns

**Comment by c-knowles** [comment]
Just swapped to this using the helm chart. So far so good.

**Comment by camilb** [comment]
I'm using it right from the beginning, previously used route53-kubernetes. Works perfectly.

**Comment by mumoshu** [comment]
It turned out to be a matter of just writing cluster.yaml like:

```yaml
controller:
  iam:
    policy:
      statements:
      - effect: Allow
        actions:
        - "route53:ChangeResourceRecordSets"
        resources:
        - "arn:aws:route53:::hostedzone/MYPUBLICHOSTEDZONE"
        - "arn:aws:route53:::hostedzone/MYPRIVATEHOSTEDZONE"
      - effect: Allow
        actions:
        - "route53:ListHostedZones"
        - "route53:ListResourceRecordSets"
        resources:
        - "*"
```

and deploying external-dns according to the doc.
It is working like a charm 🎉
