### ISSUE TITLE
Integration with kube-aws-ingress-controller + skipper/istio-ingress/nginx-ingress

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1058]
After surveying about coreos/alb-ingress-controller, nginx-ingress-controller and so on, kube-aws-ingress-controller seems to be an optimal solution when you'd like to achieve the followings requirements as whole:

* Let an ingress controller create an ALB w/ appropriate ACM cert attached
* Appropriate worker nodes are added to target group(s) of the ALB
* DNS records are created on the ALB by external-dns
- In combination with an other ingress controller, path/cookie/weight/other rule based routing which isn't possible just with ALB but with combination of two ingress controllers

As kube-aws-ingress-controller is designed to be used in combination with an another ingress controller, we may choose skipper or istio-ingress, nginx-ingress, or else in addition to kube-aws-ingress-controller.

* skipper is well known and battle-tested in combination with kube-aws-ingress-controller by zalando. supports annotations for easy customizations. Even weight-based routing is configurable via annotations.
* istio-ingress would be a natural choice once we address #978. It works but I don't know how mature it is. I also don't know if it works well w/ kube-aws-ingress-controller though. Just have not tried yet.
* nginx-ingress-controller seems like the defacto of ingress controllers. Don't know if it works well w/ kube-aws-ingress-controller. Supports many annotations for easy customizations. Supports nginx.conf injection as the last resort.

**Comment by mumoshu** [comment]
Just finished experimenting with kube-ingress-aws-controller+skipper - it worked great!

Firstly, you'd need these IAM permissions for all the ASG-backed worker nodes:

```yaml
worker:
  nodePools:
  - iam:
      policy:
        statements:
        - effect: Allow
          actions:
          - "autoscaling:DescribeAutoScalingGroups"
          - "autoscaling:AttachLoadBalancers"
          - "autoscaling:DetachLoadBalancers"
          - "autoscaling:DetachLoadBalancerTargetGroup"
          - "autoscaling:AttachLoadBalancerTargetGroups"
          - "elasticloadbalancing:AddTags"
          - "elasticloadbalancing:DescribeLoadBalancers"
          - "elasticloadbalancing:CreateLoadBalancer"
          - "elasticloadbalancing:DeleteLoadBalancer"
          - "elasticloadbalancing:DescribeListeners"
          - "elasticloadbalancing:CreateListener"
          - "elasticloadbalancing:DeleteListener"
          - "elasticloadbalancing:DescribeTags"
          - "elasticloadbalancing:CreateTargetGroup"
          - "elasticloadbalancing:DeleteTargetGroup"
          - "elasticloadbalancing:DescribeTargetGroups"
          - "elasticloadbalancingv2:DescribeTargetGroups"
          - "elasticloadbalancingv2:DescribeLoadBalancers"
          - "elasticloadbalancingv2:CreateLoadBalancer"
          - "elasticloadbalancingv2:DeleteLoadBalancer"
          - "elasticloadbalancingv2:DescribeListeners"
          - "elasticloadbalancingv2:CreateListener"
          - "elasticloadbalancingv2:DeleteListener"
          - "elasticloadbalancingv2:DescribeTags"
          - "elasticloadbalancingv2:CreateTargetGroup"
          - "elasticloadbalancingv2:DeleteTargetGroup"
          - "ec2:DescribeInstances"
          - "ec2:DescribeSubnets"
          - "ec2:DescribeSecurityGroup"
          - "ec2:DescribeRouteTables"
          - "ec2:DescribeVpcs"
          - "acm:ListCertificates"
          - "acm:DescribeCertificate"
          - "iam:ListServerCertificates"
          - "iam:GetServerCertificate"
          - "cloudformation:Get*"
          - "cloudformation:Describe*"
          - "cloudformation:List*"
          - "cloudformation:Create*"
          - "cloudformation:Delete*"
          resources:
          - "*"
```

Also note that as kube-ingress-aws-controller doesn't support running on spot instances, you should add a nodeAffinity like this to stick it to ASG-backed worker nodes:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-ingress-aws-controller
    component: ingress
  name: kube-ingress-aws-controller
controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ingress-aws-controller
      component: ingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: kube-ingress-aws-controller
        component: ingress
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kube-aws.coreos.com/autoscalinggroup
                operator: Exists
      containers:
      - env:
        - name: AWS_REGION
          value: $YOUR_REGION
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest
        imagePullPolicy: Always
        name: controller
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

To add the `kube-aws.coreos.com/autoscalinggroup` label to nodes, you need to enable the awsNodeLabels feature in cluster.yaml:

```
worker:
  nodePools:
  - awsNodeLabels:
      enabled: true
```
