### ISSUE TITLE
master: kube-proxy fails on a controller node

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1121]
Saying it was unable to find the `KubeProxyConfiguration` kind:

```
core@ip-10-0-0-27 ~ $ docker ps -a | grep proxy
056931c37b71        k8s.gcr.io/hyperkube-amd64                         "/hyperkube proxy --…"   4 minutes ago       Exited (1) 4 minutes ago                          k8s_kube-proxy_kube-proxy-pzk72_kube-system_b1440c3f-04ab-11e8-83a8-0630a36a131c_6
6698a3c54ff6        gcr.io/google_containers/pause-amd64:3.0           "/pause"                 10 minutes ago      Up 10 minutes                                     k8s_POD_kube-proxy-pzk72_kube-system_b1440c3f-04ab-11e8-83a8-0630a36a131c_0
core@ip-10-0-0-27 ~ $ docker logs 056931c37b71
error: no kind "KubeProxyConfiguration" is registered for version "componentconfig/v1alpha1"
```

**Comment by mumoshu** [comment]
On the surface, it will look like cfn-signal is timing out
https://gist.github.com/mumoshu/503c01a7e7af0067adf70232e45161b5

**Comment by mumoshu** [comment]
This is odd.

`apiVersion: {{if ge .K8sVer "v1.9"}}kubeproxy.config.k8s.io{{else}}componentconfig{{end}}/v1alpha1` is somehow evaluated to componentconfig/v1alpha1?

```
core@ip-10-0-0-27 ~ $ cat /etc/kubernetes/manifests/kube-apiserver.yaml  | grep 1.9.1
    image: k8s.gcr.io/hyperkube-amd64:v1.9.1
core@ip-10-0-0-27 ~ $ cat /srv/kubernetes/manifests/kube-proxy-cm.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-proxy-config
  namespace: kube-system
data:
  kube-proxy-config.yaml: |
    apiVersion: componentconfig/v1alpha1
    kind: KubeProxyConfiguration
    bindAddress: 0.0.0.0
    clientConnection:
      kubeconfig: /etc/kubernetes/kubeconfig/kube-proxy.yaml
    clusterCIDR: 10.2.0.0/16
```

**Comment by mumoshu** [comment]
Looks like a race between an update to kube-proxy-cm and kube-proxy starts. Only `kube-aws udpate` form k8s 1.8.x to 1.9.x would be affected.

**Comment by mumoshu** [comment]
Hm, `install-kube-system` is not updating kube-proxy-config, which is wrong.

```
Jan 29 04:19:57 ip-10-0-0-27.ap-northeast-1.compute.internal retry[2359]: configmap "kube-proxy-config" unchanged
```

**Comment by mumoshu** [comment]
Ah, my cloud-config-controller was too old, again :)

```
- path: /srv/kubernetes/manifests/kube-proxy-cm.yaml
    content: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: kube-proxy-config
        namespace: kube-system
      data:
        kube-proxy-config.yaml: |
          apiVersion: componentconfig/v1alpha1
          kind: KubeProxyConfiguration
          bindAddress: 0.0.0.0
          clientConnection:
            kubeconfig: /etc/kubernetes/kubeconfig/kube-proxy.yaml
          clusterCIDR: {{.PodCIDR}}
```

**Comment by kylegoch** [comment]
I am having this same issue on a brand new cluster. kube-aws is `0.9.9`

How exactly did you fix this @mumoshu ?

**Comment by mumoshu** [comment]
Hi! Wonder if your issue is really related to this one?
Perhaps sharing the full output from `journalctl` would help!

**Comment by kylegoch** [comment]
My docker logs match your first post, and my journalctl matches your gist.
I tried manually specifying the api in the cloud-config-controller like this:
```
content: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: kube-proxy-config
        namespace: kube-system
      data:
        kube-proxy-config.yaml: |
          apiVersion: kubeproxy.config.k8s.io/v1alpha1
          kind: KubeProxyConfiguration
          bindAddress: 0.0.0.0
          clientConnection:
            kubeconfig: /etc/kubernetes/kubeconfig/kube-proxy.yaml
          clusterCIDR: {{.PodCIDR}}
```
