### ISSUE TITLE
Managed Route Table VGW Propagate Setting

### ISSUE THREAD

**Issue by S-Collison** [kubernetes-incubator/kube-aws#1138]
We are using managed subnets for the cluster.yaml configuration and need to enable propagation for specific vgw's. Can I create a PR to add this to the subnets section of the cluster.yaml configuration? As in:
```
subnets:
- availabilityZone: us-xxxxx-xa
  instanceCIDR: x.x.x.x/24
  name: PrivateSubnetx
  natGateway:
    eipAllocationId: eipalloc-xxxxxxxxx
  private: true
  propagate:
  - vgw-xxxxxx
```
Or is there another preferred method of ensuring that managed route tables have this setting? Are plugins up to the task?
