### ISSUE TITLE
Cleaner way for extending kube-aws to generate addon TLS cert/key

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#1144]
#1134 ended up with a terrible implementation. We'd want a more generic, less brittle way to instruct kube-aws to generate various addons TLS certs/keys.
`KeyUsage`, `Subject`, `DNSNames` and `Expiration` customizability would be required.

**Comment by mumoshu** [comment]
Maybe by enhancing the hidden feature of the plugin system to understand:

```yaml
tlsAssets:
- id: kiam-server
  keyUsage: [ ... ]
  subject: "..."
   dnsNames: [ ... ]
- id: kiam-agent
  keyUsage: [ ... ]
  subject: "..."
   dnsNames: [ ... ]
```

so that `kube-aws render credentials` or `kube-aws rotate certificate kiam-(agent|server)`(#1146) picks it up to include those assets to be (re)generated.
