### ISSUE TITLE
Unable to create cluster in existing VPC

### ISSUE THREAD

**Issue by vbogretsov** [kubernetes-incubator/kube-aws#1176]
Hello, I'm trying to create a cluster in existing VPC and reuse existing networks using the following `cluster.yaml`:

```yaml
clusterName: myapp-dev
apiEndpoints:
-
  name: default
  dnsName: dev.myapp.com
  loadBalancer:
    subnets:
      - name: public1
    hostedZone:
      id: <HOSTED_ZONE_ID>
keyName: myapp
region: us-east-2
kmsKeyArn: <KEY_ARN>
controller:
  instanceType: t2.small
  subnets:
    - name: public1
worker:
  nodePools:
    -
      name: nodepool1
      instanceType: t2.small
      subnets:
        - name: private1a
etcd:
  instanceType: t2.small
  subnets:
   - name: private1a
vpc:
  idFromStackOutput: myapp-vpc-VPCID
subnets:
  - name: public1
    availabilityZone: us-east-2a
    idFromStackOutput: myapp-vpc-PublicSubnet1
  - name: private1a
    availabilityZone: us-east-2a
    idFromStackOutput: myapp-vpc-PrivateSubnet1A
# The settings below are uncommented after kube-aws init
kubernetesDashboard:
  adminPrivileges: true
  insecureLogin: false
addons:
  clusterAutoscaler:
    enabled: false
  rescheduler:
    enabled: false
  metricsServer:
    enabled: false
experimental:
  admission:
    podSecurityPolicy:
      enabled: false
    alwaysPullImages:
      enabled: false
    denyEscalatingExec:
      enabled: false
    initializers:
      enabled: false
  awsEnvironment:
    enabled: false
    environment:
      CFNSTACK: '{ "Ref" : "AWS::StackId" }'
  auditLog:
    enabled: false
    maxage: 30
    logpath: /dev/stdout
  authentication:
    webhook:
      enabled: false
      cacheTTL: 1m0s
      configBase64: base64-encoded-webhook-yaml
  awsNodeLabels:
    enabled: false
  tlsBootstrap:
    enabled: false
  nodeAuthorizer:
    enabled: false
  ephemeralImageStorage:
    enabled: false
  kube2IamSupport:
    enabled: false
  nodeDrainer:
    enabled: false
    drainTimeout: 5
  oidc:
    enabled: false
    issuerUrl: "https://accounts.google.com"
    clientId: "kubernetes"
    usernameClaim: "email"
    groupsClaim: "groups"
  disableSecurityGroupIngress: false

```

but I'm gettings the following error:

+00:19:33	UPDATE_IN_PROGRESS      		Controllers           	"Failed to receive 1 resource signal(s) for the current batch.  Each resource signal timeout is counted as a FAILURE."
+00:19:34	CREATE_FAILED           		Controllers           	"Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement"
+00:19:36	CREATE_FAILED           		myapp-dev-Controlplane-18EB4X437CDU2	"The following resource(s) failed to create: [Controllers]. "
+00:20:16	CREATE_FAILED           		Controlplane          	"Embedded stack <ARN> was not successfully created: The following resource(s) failed to create: [Controllers]. "
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [Controlplane].

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack myapp-dev The following resource(s) failed to create: [Controlplane].
CREATE_FAILED AWS::CloudFormation::Stack Controlplane Embedded stack <ARN> was not successfully created: The following resource(s) failed to create: [Controllers].

The step `kube-aws validate` completed successfully. When I'm creating a cluster with the default `cluster.yaml` it's created successfully.

The VPC stack is the following:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates VPC for the MyApp project.

  Last Modified: 5 Mar 2018
Parameters:
  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for VPC
    Type: String
    Default: 172.16.0.0/16
  PublicSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for public subnet located in Availability Zone 1
    Type: String
    Default: 172.16.0.0/24
  PrivateSubnet1ACIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for private subnet 1A located in Availability Zone 1
    Type: String
    Default: 172.16.1.0/24
  PrivateSubnet1BCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for private subnet 1B located in Availability Zone 1
    Type: String
    Default: 172.16.2.0/24
  PublicSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for public subnet located in Availability Zone 2
    Type: String
    Default: 172.16.100.0/24
  PrivateSubnet2ACIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for private subnet 2A located in Availability Zone 2
    Type: String
    Default: 172.16.101.0/24
  PrivateSubnet2BCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for private subnet 2B located in Availability Zone 2
    Type: String
    Default: 172.16.102.0/24
Resources:
  DHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers:
        - AmazonProvidedDNS
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-InternetGateway"
        - Key: Network
          Value: Public
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  VPCDHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: !Ref VPC
      DhcpOptionsId: !Ref DHCPOptions
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select
        - '0'
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: Public subnet in AZ1
        - Key: Network
          Value: Public
  PrivateSubnet1A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1ACIDR
      AvailabilityZone: !Select
        - '0'
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: Private subnet A in AZ1
        - Key: Network
          Value: Private
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: !Select
        - '1'
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: Public subnet in AZ2
        - Key: Network
          Value: Public
  PrivateSubnet2A:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2ACIDR
      AvailabilityZone: !Select
        - '1'
        - Fn::GetAZs: !Ref AWS::Region
      Tags:
        - Key: Name
          Value: Private subnet A in AZ2
        - Key: Network
          Value: Private
  NAT1EIP:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NAT2EIP:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  NATGateway1:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt
        - NAT1EIP
        - AllocationId
      SubnetId: !Ref PublicSubnet1
  NATGateway2:
    DependsOn: VPCGatewayAttachment
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt
        - NAT2EIP
        - AllocationId
      SubnetId: !Ref PublicSubnet2
  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public subnet 1
        - Key: Network
          Value: Public
  PublicSubnetRoute:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicSubnetRouteTable
  PrivateSubnet1ARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private subnet 1A
        - Key: Network
          Value: Private
  PrivateSubnet1ARoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateSubnet1ARouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1
  PrivateSubnet1ARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1A
      RouteTableId: !Ref PrivateSubnet1ARouteTable
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicSubnetRouteTable
  PrivateSubnet2ARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Private subnet 2A
        - Key: Network
          Value: Private
  PrivateSubnet2ARoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateSubnet2ARouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2
  PrivateSubnet2ARouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PrivateSubnet2A
      RouteTableId: !Ref PrivateSubnet2ARouteTable
  EC2PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: !Sub ${AWS::StackName} EC2 Public Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        # TODO(bogretovv): remove when template will be ready
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  EC2PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: !Sub ${AWS::StackName} EC2 Private Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        # TODO(bogretovv): remove when template will be ready
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        VpcId: !Ref VPC
        GroupDescription: !Sub ${AWS::StackName} RDS security group
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: !Ref VPCCIDR
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${AWS::StackName} RDS subnet group
      SubnetIds:
        - !Ref PrivateSubnet1A
        - !Ref PrivateSubnet2A
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: myapp.com
      VPCs:
      - VPCId: !Ref VPC
        VPCRegion: !Ref AWS::Region
Outputs:
  VPCID:
    Value: !Ref VPC
    Description: VPC ID
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  InternetGateway:
    Value: !Ref InternetGateway
    Description: Internet Gateway
    Export:
      Name: !Sub "${AWS::StackName}-InternetGatewayID"
  VPCCIDR:
    Description: VPC CIDR
    Value: !Ref VPCCIDR
  PublicSubnet1CIDR:
    Description: Public Subnet 1 CIDR
    Value: !Ref PublicSubnet1CIDR
  PrivateSubnet1ACIDR:
    Description: Private Subnet 1A CIDR
    Value: !Ref PrivateSubnet1ACIDR
  PublicSubnet2CIDR:
    Description: Public Subnet 2 CIDR
    Value: !Ref PublicSubnet2CIDR
  PrivateSubnet2ACIDR:
    Description: Private Subnet 2A CIDR
    Value: !Ref PrivateSubnet2ACIDR
  PublicSubnet1:
    Description: Pubblic subnet 1
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1"
  PublicSubnet2:
    Description: Pubblic subnet 2
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2"
  PrivateSubnet1A:
    Description: Private subnet 1A
    Value: !Ref PrivateSubnet1A
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1A"
  PrivateSubnet2A:
    Description: Private subnet 2A
    Value: !Ref PrivateSubnet2A
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2A"
  NAT1EIP:
    Description: Subnet 1 NAT IP address
    Value: !Ref NAT1EIP
    Export:
      Name: !Sub "${AWS::StackName}-NAT1EIP"
  NAT2EIP:
    Description: Subnet 2 NAT IP address
    Value: !Ref NAT2EIP
    Export:
      Name: !Sub "${AWS::StackName}-NAT2EIP"
  EC2PublicSecurityGroupID:
    Description: Public Security Group for EC2 instances
    Value: !Ref EC2PublicSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-EC2PublicSecurityGroupID"
  EC2PrivateSecurityGroupID:
    Description: Private Security Group for EC2 instances
    Value: !Ref EC2PrivateSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-EC2PrivateSecurityGroupID"
  RDSSecurityGroupID:
    Description: Security Group for RDS instances
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-RDSSecurityGroupID"
  RDSSubnetGroupID:
    Description: Subnet Group for RDS instances
    Value: !Ref RDSSubnetGroup
    Export:
      Name: !Sub "${AWS::StackName}-RDSSubnetGroupID"
  PrivateHostedZoneID:
    Description: Private Hosted Zone ID
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub "${AWS::StackName}-PrivateHostedZoneID"
```

Could you please help me to understand what is wrong in my `cluster.yaml`.
Thank you!
