### ISSUE TITLE
0.9.9 unable to create internal elb for api endpoint

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/kube-aws#1183]
We tried setting our k8s api endpoint to use an internal ELB. The resulting ELB, unfortunately, was still public.

## Does not work

The ELB is not accessible, and it is not internal, but public.

```yaml
apiEndpoints:
- name: default
  dnsName: k8s.example.com
  loadBalancer:
    subnets:
    - name: ManagedPrivateSubnet1d
      private: true
      recordSetTTL: 30
    hostedZone:
      id: abc123

subnets:
  - availabilityZone: us-east-1d
    instanceCIDR: "10.90.36.0/24"
    name: ManagedPrivateWorkerSubnet1d
    private: true
    routeTable:
      id: "rtb-internal"
  - availabilityZone: us-east-1d
    instanceCIDR: "10.90.35.0/24"
    name: ManagedPrivateSubnet1d
    private: true
    routeTable:
      id: "rtb-internal"
  - name: ExistingPublicSubnet1d
    availabilityZone: us-east-1d
    private: false
    id: "subnet-b450e7ed"
    routeTable:
      id: "rtb-dmz"
```

## Works

The ELB is accessible from the internet. 

```yaml
apiEndpoints:
- name: default
  dnsName: k8s.example.com
  loadBalancer:
    subnets:
    - name: ExistingPublicSubnet1d
      private: false
      recordSetTTL: 30
    hostedZone:
      id: abc123

subnets:
  - availabilityZone: us-east-1d
    instanceCIDR: "10.90.36.0/24"
    name: ManagedPrivateWorkerSubnet1d
    private: true
    routeTable:
      id: "rtb-internal"
  - availabilityZone: us-east-1d
    instanceCIDR: "10.90.35.0/24"
    name: ManagedPrivateSubnet1d
    private: true
    routeTable:
      id: "rtb-internal"
  - name: ExistingPublicSubnet1d
    availabilityZone: us-east-1d
    private: false
    id: "subnet-b450e7ed"
    routeTable:
      id: "rtb-dmz"

```
