### ISSUE TITLE
Kubernetes version specified in cluster.yaml not reflected in `kubectl cluster-info dump`

### ISSUE THREAD

**Issue by Sriharivignesh** [kubernetes-incubator/kube-aws#1192]
I am specifying hyperkube image like so:

```
hyperkubeImage:
  repo: k8s.gcr.io/hyperkube
  rktPullDocker: false
  tag: v1.9.5
  RepoWithTag: 'k8s.gcr.io/hyperkube:v1.9.5'
```

But in the cluster-info dump, I am seeing `"KubeletVersion": "v1.8.4+coreos.0"`

Also specifying this `kubernetesVersion: v1.9.5` outside of `hyperkubeImage` key doesn't seem to work as my cluster never gets created.

How to correctly specify latest kubernetes version in the cluster.yaml?
