### ISSUE TITLE
reuse of an existing network ELB for APIEndpoint

### ISSUE THREAD

**Issue by rckgrail** [kubernetes-incubator/kube-aws#1321]
It appears that there is no way to accomplish the reuse of an existing network elb to get at the API servers (observed in v0.9.9, though the related code doesn't appear to have changed in v0.9.10)

For example the cluster.yaml snippet:
```
apiEndpoints:
- name: externalPublic
  dnsName: green.k8s.xxx.com
  loadBalancer:
    id: elb-green-external
```
will result in an ultimate failure with:
+00:08:36       CREATE_FAILED                           Controllers             "Provided Load Balancers may not be valid. Please ensure they exist and try again."

also, it appears there is no support for the targetGroup setting at the apiEndpoints level, which might be the mechanism to make this work.

Robert
