### ISSUE TITLE
Kiam server health check is hardcoded

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes-incubator/kube-aws#1350]
The latest vault (0.10.1) does not allow port names in the subject alternative name

Previous editions allowed this: "alt_names=kiam-server:443,localhost:443" when creating an pki issue

This has now been stopped and only valid dns names are allowed

Vault will allow localhost overriding which will create:
```
X509v3 Subject Alternative Name:
                DNS:localhost
```

...but the server health checks in the kiam-server manifest specify the port in the server address check and this is validated against the SAN in the cert

```
livenessProbe:
                  exec:
                    command:
                    - /health
                    - --cert=/etc/kiam/tls/server.pem
                    - --key=/etc/kiam/tls/server-key.pem
                    - --ca=/etc/kiam/tls/ca.pem
                    - --server-address=localhost:443
                    - --server-address-refresh=2s
                    - --timeout=5s
```

Need to either allow a configurable server-address or have some other health check

/cc @pingles
