### ISSUE TITLE
nfs mount issues

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1364]
Hi

I'm trying to mount a NFS share in a POD, but I encounter the exact same issue as mentioned here
https://github.com/coreos/bugs/issues/2038

My cluster is created with kube-aws 0.9.10 and CoreOS with ami-c70005be

Deployment for test purposes
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: webapp
    spec:
      volumes:            
      - name: netapp
        nfs:
          server: my-nfs-server-host
          path: /vol1
      containers:
      - name: hello-backend
        image: docker pull busybox
        volumeMounts:                        
        - mountPath: /vol1
          name: netapp 
```

Error message
```
Mounting command: mount
Mounting arguments: netapp.gdo.aws:/vol1 /var/lib/kubelet/pods/d7452ed4-6f44-11e8-a1d5-02878f774928/volumes/kubernetes.io~nfs/netapp nfs []
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
```
