### ISSUE TITLE
Error: failed to run Kubelet: cannot create certificate signing request

### ISSUE THREAD

**Issue by qpaulson** [kubernetes-incubator/kube-aws#1372]
I am trying to upgrade my clusters from 1.6.2 to the latest....
When booting the cluster I am getting an error:

```
Jun 18 22:51:26 ip-10-143-8-241.aue1.central1.cc kubelet-wrapper[2096]: Error: failed to run Kubelet: cannot create certificate signing request: Post https://ckube-a-common.aws.central1.com:443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 54.173.88.186:443: i/o timeout
```
I am trying to enable tlsBootstrap & mangeCertificates ( obviously )..

I've tried a few things, but nothing I can think of will resolve it.. 

If it helps, I am running the latest Version: **Cluster bootstrap stability fix on top of v0.9.10**

Here is my cluster.yaml ( Ignore the _WORD_ values, these are replaced at Jenkins run time with the correct information needed to manage the given cluster.

```
clusterName: _CLUSTER_NAME_
s3URI: s3://kubernetes-state-backend-us-east-1/
amiId: "ami-fd3b4582"
disableContainerLinuxAutomaticUpdates: true
apiEndpoints:
- # The unique name of this API endpoint used to identify it inside CloudFormation stacks or
  name: default
  dnsName: _CLUSTER_NAME_.aws.central1.com
  loadBalancer:

    hostedZone:
      id: _ZONE_

keyName: _AWS_KEY_
region: _REGION_
availabilityZone: us-east-1b
kmsKeyArn: _ARN_
controller:
  securityGroupIds:
    - _WORKER_SECURITY_GROUP_
  autoScalingGroup:
    minSize: 1
    maxSize: 1
    rollingUpdateMinInstancesInService: 0
worker:
  nodePools:
    - # Name of this node pool. Must be unique among all the node pools in this cluster
      name: nodepool1
      securityGroupIds:
        - _WORKER_SECURITY_GROUP_
      autoScalingGroup:
        minSize: 4
        maxSize: 20
        rollingUpdateMinInstancesInService: 4
      autoscaling:
        clusterAutoscaler:
          enabled: true
      awsNodeLabels:
        enabled: true
      clusterAutoscalerSupport:
        enabled: true
      customFiles:
        - path: "/etc/systemd/system/docker.service.d/10-custom.conf"
          permissions: 0600
          content: |
            [Service]
            Environment="DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3 --registry-mirror=http://127.0.0.1:30199 --registry-mirror=https://artifactory.oss.central1.com:5000 --insecure-registry=127.0.0.1:30199 --bip=192.168.0.1/16"
workerInstanceType: t2.xlarge
etcd:
  count: 3
  instanceType: t2.medium
  instanceTags:
    instanceRole: etcd
  dataVolume:
    encrypted: false
    ephemeral: false
  subnets:
    - name: PrivateSubnet1
  snapshot:
    automated: true
  memberIdentityProvider: eni
vpc:
  id: _VPC_ID_
routeTableId: _ROUTING_TABLE_
vpcCIDR: "_VPC_CIDR_"
subnets:
  - name: PrivateSubnet1
    availabilityZone: _ZONE_
    id: "_SUBNET_"
    public: false
containerRuntime: docker
manageCertificates: true
kubernetesDashboard:
  adminPrivileges: true
  insecureLogin: false
amazonSsmAgent:
  enabled: true
  downloadUrl: https://github.com/DailyHotel/amazon-ssm-agent/releases/download/v2.0.805.1/ssm.linux-amd64.tar.gz
  sha1sum: a6fff8f9839d5905934e7e3df3123b54020a1f5e
kubeDns:
  autoscaler:
    coresPerReplica: 256
    nodesPerReplica: 16
    min: 2
kubeProxy:
  ipvsMode:
    enabled: false
    scheduler: rr
    syncPeriod: 300s
    minSyncPeriod: 60s
addons:
  clusterAutoscaler:
    enabled: false
  rescheduler:
    enabled: false
  metricsServer:
    enabled: true
  prometheus:
    securityGroupsEnabled: true
experimental:
  admission:
    podSecurityPolicy:
      enabled: false
    alwaysPullImages:
      enabled: false
    denyEscalatingExec:
      enabled: false
    initializers:
      enabled: false
    priority:
      enabled: false
    mutatingAdmissionWebhook:
      enabled: false
    validatingAdmissionWebhook:
      enabled: false
    OwnerReferencesPermissionEnforcement:
      enabled: false
    persistentVolumeClaimResize:
      enabled: false
  awsEnvironment:
    enabled: false
    environment:
      CFNSTACK: '{ "Ref" : "AWS::StackId" }'
  auditLog:
    enabled: false
    maxage: 30
    logpath: /dev/stdout
  authentication:
    webhook:
      enabled: false
      cacheTTL: 1m0s
      configBase64: base64-encoded-webhook-yaml
  awsNodeLabels:
    enabled: true
  tlsBootstrap:
    enabled: true
  nodeAuthorizer:
    enabled: false
  ephemeralImageStorage:
    enabled: false
  kube2IamSupport:
    enabled: false
  nodeDrainer:
    enabled: true
    drainTimeout: 5
    iamRole:
      arn: ""
  oidc:
    enabled: false
    issuerUrl: "https://accounts.google.com"
    clientId: "kubernetes"
    usernameClaim: "email"
    groupsClaim: "groups"
  disableSecurityGroupIngress: false
kubelet:
  RotateCerts:
    enabled: true
stackTags:
  Name: "Cluster _CLUSTER_NAME_"
  c1:env: "_ENV_"
  c1:cost-centre: "4473"
  c1:cluster: "_CLUSTER_NAME_"
  c1:cluster-type: "kubernetes"
  c1:owner: "_OWNER_"
  c1:supported-by: "Platform Management"

```

Thanks for any help you guys may have!

**Comment by mumoshu** [comment]
Hi! The dial tcp timeout error seems to indicate that you have L4
connectivity issue between the apiserver lb and the node. Can you verify
that your network ACL or route tables blocking it?
2018年6月19日(火) 8:24 qpaulson <notifications@github.com>:

**Comment by qpaulson** [comment]
It should not be a problem.. If I remove the tlsBootstrap & mangeCertificates options it all starts correctly.

Is there perhaps additional ports that are not correct in the default security groups?

FYI, I've also tried enabling:
```
  authentication:
    webhook:
      enabled: false
      cacheTTL: 1m0s
      configBase64: base64-encoded-webhook-yaml
```

No change.

**Comment by qpaulson** [comment]
Probably not related, but I am also seeing another error in the logs on the worker nodes..  I suspect its  not really an issue:

```
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]: 2018-06-19 00:03:27 ERROR [instanceID=i-02d881a145ffefe6a] [MessageProcessor] [Association] error when calling AWS APIs.error details - AccessDeniedException: User: arn:aws:sts::368897584504:assumed-role/ckube-a-common-Nodepool1-D89G1N4VIO0-IAMRoleWorker-10A1ZKO22CBS4/i-02d881a145ffefe6a is not authorized to perform: ssm:ListInstanceAssociations on resource: arn:aws:ec2:us-east-1:368897584504:instance/i-02d881a145ffefe6a
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]:         status code: 400, request id: 226c50a9-d582-4937-90fb-0c28104f652f
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]: 2018-06-19 00:03:27 INFO [instanceID=i-02d881a145ffefe6a] [MessageProcessor] [Association] increasing error count by 1
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]: 2018-06-19 00:03:27 ERROR [instanceID=i-02d881a145ffefe6a] [MessageProcessor] [Association] error when calling AWS APIs.error details - AccessDeniedException: User: arn:aws:sts::368897584504:assumed-role/ckube-a-common-Nodepool1-D89G1N4VIO0-IAMRoleWorker-10A1ZKO22CBS4/i-02d881a145ffefe6a is not authorized to perform: ssm:ListAssociations on resource: arn:aws:ssm:us-east-1:368897584504:*
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]:         status code: 400, request id: b04f5188-dd35-42d2-8332-994fbf5857ba
Jun 19 00:03:27 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]: 2018-06-19 00:03:27 INFO [instanceID=i-02d881a145ffefe6a] [MessageProcessor] [Association] increasing error count by 1
Jun 19 00:03:28 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]: 2018-06-19 00:03:27 ERROR [instanceID=i-02d881a145ffefe6a] [MessageProcessor] [Association] Unable to load instance associations, unable to retrieve associations unable to retrieve associations AccessDeniedException: User: arn:aws:sts::368897584504:assumed-role/ckube-a-common-Nodepool1-D89G1N4VIO0-IAMRoleWorker-10A1ZKO22CBS4/i-02d881a145ffefe6a is not authorized to perform: ssm:ListAssociations on resource: arn:aws:ssm:us-east-1:368897584504:*
Jun 19 00:03:28 ip-10-143-14-166.aue1.central1.cc amazon-ssm-agent[1003]:         status code: 400, request id: b04f5188-dd35-42d2-8332-994fbf5857ba
```

**Comment by mumoshu** [comment]
> It should not be a problem.. If I remove the tlsBootstrap & mangeCertificates options it all starts correctly.

Just trying to understand but are you saying that your worker node has access to K8S API when TLS bootstrapping is disabled, but not when it is enabled, right? Definitely something is wrong then, because the log message indicates its a L4 issue.

**Comment by qpaulson** [comment]
That is correct. If I disable the Certificate Rotation and bootstrapping it starts.  I will do it again, just to confirm.

**Comment by qpaulson** [comment]
This stack ran fine.. 

```
clusterName: _CLUSTER_NAME_
s3URI: s3://kubernetes-state-backend-us-east-1/
amiId: "ami-fd3b4582"
disableContainerLinuxAutomaticUpdates: true
apiEndpoints:
- # The unique name of this API endpoint used to identify it inside CloudFormation stacks or
  name: default
  dnsName: _CLUSTER_NAME_.aws.central1.com
  loadBalancer:

    hostedZone:
      id: Z2LGBQ7H2AU015

keyName: _AWS_KEY_
region: _REGION_
availabilityZone: us-east-1b
kmsKeyArn: _ARN_
controller:
  securityGroupIds:
    - _WORKER_SECURITY_GROUP_
  autoScalingGroup:
    minSize: 1
    maxSize: 1
    rollingUpdateMinInstancesInService: 0
worker:
  nodePools:
    - # Name of this node pool. Must be unique among all the node pools in this cluster
      name: nodepool1
      securityGroupIds:
        - _WORKER_SECURITY_GROUP_
      autoScalingGroup:
        minSize: 4
        maxSize: 20
        rollingUpdateMinInstancesInService: 4
      autoscaling:
        clusterAutoscaler:
          enabled: true
      awsNodeLabels:
        enabled: true
      clusterAutoscalerSupport:
        enabled: true
      customFiles:
        - path: "/etc/systemd/system/docker.service.d/10-custom.conf"
          permissions: 0600
          content: |
            [Service]
            Environment="DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3 --registry-mirror=http://127.0.0.1:30199 --registry-mirror=https://artifactory.oss.central1.com:5000 --insecure-registry=127.0.0.1:30199 --bip=192.168.0.1/16"
workerInstanceType: t2.xlarge
etcd:
  count: 3
  instanceType: t2.medium
  instanceTags:
    instanceRole: etcd
  dataVolume:
    encrypted: false
    ephemeral: false
  subnets:
    - name: PrivateSubnet1
  snapshot:
    automated: true
  memberIdentityProvider: eni
vpc:
  id: _VPC_ID_
routeTableId: _ROUTING_TABLE_
vpcCIDR: "_VPC_CIDR_"
subnets:
  - name: PrivateSubnet1
    availabilityZone: _ZONE_
    id: "_SUBNET_"
    public: false
containerRuntime: docker
manageCertificates: true
kubernetesDashboard:
  adminPrivileges: true
  insecureLogin: false
amazonSsmAgent:
  enabled: true
  downloadUrl: https://github.com/DailyHotel/amazon-ssm-agent/releases/download/v2.0.805.1/ssm.linux-amd64.tar.gz
  sha1sum: a6fff8f9839d5905934e7e3df3123b54020a1f5e
kubeDns:
  autoscaler:
    coresPerReplica: 256
    nodesPerReplica: 16
    min: 2
kubeProxy:
  ipvsMode:
    enabled: false
    scheduler: rr
    syncPeriod: 300s
    minSyncPeriod: 60s
addons:
  clusterAutoscaler:
    enabled: false
  rescheduler:
    enabled: false
  metricsServer:
    enabled: true
  prometheus:
    securityGroupsEnabled: true
experimental:
  admission:
    podSecurityPolicy:
      enabled: false
    alwaysPullImages:
      enabled: false
    denyEscalatingExec:
      enabled: false
    initializers:
      enabled: false
    priority:
      enabled: false
    mutatingAdmissionWebhook:
      enabled: false
    validatingAdmissionWebhook:
      enabled: false
    OwnerReferencesPermissionEnforcement:
      enabled: false
    persistentVolumeClaimResize:
      enabled: false
  awsEnvironment:
    enabled: false
    environment:
      CFNSTACK: '{ "Ref" : "AWS::StackId" }'
  auditLog:
    enabled: false
    maxage: 30
    logpath: /dev/stdout
  authentication:
    webhook:
      enabled: false
      cacheTTL: 1m0s
      configBase64: base64-encoded-webhook-yaml
  awsNodeLabels:
    enabled: true
  tlsBootstrap:
    enabled: true
  nodeAuthorizer:
    enabled: false
  ephemeralImageStorage:
    enabled: false
  kube2IamSupport:
    enabled: false
  nodeDrainer:
    enabled: true
    drainTimeout: 5
    iamRole:
      arn: ""
  oidc:
    enabled: false
    issuerUrl: "https://accounts.google.com"
    clientId: "kubernetes"
    usernameClaim: "email"
    groupsClaim: "groups"
  disableSecurityGroupIngress: false
kubelet:
  RotateCerts:
    enabled: true
stackTags:
  Name: "Cluster _CLUSTER_NAME_"
  c1:env: "_ENV_"
  c1:cost-centre: "4473"
  c1:cluster: "_CLUSTER_NAME_"
  c1:cluster-type: "kubernetes"
  c1:owner: "_OWNER_"
  c1:supported-by: "Platform Management"
```
