### ISSUE TITLE
ELB Security group not added to worker when using worker.nodePools.loadBalancer spec

### ISSUE THREAD

**Issue by mdgreenwald** [kubernetes-incubator/kube-aws#1429]
**Expected behavior:**

The worker nodes are created with a security group policy which includes the ELBs security groups allowing all traffic from the ELB security groups which are associated with user managed load balancers.

```yaml
worker:
  apiEndpointName: default
  nodePools:
    - 
      name: nodepool1
      subnets:
      - name: ManagedPublicSubnet1
      loadBalancer:
        enabled: true
        names: [ "example-elb-1", "example-elb-2" ]
        securityGroupIds: [ "sg-1234abc", "sg-5678def" ]
```

**What happens instead:**

The worker nodes are created with a security group policy which does not contain ELB security groups and so the load balancers are not able to health check the instances.
