### ISSUE TITLE
Upgrade v0.10.2 (k8s 1.9.10) --> v0.11.0(k8s 1.10.5)

### ISSUE THREAD

**Issue by wolstena** [kubernetes-incubator/kube-aws#1458]
I'm in the process of trying to upgrade a k8s cluster provisioned with kube-aws 0.10.2 to k8s 1.10.5 using kube-aws 0.11.0. 

I have tried a couple things. In each case, the new etcd servers are unable to connect to the existing etcd servers. 

Running kube-aws apply using new kube-aws results in:
Error: failed to initialize cluster driver: failed to initizlie network stack: failed to read/create encrypted assets: error reading credential file credentials/kube-controller-manager.pem: credentials/kube-controller-manager.pem must exist. Please confirm that you have not deleted the file manually.

However, running:
 kube-aws render credentials --ca-cert-path=./credentials/ca.pem --ca-key-path=./credentials/ca-key.pem
  kube-aws render stack
  kube-aws apply

I also tried backing up the existing certs and then using them along with the newly generated certs with the same outcome. The new etcd servers cannot connect to the old ones. I was unable to netcat to the old etcd from the new etcd results in a timeout.

Is what I am trying possible or do I need to rebuild the cluster.

cluster.yaml

```
clusterName: ckube-a-common
s3URI: <redacted>
disableContainerLinuxAutomaticUpdates: true
apiEndpoints:
- name: default
  dnsName: <redacted>
  loadBalancer:
    private: true
    hostedZone:
      id: Z2ONWAFV9V0IHD
keyName: <redacted>
region: us-east-1
kmsKeyArn: "<redacted>"
controller:
  securityGroupIds:
    - sg-61ed811e
  autoScalingGroup:
    minSize: 1
    maxSize: 3
    rollingUpdateMinInstancesInService: 1
  iam:
    role:
      managedPolicies:
      - arn: arn:aws:iam::aws:policy/AmazonSSMFullAccess
  subnets:
    - name: PrivateSubnet1
  nodeLabels:
    kube-aws.coreos.com/role: controller
    central1.cluster/name: ckube-a-common
  customFiles:
    - path: "/etc/systemd/system/docker.service.d/10-custom.conf"
      permissions: 0644
      content: |
        [Service]
        Environment="DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3 --bip=192.168.0.1/16 --no-new-privileges"
worker:
  nodePools:
    - name: nodepool1
      subnets:
      - name: PrivateSubnet1
      securityGroupIds:
        - sg-61ed811e
      iam:
        role:
          managedPolicies:
          - arn: "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
      instanceType: m5.4xlarge
      autoScalingGroup:
        minSize: 1
        maxSize: 2
        rollingUpdateMinInstancesInService: 1
      autoscaling:
        clusterAutoscaler:
          enabled: true
      clusterAutoscalerSupport:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        central1.cluster/name: ckube-a-common
      customFiles:
        - path: "/etc/systemd/system/docker.service.d/99-bip.conf"
          permissions: 0644
          content: |
            [Service]
            Environment="DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3 --bip=192.168.0.1/16  --no-new-privileges"
workerInstanceType: m5.4xlarge
etcd:
  count: 3
  subnets:
    - name: PrivateSubnet1
  iam:
    role:
      managedPolicies:
      - arn: "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
  snapshot:
    automated: true
  memberIdentityProvider: emo
vpc:
  id: vpc-2d3b694b
vpcCIDR: "10.143.0.0/16"
subnets:
   - name: PrivateSubnet1
     private: true
     availabilityZone: us-east-1a
     id: "subnet-f1360cdc"
     routeTable:
       id: "rtb-d9dbbba0"
tlsCADurationDays: 3650
tlsCertDurationDays: 365
kubernetesVersion: v1.10.5
kubernetes:
  encryptionAtRest:
    enabled: false
  networking:
    selfHosting:
      enabled: true    # false will fall back to legacy coreos flannel/etcd2 installation
      type: canal      # either "canal" or "flannel"
      typha: false     # enable for type 'canal' for 50+ node clusters
containerRuntime: docker
manageCertificates: true
kubeResourcesAutosave:
  enabled: true
kubeSystemNamespaceLabels:
  name: kube-system
kubernetesDashboard:
  adminPrivileges: true
  insecureLogin: false
  enabled: true
cloudWatchLogging:
  enabled: true
  retentionInDays: 7
  localStreaming:
    enabled: true
amazonSsmAgent:
  enabled: true
  downloadUrl: https://github.com/DailyHotel/amazon-ssm-agent/releases/download/v2.2.546.0/ssm.linux-amd64.tar.gz
  sha1sum: cfe36dab08b55df61bc10e501615d7c11da46288
kubeDns:

  provider: kube-dns
  autoscaler:
    coresPerReplica: 256
    nodesPerReplica: 16
    min: 2
kubeProxy:
  ipvsMode:
    enabled: false
    scheduler: rr
    syncPeriod: 300s
    minSyncPeriod: 60s
addons:
  clusterAutoscaler:
    enabled: true
  rescheduler:
    enabled: false
  metricsServer:
    enabled: true
  prometheus:
    securityGroupsEnabled: false
experimental:
  admission:
    podSecurityPolicy:
      enabled: false
    alwaysPullImages:
      enabled: false
    denyEscalatingExec:
      enabled: true
    initializers:
      enabled: false
    priority:
      enabled: false
    mutatingAdmissionWebhook:
      enabled: false
    validatingAdmissionWebhook:
      enabled: false
    OwnerReferencesPermissionEnforcement:
      enabled: false
    persistentVolumeClaimResize:
      enabled: false
  awsEnvironment:
    enabled: false
    environment:
      CFNSTACK: '{ "Ref" : "AWS::StackId" }'
  auditLog:
    enabled: true
    logPath: /dev/stdout
  authentication:
    webhook:
      enabled: false
      cacheTTL: 1m0s
      configBase64: base64-encoded-webhook-yaml
  awsNodeLabels:
    enabled: false
  clusterAutoscalerSupport:
    enabled: true
  tlsBootstrap:
    enabled: true
  nodeAuthorizer:
    enabled: false
  ephemeralImageStorage:
    enabled: false
  kiamSupport:
    enabled: true
    image: 
      repo: quay.io/uswitch/kiam
      tag: v2.7
      rktPullDocker: false
    sessionDuration: 15m  
    serverAddresses:
      serverAddress: localhost:443
      agentAddress: kiam-server:443
  kube2IamSupport:
    enabled: false
  nodeDrainer:
    enabled: false
    drainTimeout: 5
    iamRole:
      arn: ""
  oidc:
    enabled: true
    issuerUrl: "_OATH_ISSUER_"
    clientId: "example-app"
    usernameClaim: "email"
    groupsClaim: "groups"
  disableSecurityGroupIngress: false
kubelet:
  RotateCerts:
    enabled: true
stackTags:
  Name: "Cluster ckube-a-common"
  c1:env: "common-services"
  c1:cluster: "ckube-a-common"
  c1:cluster-type: "kubernetes"
  c1:owner: "Jen Kins"
hostOS:
```

**Comment by mumoshu** [comment]
@wolstena Hey! Thanks for the report.

Would adding only `kube-scheduler` and `kube-controller-manager` keys and certs work for you?
That is, run:

```
kube-aws render credentials --ca-cert-path=./credentials/ca.pem --ca-key-path=./credentials/ca-key.pem
```

and then revert everything other than `kube-controller-manager-key.pem`, `kube-controller-manager-cert.pem`, `kube-scheduler-key.pem`, and `kube-scheduler-cert.pem`.

**Comment by wolstena** [comment]
@mumoshu your suggestions did the trick along with enabling selfHosting before the upgrade. I thought I had but I was mistaken. 

For anyone else:

cp -p credentials/* backup/
kube-aws render credentials --ca-cert-path=./credentials/ca.pem --ca-key-path=./credentials/ca-key.pem
cp -p backup/* credentials
kube-aws render stack
kube-aws validate
kube-aws apply

The next issue I have come across is the new controller is not launching. It is looping on the cni setup:

`
Sep 28 01:13:59 ip-10-143-13-122.aue1.central1.cc retry[2476]: Sleeping 3 seconds.
Sep 28 01:14:01 ip-10-143-13-122.aue1.central1.cc kubelet-wrapper[1302]: W0928 01:14:01.873042    1302 cni.go:171] Unable to update cni config: No networks found in /etc/kubernetes/cni/net.d
Sep 28 01:14:01 ip-10-143-13-122.aue1.central1.cc kubelet-wrapper[1302]: E0928 01:14:01.873699    1302 kubelet.go:2130] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
`

I suspect it is related to our selfHosting setup:

`
  networking:
    selfHosting:
      enabled: true    # false will fall back to legacy coreos flannel/etcd2 installation
      type: canal      # either "canal" or "flannel"
      typha: false     # enable for type 'canal' for 50+ node clusters
`

Do we need to specify any additional configuration.

**Comment by mumoshu** [comment]
I'm now seeing the same error on my test cluster.

Could you take logs from your, probably failing, controller-manager container?

```
$ docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                        PORTS               NAMES
39ea0592eb11        k8s.gcr.io/hyperkube-amd64:v1.10.5   "/hyperkube kubectl …"   1 second ago        Created                                           wizardly_lalande
9ed124410c57        k8s.gcr.io/hyperkube-amd64:v1.10.5   "/hyperkube kubectl …"   1 second ago        Created                                           vigilant_ardinghelli
2bd5b00172c3        6006241c0593                         "/hyperkube controll…"   32 seconds ago      Exited (255) 12 seconds ago                       k8s_kube-controller-manager_kube-controller-manager-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_85e935e01177a915de2e10d3a365860b_7
aa1f7da3b6f8        6006241c0593                         "/hyperkube schedule…"   13 minutes ago      Up 13 minutes                                     k8s_kube-scheduler_kube-scheduler-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_352b06fd450c7b49063bb0c98c7ab717_0
3d0736d76f48        6006241c0593                         "/hyperkube apiserve…"   13 minutes ago      Up 13 minutes                                     k8s_kube-apiserver_kube-apiserver-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_3facf922dd4ff0b2fb1d3470d000b9a6_0
8de2ef303c7d        k8s.gcr.io/pause-amd64:3.1           "/pause"                 13 minutes ago      Up 13 minutes                                     k8s_POD_kube-scheduler-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_352b06fd450c7b49063bb0c98c7ab717_0
b50330f7a0e8        k8s.gcr.io/pause-amd64:3.1           "/pause"                 13 minutes ago      Up 13 minutes                                     k8s_POD_kube-controller-manager-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_85e935e01177a915de2e10d3a365860b_0
47337f7c9c9e        k8s.gcr.io/pause-amd64:3.1           "/pause"                 13 minutes ago      Up 13 minutes                                     k8s_POD_kube-apiserver-ip-10-0-0-233.ap-northeast-1.compute.internal_kube-system_3facf922dd4ff0b2fb1d3470d000b9a6_0
```

```
$ docker logs 2bd5b00172c3
I0928 07:07:12.649622       1 controllermanager.go:116] Version: v1.10.5
W0928 07:07:12.650377       1 authentication.go:55] Authentication is disabled
I0928 07:07:12.650408       1 insecure_serving.go:44] Serving insecurely on [::]:10252
I0928 07:07:12.650560       1 leaderelection.go:175] attempting to acquire leader lease  kube-system/kube-controller-manager...
I0928 07:07:30.219250       1 leaderelection.go:184] successfully acquired lease kube-system/kube-controller-manager
I0928 07:07:30.239637       1 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"e03f8584-c098-11e8-b67b-0677f1f56d78", APIVersion:"v1", ResourceVersion:"344451", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-10-0-0-233.ap-northeast-1.compute.internal_1f82d3a2-c2ed-11e8-b939-0695f6f4e4bc became leader
I0928 07:07:30.261533       1 aws.go:1026] Building AWS cloudprovider
I0928 07:07:30.261572       1 aws.go:988] Zone not specified in configuration file; querying AWS metadata service
I0928 07:07:30.939882       1 tags.go:76] AWS cloud filtering on ClusterID: kubeaws1
I0928 07:07:30.942578       1 controller_utils.go:1019] Waiting for caches to sync for tokens controller
E0928 07:07:30.947285       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Secret: illegal base64 data at input byte 3
F0928 07:07:30.948067       1 client_builder.go:273] unable to get token for service account: illegal base64 data at input byte 3
```

The last error seems problematic, but not sure what's causing this yet.

**Comment by mumoshu** [comment]
Oops, so mine was due to that I've enabled `kubernetes.encryptionAtRest` and then disabled, which resulted in k8s controller-manager came up after disabling it resulted in unable to fetch encrypted secrets.

Maybe you cluster has its own reasons not coming up.

Firstly, could you try running `docker ps -a` to see if there is any container failing? Typically you could run `docker logs` against the failing container to see what's the cause.

**Comment by davidmccormick** [comment]
Hi, I would check the contents of /etc/kubernetes/ssl/service-account-key.pem to check whether you have a valid service account signing key in there.  Also, are you seeing any errors on the apiserver logs?

**Comment by wolstena** [comment]
The output from the controller logs indicates it is key related.  There may be a issue with the way I store and retrieve our certs in the upgrade process.   

docker logs 7b3ce72f242c (controller)
```E0928 17:50:19.537010       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: x509: certificate is valid for 10.3.0.1, not 127.0.0.1```

**Comment by wolstena** [comment]
When we originally generated our certs (~1.9.3) the apiserver.pem. These certs did not include 127.0.0.1 in the SAN list.  If you regenerated the certs they do. 

As part of a cluster upgrade, is it possible to regenerated all certs excluding etcd. Something along the lines of:

```
# backup existing credentials
cp -p credentials/* backup/
# generate new credentials
kube-aws render credentials --ca-cert-path=./credentials/ca.pem --ca-key-path=./credentials/ca-key.pem
# copy original etcd certs
cp -p backup/etcd* /credentials
kube-aws render stack
kube-aws apply
```

**Comment by mumoshu** [comment]
@wolstena Oh, good catch!

If you would be regenerating certs, you'd somehow figure out doing it with tools like openssl so that you can reuse the private keys to regenerate only certs, or enhance kube-aws to do it, which sounds like a hassle.

An alternative way would be to just rewrite cloud-config-controller so that controller-manager accesses the api via 10.3.0.1, not 127.0.0.1.

More concretely, could you change `127.0.0.1` to `10.3.0.1` in your `cloud-config-controller`?

```
  - path: /etc/kubernetes/kubeconfig/kube-controller-manager.yaml
    content: |
        apiVersion: v1
        kind: Config
        clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/ssl/ca.pem
            server: https://127.0.0.1
```

```
  - path: /etc/kubernetes/kubeconfig/kube-scheduler.yaml
    content: |
        apiVersion: v1
        kind: Config
        clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/ssl/ca.pem
            server: https://127.0.0.1
```

**Comment by mumoshu** [comment]
If that works, we could update kube-aws to expose a new template function named like `KubernetesServiceIPAddr` that looks like:

```
_, serviceNet, err := net.ParseCIDR(c.ServiceCIDR)
if err != nil {
	return nil, fmt.Errorf("invalid serviceCIDR: %v", err)
}
return netutil.IncrementIP(serviceNet.IP)
```

so that you can use it in `cloud-config-controller`:

```
  - path: /etc/kubernetes/kubeconfig/kube-scheduler.yaml
    content: |
        apiVersion: v1
        kind: Config
        clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/ssl/ca.pem
            server: https://{{ .KubernetesServiceIPAddr}}
```
