### ISSUE TITLE
kube-aws apply (update) The CIDR 'X.X.X.X/XX' conflicts with another subnet

### ISSUE THREAD

**Issue by devdemos** [kubernetes-incubator/kube-aws#1465]
Attempts to update an existing cluster encounters messages such as the below, leading to a failure and Rollback:

```
The CIDR 'X.X.X.X/XX' conflicts with another subnet (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnet.Conflict; Request ID: 5c450d2d-7c0a-474e-9e4e-da71ef7deb75)"
```

The conflict occurs as part of the process to create the Network Stack

```                                                                                                                 
kube-aws version v0.11.0
```

**Comment by mumoshu** [comment]
Yeah! Can you (1) remove the another, conflicting subnet in your VPC, or (2) change your subnet's `instanceCIDR` not to conflict with existing ones (3) use another VPC?

**Comment by mumoshu** [comment]
Yes. Or how about reusing existing subnets?

**Comment by devdemos** [comment]
The subnets we have in cluster.yaml are the same subnets we set the cluster up on, Hence were hoping to keep using them as part of the upgrade.
However looks like this will not be possible

**Comment by mumoshu** [comment]
Oh, are you saying that you have not altered `subnets:` section of your `cluster.yaml` at all, from the initial creation to the upgrade?

**Comment by mumoshu** [comment]
Are you sure you've specified `subnets[].id` in your `cluster.yaml`?

**Comment by devdemos** [comment]
Yes I have populated the `cluster.yaml` with the subnet information 
This config was used to bring up the cluster, and has remained unchanged as part of the update
```
subnets:
    - name: kservice-apse2a-sn
      private: false
      availabilityZone: ap-southeast-2a
      instanceCIDR: "10.122.77.0/26"
      routeTable:
       id: "rtb-123456"

    - name: kservice-apse2b-sn
      private: false
      availabilityZone: ap-southeast-2b
      instanceCIDR: "10.122.77.64/26"
      routeTable:
        id: "rtb-123456"

    - name: knode-apse2a-sn
      private: true
      availabilityZone: ap-southeast-2a
      instanceCIDR: "10.122.76.0/26"
      routeTable:
        id: "rtb-abcdbb"

    - name: knode-apse2b-sn
      private: true
      availabilityZone: ap-southeast-2b
      instanceCIDR: "10.122.76.64/26"
      routeTable:
        id: "rtb-abcdbb"
```
