### ISSUE TITLE
Feature: Cluster Autoscaling

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#148]
a.k.a [cluster-autoscaler](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler) Integration

I'd suggest something like the below in cluster.yaml to enable autoscaling of worker nodes based on pending pods.

```
# an auto scaling group
# see #142
worker:
  autoScalingGroup:
    minSize: 1
    maxSize: 20

# or a spot fleet (see #112)

worker:
  spotFleet:
    minSize: 1
    maxSize: 20

# which auto-scaling is enabled like:

experimental:
  workerClusterAutoscaler:
    enabled: true

# or

worker:
  clusterAutoScaler
    enabled: true

# or

worker:
  experimental:
    clusterAutoScaler:
      enabled: true
```

After thinking for a while about how we'd like [cluster-autoscaler](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler) to be deployed and managed to achieve auto-scaling of worker nodes in a main cluster or a node pool created via kube-aws, it turns out to be a bit cumbersome to fully automate it. It won't be a matter of just deploying it via `kubectl` and forget, at least.

## TL;DR;

How could we converge cluster-autoscaler to the desired state, without persisting the state outside of cluster?

## General questions

  * [x] To which node should we deploy cluster-autoscaler, controllers or workers?
     * Deploying it to worker nodes means it eats some resource we originally reserved for our application
     * cluster-autoscaler [is scheduled to master nodes on GCE, GKE](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler#deployment)
     * #150 is required if we'd like to deploy cluster-autoscaler to controller nodes
  * [x] Should we annotate cluster-autoscaler to be a "CriticalPod"?
     * We'd want cluster-autoscaler to survive resource shortage or we may end up unable to auto-scale nodes when in resource shortage(!)
     * If we'd like to annotate like that, rescheduler must be supported beforehand (#118)
     * [It is recommended to be a critical pod in cluster-autoscaler's doc](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler#deployment)

## kube-aws specific questions

  * How should we deploy cluster-autoscaler?
     * Via `kubectl apply -f <yaml file templated with vars like asg min/max size and asg name>`in cloud-config of worker nodes?
        * How could we let cluster-autoscaler stop managing specific ASG if it becomes unneeded?
            * How could we let cluster-autoscaler stop managing already deleted ASGs?
            * If we enabled auto-scaling on a ASG initially and then disabled afterwards, how could we let cluster-autoscaler stop managing the ASG?
  * How should we update cluster-autoscaler when an ASG's min/max size changed?
     * cluster-autoscaler is run like:
        ```
        cluster-autoscaler \
          --nodes <min size>:<max size>:<asg1> \
          --nodes <min size>:<max size>:<asg2> \
          ...
        ```
         to limit min/max num of nodes in an ASG.
     * If an ASG's min/max size is changed by `kube-aws update`, how should we update cluster-autoscaler accordingly?
        * `kubeclt apply -f something` to update cluster-autoscaler's args
           * Or configmap+inotifywait to watch for a configuration change?
        * How could we know which ASGs and spot fleets are linked to worker nodes?
           * Filter ASGs with the KubernetesCluster tag?
               * Doesn't work for Spot Fleet since it doesn't support tagging
                  * Filter CFN stacks with the KubernetesCluster tag and then find spot fleets managed by them? A bit cumbersome but would work.
        * If we don't do this, cluster-autoscaler won't scale (more than the max size|less than the min size) set before `kube-aws update` until we manually update it.
