### ISSUE TITLE
Allow managed subnets with existing route table and no NAT Gateway

### ISSUE THREAD

**Issue by colebrumley** [kubernetes-incubator/kube-aws#1494]
I am trying to use kube-aws to deploy a cluster into an existing VPC, using exclusively private subnets that kube-aws manages, connected to an existing route table. The route table's default route to `0.0.0.0/0` goes over a VPN gateway instead of a NAT gateway (we're using a transit VPC model where all egress traffic goes out through a managed firewall instance in another account). When I try to validate the cluster config I am getting the following error:

```
panic: No appropriate public subnet found for a non-preconfigured NAT gateway associated to private subnet ManagedPrivateSubnet1
```

The subnet config looks like this:

```yaml
subnets:
  - name: ManagedPrivateSubnet1
    private: true
    availabilityZone: us-east-2a
    instanceCIDR: "10.30.190.0/24"
    routeTable:
      id: "rtb-xxxxxxxx"
```

Based on [the code](https://github.com/kubernetes-incubator/kube-aws/blob/6e68d410c79f94796458086d3c2354ef0efbd969/core/controlplane/config/config.go#L1565) it looks like that error message only comes up when `privateSubnet.ManageNATGateway()` is true. Why is kube-aws trying to manage a NAT gateway? [The docs](https://github.com/kubernetes-incubator/kube-aws/blob/master/core/root/config/templates/cluster.yaml#L980) make it seem like using an existing route table means that I am responsible for ensuring there's a route to the internet, which I've done. kube-aws shouldn't be trying to manage a NGW for me.

I am using `kube-aws version v0.12.0`
