### ISSUE TITLE
Default kube-controller-manager resource limits causes OOMs in larger clusters

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes-incubator/kube-aws#1502]
I've had some issues rolling one of our larger clusters (137 nodes).  *kube-aws* is setting default controller memory request and limit of 100M.  This caused the `kube-controller-manager` to OOM continuously during out a roll out of kube-aws version v0.11.x.  What is interesting is that, as a user, I can pick a fairly large aws instance but the controller isn't able to make use of it because both its cpu and memory is throttled so low.

I suggest that we either do not set a memory limit on the `kube-controller-manager` or use the number of nodes in the cluster in calculating the default value.  (I was able to resolve my issues by specifying my own request/limit for the controller but I think that the default should be safer)

**Comment by c-knowles** [comment]
We had the same issue starting with clusters sized around a dozen instances. Could we set something intelligent based on the cluster size? Not sure if there is a recommendation anywhere.

**Comment by jorge07** [comment]
We experienced similar issues when managing more than 3k pods. Specially when scaling dramatically (400 new pods in a minute). 
Updated config:
```
kubernetes:
  controllerManager:
    resources:
      requests:
        cpu: 250m
        memory: 1G
      limits:
        cpu: 500m
        memory: 2G
```
