### ISSUE TITLE
Extend LoadBalancer service to support TLS for NLB

### ISSUE THREAD

**Issue by davidxjohnson** [kubernetes-incubator/kube-aws#1558]
I want to take advantage of [the recently announced](https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/) support for TLS termination on NLBs. Specifically, I want to use annotations on K8S LoadBalancer service to add certificate ARN, TLS policy and TLS protocol to the NLB listener. 

Perhaps the implementation would look like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:999999999:certificate/b86e3bda-df96-4648-81d5-5be1cb770c07
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: TLS
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```
