### ISSUE TITLE
etcd stack does not honor etcd.subnets: config for unmanaged subnets

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1579]
kube-aws built from master (master/5f14e23a+dirty) does not honer the list of subnets under etcd.subnets.

kube-aws 0.12.3 does not have this bug.

cluster.yaml
```
...
subnets:
  - name: gdo-vpc-PublicSubnetA
    availabilityZone: eu-west-1a
    id: "subnet-61f06216"
  - name: gdo-vpc-PublicSubnetB
    availabilityZone: eu-west-1b
    id: "subnet-71711b14"
  - name: gdo-vpc-PublicSubnetC
    availabilityZone: eu-west-1c
    id: "subnet-1c7ace45"
  
  - name: gdo-vpc-PrivateSubnetA
    availabilityZone: eu-west-1a
    id: "subnet-60f06217"
  - name: gdo-vpc-PrivateSubnetB
    availabilityZone: eu-west-1b
    id: "subnet-76711b13"
  - name: gdo-vpc-PrivateSubnetC
    availabilityZone: eu-west-1c
    id: "subnet-1f7ace46" 
...
etcd:
  count: 1
  instanceType: t3.medium
  tenancy: default
  rootVolume:
    size: 30
    type: gp2
    iops: 0
  dataVolume:
   size: 40
   type: gp2
   iops: 0
   encrypted: true
   # CAUTION: Currently broken. Please don't turn this on until it is fixed in https://github.com/kubernetes-incubator/kube-aws/pull/417
   ephemeral: false    
#  version: 3.1.11
  snapshot:
    automated: true
  disasterRecovery:
    automated: true
  subnets:
    - name: gdo-vpc-PrivateSubnetA
  memberIdentityProvider: eni
``` 

results in an etcd ENI in the etcd/stack.json created in a wrong sbunet (gdo-vpc-PublicSubnetA in this case)
```
    "Etcd0ENI": {
      "Properties": {
        "SubnetId": "subnet-61f06216",
        "GroupSet": [
          {
            "Fn::ImportValue": {
              "Fn::Sub": "${NetworkStackName}-EtcdSecurityGroup"
            }
          }
        ]
      },
      "Type": "AWS::EC2::NetworkInterface"
    },
```

I'm not sure if https://github.com/kubernetes-incubator/kube-aws/issues/1332 is related or not.
