### ISSUE TITLE
Cannot update network stack when CloudWatch logs is enabled

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1580]
kube-aws version master/1b146a42+dirty

CloudFormation rolls back due to missing CloudWatchLogGroupARN parameter 

```
root@xxxx/0.13.pre# ./kube-aws apply --pretty-print --targets network
This operation will create/update the cluster. Are you sure? [y,n]: y
generating assets for network
updating template url of network
generating assets for network
updating template url of network
Streaming filtered Journald logs for log group 'k8s6'...
NOTE: Due to high initial entropy, '.service' failures may occur during the early stages of booting.
Error: error updating cluster: error updating cluster: unexpected stack status: UPDATE_ROLLBACK_IN_PROGRESS
```

```
14:55:54 UTC+0200 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | k8s6 |  
-- | -- | -- | -- | --
  | 14:55:53 UTC+0200 | UPDATE_COMPLETE | AWS::CloudFormation::Stack | Network |  
  | 14:55:53 UTC+0200 | UPDATE_IN_PROGRESS | AWS::CloudFormation::Stack | Network |  
  | 14:55:51 UTC+0200 | UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS | AWS::CloudFormation::Stack | k8s6 |  
  | 14:55:47 UTC+0200 | UPDATE_COMPLETE | AWS::CloudFormation::Stack | Network |  
  | 14:55:19 UTC+0200 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | k8s6 | The following resource(s) failed to update: [Network].
  | 14:55:18 UTC+0200 | UPDATE_FAILED | AWS::CloudFormation::Stack | Network | Parameters: [CloudWatchLogGroupARN] must have values
  | 14:55:17 UTC+0200 | UPDATE_IN_PROGRESS | AWS::CloudFormation::Stack | Network |  
  | 14:55:10 UTC+0200 | UPDATE_IN_PROGRESS | AWS::CloudFormation::Stack | k8s6 | User Initiated
```

cluster.yaml
```
cloudWatchLogging:
  enabled: true
  retentionInDays: 7
  localStreaming:
    enabled: true
    filter:  '{ $.priority = "CRIT" || $.priority = "WARNING" && $.transport = "journal" && $.systemdUnit = "init.scope" }'
    interval: 60 
```
