### ISSUE TITLE
Multiple clusters/work pools with the same name in the same AWS account will not be possible with 0.13.0 (current master)

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1581]
https://github.com/kubernetes-incubator/kube-aws/pull/1531 introduced LaunchTemplates in replacement of  LaunchConfigurations. LaunchTemplates are an account wide (pr region) resource, and you cannot have two LaunchTemplates with the same name, even if the ID is different, in the same account and region.

cluster.yaml (test)
```
clusterName: k8s6
...
worker:
  nodePools:
    - name: normal
      instanceType: r5.large
      createTimeout: PT24M
      rootVolume:
        size: 75
        type: gp2
        iops: 0      
      subnets:
      - name: gdo-vpc-PrivateSubnetA
      - name: gdo-vpc-PrivateSubnetB
      - name: gdo-vpc-PrivateSubnetC
      autoScalingGroup:
        minSize: 0
        maxSize: 0
        rollingUpdateMinInstancesInService: 1
...
```

cluster.yaml (prod)
```
clusterName: k8s5
...
worker:
  nodePools:
    - name: normal
      instanceType: r5.xlarge
      createTimeout: PT24M
      rootVolume:
        size: 75
        type: gp2
        iops: 0      
      subnets:
      - name: gdo-vpc-PrivateSubnetA
      - name: gdo-vpc-PrivateSubnetB
      - name: gdo-vpc-PrivateSubnetC
      autoScalingGroup:
        minSize: 0
        maxSize: 0
        rollingUpdateMinInstancesInService: 1
...
```
When deploying k8s6 cluster a LaunchTemplate named normal will be created
![image](https://user-images.githubusercontent.com/9726307/55884248-0bac8600-5ba8-11e9-95ce-a10d95257af2.png)
PS, no tags are attached to the LaunchTemplate, which I think it should. The same way as the previous LaunchConfigurations where tagged.

If you try to deploy the second cluster (k8s5 from my example), it will fail beacuse it's not possible to have LaunchTemplates with the same name.
![image](https://user-images.githubusercontent.com/9726307/55884651-b7ee6c80-5ba8-11e9-93fb-d1a41d7880c4.png)

I suggest to either omit the LaunchTemplateName, as it's not mandatory
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html#cfn-ec2-launchtemplate-launchtemplatename
or concatenate the clusterName with the NodePoolName to create a cluster unique LaunchTemplateName value.
