### ISSUE TITLE
Make EventRateLimit admission controller plugin values configurable 

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#1614]
Currently the EventRateLimit admission controller plugin values are hard coded in the `/etc/kubernetes/auth/admission-control-eventconfig.yaml` file, that is created in the cloud-config-controller template. The hard coded values are

```
  - path: /etc/kubernetes/auth/admission-control-eventconfig.yaml
    content: |
      kind: Configuration
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      limits:
      - type: Namespace
        qps: 250
        burst: 500
        cacheSize: 4096
      - type: User
        qps: 50
        burst: 250
```

The nginx-ingress PODs will hit this limits in semi large clusters, when querying the API server for ingress objects during startup. In one of our clusters we have more then 1000 ingress rules, and errors like this starts to show up in the ingress POD during startup.

`E0603 12:10:19.127209       8 event.go:191] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"printingtools-nin.15a4af075fe5dc06", GenerateName:"", Namespace:"agscommon", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Ingress", Namespace:"agscommon", Name:"printingtools-nin", UID:"fa9adefa-85d3-11e9-ba87-02e23e825296", APIVersion:"extensions/v1beta1", ResourceVersion:"204638194", FieldPath:""}, Reason:"CREATE", Message:"Ingress agscommon/printingtools-nin", Source:v1.EventSource{Component:"nginx-ingress-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf35616a4b0f8206, ext:1505655353, loc:(*time.Location)(0x26192c0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf35616a4b0f8206, ext:1505655353, loc:(*time.Location)(0x26192c0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Too many requests: limit reached on type User for key system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount' (will not retry!)`
