### ISSUE TITLE
kube-aws-0.14.2 Unable to create cluster, due to worker pool 

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/kube-aws#1779]
I define a number of subnets and configure the node pool to be created in  `ManagedPrivateWorkerSubnet1e`. Inexplicably the node pool is created in the subnet `ExistingPublicSubnet1e`.

## cluster.yaml

```yaml
worker:
  nodePools:
  - name: pool-1e
    subnets:
      - name: ManagedPrivateWorkerSubnet1e
...
subnets:
  - availabilityZone: us-east-1e
    instanceCIDR: "10.30.47.0/24"
    name: ManagedPrivateElbSubnet1e
    private: true
    routeTable:
      id: "rtb-a1234567"
  - availabilityZone: us-east-1e
    instanceCIDR: "10.30.46.0/24"
    name: ManagedPrivateWorkerSubnet1e
    private: true
    routeTable:
      id: "rtb-b1234567"
  - availabilityZone: us-east-1e
    instanceCIDR: "10.30.45.0/24"
    name: ManagedPrivateSubnet1e
    private: true
    routeTable:
      id: "rtb-c1234567"
  - name: ExistingPublicSubnet1e
    availabilityZone: us-east-1e
    private: false
    id: "subnet-f7654321"
    routeTable:
      id: "rtb-d1234567"
```

## kube-aws/clusters/k9s-zoo/exported/stacks/nodepool1/stack.json

Notice that the LaunchConfig VPCZoneIdentifier is the subnet id of `ExistingPublicSubnet1e`
```
"VPCZoneIdentifier":["subnet-f7654321"]
```
