### ISSUE TITLE
node-pools render invalid template when using spotFleet

### ISSUE THREAD

**Issue by Overbryd** [kubernetes-incubator/kube-aws#186]
```console
$ kube-aws version
kube-aws version v0.9.3-rc.2
```

Steps to reproduce:

1. Create a node-pool using `spotFleet` configuration:

    ```yaml
    worker:
      spotFleet:
        iamFleetRoleArn: "arn:aws:iam::123....789:role/aws-ec2-spot-fleet-role"
        targetCapacity: 20
        # ...
    ```

2. Render the node-pool using `$ kube-aws node-pools render stack --node-pool-name your-node-pool-name`

3. Update/create the node-pool using `$ kube-aws node-pools update --node-pool-name your-node-pool-name --s3-uri=s3://your-bucket/your-node-pool-name`

    **Output:**

    ```console
    Error: Failed to render stack template: invalid character 'a' looking for beginning of value:
    json syntax error (offset=289), in this region:
    -------
    {
        "Type": "AWS::EC2::SpotFleet",
        "Properties": {
          "SpotFleetRequestConfigData": {
            "IamFleetRole": arn:aws:iam::123....789:role/aws-ec2-spot-fleet-role,
    ```

One can clearly see the invalid JSON of the `"IamFleetRolte"` key in `stack-template.json`.

**As a workaround** I am fixing the JSON syntax error by hand after rendering the stack.
