### ISSUE TITLE
My findings and suggestions

### ISSUE THREAD

**Issue by sasso** [kubernetes-incubator/kube-aws#271]
After working on this project I would like to share some of my findings and give some suggestions on how we can improve it. This is my view and I would love to hear maintainers thoughts on this and get a better sense of what your roadmap is and where you see this project in 3 months.

**1. ETCD deployment and management should not be a part of this project.**
This is one of the biggest issues for me and it makes running this project in production a real pain. It would be amazing if this could be managed with a tool like https://github.com/crewjam/etcd-aws or something similar. This would bring stability and security when dealing with ETCD.

**2. Project should be focused on both new and existing infrastructures**
By using resource tags like `Kube-AWS: <cluster>-etcd-node`, `Kube-AWS: <cluster>-worker`, `Kube-AWS: <cluster>-subnet` we would be able to reconstruct state and generate better CF templates. Based on state findings we could decide if we need to create new resources or if we should reuse existing ones.

**3. Node pools should be more tightly integrated**
There is a lot of separation between main cluster and node pools. It would be nice if we would only have controller at the top level and then worker pools that could all reside in one cluster config for easier maintenance. You would inherit default options and if needed override them on a node cluster level. It would also be nice if controller and node clusters would be a separated CF's as there is no big dependency between them

**4. Extending should be easy**
With hooks we could inject custom unit files that would allow us to extend the system and support some custom needs that you don't want in master

**5. No experimental tags**
It makes no sense to me to have experimental tags, in the long run it only makes more work for developers and users as they need to modify their templates. It would also be nice to break CF into smaller pieces and include parts/features when needed. By doing that we would move if's and loops out of templates and make codebase more maintainable.

Overall this is a great project and I'm looking forward to seeing it grow and mature. Great work guys!

**Comment by redbaron** [comment]
Here is my view:

1. don't agree, but **optionally** being able to point to existing etcd cluster and not to create it is a good feature to have.
2.you mean make kube-aws adopt existing setups? generally not possible, as existing resources cannot be "imported" into CF template. achieving this goal would mean ditching CF and move towards kops model. Use of CF is a huge win for **kube-aws**  for multiple reasons, freedom of customization is just one of them.
3. totally agree, see https://github.com/coreos/kube-aws/issues/238#issuecomment-272352977
4. already possibly by utilizing git workflow roughly described in a discussion https://github.com/coreos/kube-aws/issues/238#issuecomment-272047491 and below
5. agreee


I'd like to add another point:
6. Extreme code bureaucracy. For what should be a simple templater taking `cluster.yaml`, doing some modificiations and `templating stack-template.json`, code is very rigid and hard to change. `cluster.Cluster`,`config.Cluster`,`config.StackConfig`, `ProvidedConfig`, `ComputedConfig` all meaning same, but slightly different things.  I'll try to address that in future PR

**Comment by c-knowles** [comment]
Thanks @sasso for the feedback! Collectively we can only improve kube-aws with good feedback like yours.

My opinion:
1. Agree but optional, I might like to use shared compose.io etcd for some environments to avoid extra management.
2. It would be hard to maintain with the existing CF as @redbaron mentions, would mean quite an architectural change. I think the end result could be that it's harder to know what action will be performed. With CF change sets we'll get a clear picture of what the tool will change before running for free.
3. Agree, having used it I would prefer node pools were more integrated into primary setup. Node pools are already separate CF but default workers are not (but you can set workerCount to zero.
4. Agree, we also use a kind of git flow but it's harder to maintain than if we had native hooks for extension
5. Agree, I prefer to keep it simple
6. Agree, I think we could do with a round of dev to simplify and tidy

**Comment by sasso** [comment]
Thanks for fast responses!

We could have `kube-aws etcd up` and `kube-aws controller up` and `kube-aws worker up --name=storage` and keep the separation and also have nice support for node-pools

I may have given a bad example in 2. By doing separation in 1. you could generate independent CF with data taken from configs or state from AWS. By reading tags you could get ETCD IP's, Controller ELB and make CF more reliable and easier to use. I also think there should be no update option and just `up` as we should generate same template without mutation for up and update.

I am ok with CF and it's great for creating ASG's and SG's.

Also I don't take creating VPC lightly as in real life you don't just create a new VPC every day. There are a lot of things that needs to be set up like flowlogs, VPC links, security groups... and that will be hard to ever put into this project as the scope of it is huge. But I also think it's great to create it for newcomers but not be married to it as you loose advance users.

**Comment by redbaron** [comment]
what separate CF buys you? I'd much rather have one single CF which glues multiple others.

As for VPC, that is why your work on existing subnet feature is so much needed,but once done, it is done, righ? :)

**Comment by sasso** [comment]
It buys us control on what gets deployed and when. What I learned over time using CF is that breaking it to smaller pieces introduces less problems. It also gives you a way to move faster as you are working/touching smaller part of the codebase.

Subnet feature is in the works but it could be better (https://github.com/checkr/kube-aws/commit/76db40639e340d9dbf7abbd0a3605be4e60b44e4 my take on auto-populating ID's that got stuck on node pools and how validations are made differently there). 

Currently we are stuck and can't redeploy because of changes made to ETCD. I need to take a closer look at what's going on. Also one of the reasons that I started this thread :)

**Comment by redbaron** [comment]
I don't by the speed argument,I'd expect that time it takes to run CF update depends on amount of changes going in,not on a total number of resources specified in a template. Make fewer changes to CF between updates and you get your agility

**Comment by mumoshu** [comment]
Hi @sasso, thanks as always for your valuable feedbacks!

Would you let me ask about your auto-populated-subnet-IDs feature?
If I understand correctly, it is intended to make node pools inherit subnets from a main cluster?
If so, I'm considering to implement it on top of #284 so that in a main cluster's `cluster.yaml`:

// BTW, this is still an experimental feature and is subject to change according to the feedback from @redbaron. To fix the specs around it, feedbacks from contributors like you are necessary!
```yaml
subnets:
- name: public1
  instanceCIDR: ...
  availabilityZone: ...
- name: public2
  ...
```

and in a nodepool's `cluster.yaml`:

```yaml
subnets:
- name: public1
```

allows subnets to be inherited from the main to the node pool stack.

Could I have any comment on this?

**Comment by mumoshu** [comment]
@sasso @c-knowles @redbaron 

> It makes no sense to me to have experimental tags, in the long run it only makes more work for developers and users as they need to modify their templates.

Agreed. Then, can I just move all the experimental keys into the top-level of `cluster.yaml`?
If I recall correctly, they began to live under the `experimental` key to be explicit about they're experimental hence can change in backward incompatible ways at any time.
Are you guys ok to e.g. just add all the former experimental features comments describing their states like:

```yaml
# waitSignal configures worker and controller AGSs to wait until nodes are ready. This is an experimental feature but enabled by default for the convenience blah-blah-blah...
#waitSignal:
#  enabled: true
```

?

**Comment by mumoshu** [comment]
OR can I just say that everything is experimental and is subject to change until kube-aws reaches v1.0 some day? 😄
We'd been putting not little efforts to keep backward-compatibility where possible but on other hand that's true we are not "promised" it yet, anyways.

**Comment by sasso** [comment]
@mumoshu what I would like to see in future releases is combining node-pools into main cluster config

sample config

```
controller:
  # Instance type
  # CAUTION: Don't use t2.micro or the cluster won't work. See https://github.com/kubernetes/kubernetes/issues/18975
  instanceType: t2.medium
  # Intance tenancy. Options are "default" and "dedicated"
  # Documentation: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html
  instanceTenancy: default
  # Attached EBS volumes
  volumes:
    # Root Volume
    - mountpoint: /
      # Disk size (GiB)
      size: 30
      # Disk type (standard, io1, or gp2)
      type: gp2
      # Number of I/O operations per second (IOPS). Leave 0 if controllerRootVolumeType is not io1
      provisionedIOPS: 0
      # Indicates whether the volume is encrypted
      encrypted: false
  # Auto Scaling Group definition
  autoScalingGroup:
    minSize: 3
    maxSize: 4
    rollingUpdateMinInstancesInService: 3
    # Maximum time to wait in seconds for controller creation
    createTimeout: 900
  # Existing "glue" security groups attached to nodes which are typically used to allow access to services running on an existing infrastructure
  # securityGroupIds:
  #   - sg-1234abcd
  #   - sg-5678efab

workers:
  - name: standard
    # Instance type
    # CAUTION: Don't use t2.micro or the cluster won't work. See https://github.com/kubernetes/kubernetes/issues/18975
    instanceType: t2.medium
    # Intance tenancy. Options are "default" and "dedicated"
    # Documentation: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html
    instanceTenancy: default
    # Attached EBS volumes
    volumes:
      # Root Volume
      - mountpoint: /
        # Disk size (GiB)
        size: 30
        # Disk type (standard, io1, or gp2)
        type: gp2
        # Number of I/O operations per second (IOPS). Leave 0 if controllerRootVolumeType is not io1
        provisionedIOPS: 0
        # Indicates whether the volume is encrypted
        encrypted: false
    # Auto Scaling Group definition
    autoScalingGroup:
      minSize: 3
      maxSize: 4
      rollingUpdateMinInstancesInService: 3
      # Maximum time to wait in seconds for controller creation
      createTimeout: 900
```

I would also ditch config settings like `workers: 2` and always prefer advance options with defaults.

Allowing to specify and mount volumes would allow us to encrypt folders like `/etc/kubernetes`, `/var/lib/docker`, `/var/lib/rkt`... without encrypting root volume. Mounting this way would also clean up CF as you only need one loop to mount volumes.

**Comment by whereisaaron** [comment]
@mumoshu I took the experimental tag to be things that `kube-aws` may add or abandon at even a patch release. But I think they could be at the top level as you suggest, with a suitable comment in the generated `cluster.yaml`, e.g.

```
# Experimental: Worker nodes will be labelled with random zodiac signs
zodiacWorkerLabels: true
```

I think the older, alternative tags like `workers: 2` could be deprecated, if the generated `cluster.yaml` includes an example similarly simple set-up, and the more obscure options like `rollingUpdateMinInstancesInService` have sensible defaults such that the beginning user can leave them out.

```
workers:
   autoScalingGroup:
       minSize: 2
       maxSize: 2
```
This is not too hard for beginners to understand, and I find it confusing when there are two separate, and potentially conflicting ways, to specify the same setting.

Personal I am greatly enjoying the 'node-pools' feature, and like it the way it is now, with separate configurations and CF stacks. I now always deploy the controllers/etcd control plane separately with no worker nodes, and add and remove node-pools of different configurations as required.
