### ISSUE TITLE
0.9.4: Allow specifying a Ref for existing NATGateways

### ISSUE THREAD

**Issue by drock** [kubernetes-incubator/kube-aws#303]
When specifying private subnets using existing NATGateways in cluster.yaml you can specify the existing gateway using either its identifier or an output from another stack.  This means you can only reference a NATGateway from another CF stack.

It would be great if you could specify a "Ref" to a resource in the same stack though.  This would allow you to customize stack-template.json to add your own NATGateways and assign them to your private subnets specified in cluster.yaml.

In an attempt to work around #302 I setup my stack-template.json with a section like:
```go
{{range $index, $ngw := .CustomSettings.natGateways}}
    ,
    "{{$ngw.name}}EIP": {
      "Properties": {
        "Domain": "vpc"
      },
      "Type": "AWS::EC2::EIP"
    },
    "{{$ngw.name}}": {
      "Properties": {
        "AllocationId": {
          "Fn::GetAtt" : ["{{$ngw.name}}EIP", "AllocationId"]
        },
        "SubnetId": { "Ref" : "{{$ngw.subnet}}"}
      },
      "Type": "AWS::EC2::NatGateway"
    }
    {{end}}
```
In cluster.yaml it would be great if I could do something like:
```yaml
subnets:
   - name: EtcdSubnet1a
     private: true
     availabilityZone: us-east-1a
     instanceCIDR: "10.0.12.0/24"
     natGateway:
       idFromRef: NATGateway1a
   - name: EtcdSubnet1c
     private: true
     availabilityZone: us-east-1c
     instanceCIDR: "10.0.13.0/24"
     natGateway:
       idFromRef: NATGateway1c
customSettings:
  natGateways:
    - name: NatGateway1a
      subnet: PublicSubnet1a
    - name: NatGateway1c
      subnet: PublicSubnet1c
```
