### ISSUE TITLE
Option to specify node pool worker certificate path

### ISSUE THREAD

**Issue by johsim** [kubernetes-incubator/kube-aws#335]
I'm currently looking into the possibility to use kube-aws to deploy our cluster. However, my current setup is multi-tenant, and needs different worker keys/certificates for the different node pools. It would be awesome to have an option worker.nodePools[].certPath or similar to avoid using the "manageCertificates: false" option.

**Comment by mumoshu** [comment]
Hi @johsim! Thanks for the feedback.
How about adding `kubeletClientCertificatePath` and `kubeletClientKeyPath` under `worker.nodePools[]` to be consistent with configuration keys for kubelet in `kubeconfig`?

```yaml
apiVersion: v1
        kind: Config
        clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/ssl/ca.pem
        users:
        - name: kubelet
          user:
            client-certificate: /etc/kubernetes/ssl/worker.pem
            client-key: /etc/kubernetes/ssl/worker-key.pem
        contexts:
        - context:
            cluster: local
            user: kubelet
          name: kubelet-context
        current-context: kubelet-context
```
