### ISSUE TITLE
Feature: Restricted SSH access

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#338]
As of v0.9.4-rc.3, SSH access is granted to all addresses for controllers, workers, etcd. As an extra layer could we support restrictions on that?

In the case of public controllers but private etcd and workers, generally there may need to be a way to gain SSH access to the private workers by tunnelling through the public controllers. i.e. SSH access allowed from controller SG to worker SG. We could also say that we just support custom bastion and IP address/SG of the bastion has to be provided to allow SSH access to private assets.

**Comment by swestcott** [comment]
+1 for this.

I feel like there's some overlap with the "glue" security groups feature. If glue SGs where available to the workers, controllers & etcd user would be free to define their security controls as necessary. This would rely on being able to disable the SSH/0.0.0.0 rule.

**Comment by mumoshu** [comment]
@c-knowles @swestcott How about adding `sshAccessCIDR` to cluster.yaml?
It will default to `0.0.0.0/32` to keep backward compatibility but can be customized regardless of the subnet in which a worker/controller node is private/public.
Perhaps,`0.0.0.0/32` for private worker/controller nodes doesn't hurt? Or do we need a flag to disable the access completely?

An example cluster.yaml would look like:

```yaml
worker:
  nodePools:
  - name: pool1
    sshAccessCIDR: 0.0.0.0/32
  - name: private1
    sshAccessCIDR: <bastion subnet's CIDR>
    subnets:
    - name: privateSubnet1

controller:
  sshAccessCIDR: <bastion subnet's CIDR>

etcd:
  sshAccessCIDR: <bastion subnet's CIDR>
  subnets:
  - name: privateSubnet1
  ...
```

**Comment by swestcott** [comment]
Looks good, could `sshAccessCIDR` be a list of ranges inside?

**Comment by mumoshu** [comment]
Yes, with the name `sshAccessCIDRs`
2017年3月24日(金) 18:42 Si Westcott <notifications@github.com>:

**Comment by c-knowles** [comment]
@mumoshu your above idea seems good, I also would be fine with defining it ourselves in the glue SGs etc and then disabling `0.0.0.0/32` somehow like @swestcott mentioned. I assume nothing internal within the cluster needs SSH access for it to function. The only "harm" I can think of if always adding `0.0.0.0/32` to private nodes is those are then potentially accessible via public nodes in the same VPC (there could be many others). I think it's better practice to make these sorts of things non-global and more specific.

**Comment by mumoshu** [comment]
Thanks @c-knowles!
How about setting `sshAccessCIDRs` to an empty list or nil to disable `0.0.0.0/32`?
cluster.yaml would be like:
```yaml
worker:
  nodePools:
  - name: pool1
    sshAccessCIDRs:
    securityGroupIds:
    - <your-glue-sg-may-or-may-not-include-your-own-ssh-access-cidrs>
```

**Comment by c-knowles** [comment]
Assuming we can tell the difference between setting it to empty and it not being there in the YAML parsing, I think that's ok. Not entirely intuitive but I can't think of a better way right now. The only other ideas I had would be if the template just contained the following as the default, it's more verbose but it also makes the default immediately clear.
```
worker:
  nodePools:
  - name: pool1
    sshAccessCIDRs: 0.0.0.0/32
#    securityGroupIds:
#    - <your-glue-sg-may-or-may-not-include-your-own-ssh-access-cidrs>
```

Not setting the `sshAccessCIDRs` would mean no SSH access but `kube-aws` would still work as it did out of the box.

**Comment by mumoshu** [comment]
Thanks @c-knowles, your latter idea seems certainly verbose but clear. Hmm, I'll think of it for a while to see what's the most reasonable now.

**Comment by mumoshu** [comment]
Hmm...

```yaml
worker:
  nodePools:
  - name: pool1
    # CIDRs of networks you'd like SSH accesses to be allowed from. Defaults to ["0.0.0.0/32"]. 
    # Explicitly set to an empty array to completely disable it. If you do that, probably you would like to set securityGroupIds to provide this node pool an existing sg with a ssh access allowed from specific ranges.
    #sshAccessCIDRs:
    # - 0.0.0.0/32
    securityGroupIds:
    - <your-glue-sg-may-or-may-not-include-your-own-ssh-access-cidrs>
```
