### ISSUE TITLE
IAM role names are getting too long

### ISSUE THREAD

**Issue by ankon** [kubernetes-incubator/kube-aws#347]
In my cluster config:
```yaml
clusterName: collaborne-20170221
region: eu-west-1
controller:
    managedIamRoleName: "controller"
worker:
  nodePools:
    - name: production-workers
      managedIamRoleName: "production-worker"
```

This produces a role name like this: 
~~~~
collaborne-20170221-Productionworkers-PRK1CVQNY7XZ-eu-west-1-production-worker
~~~~

This is too long for AWS: role names can only have 64 or fewer characters.

I can see some redundancy I can trim, but ultimately it is really really getting tight :) 

EDIT: Forgot the purpose of this issue: I think it would be good to document this limitation, and make sure the user knows about it. But where?
