### ISSUE TITLE
cluster.yaml: Deprecate `controller*` and `etcd*` keys in favor of nested keys

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#372]
Make cluster.yaml a bit more clearer by deprecating `controller*` and `etcd*` keys in favor of nested keys and move those keys under the `controller` and `etcd `keys respectively.
Also introduce `rootVolume` and `dataVolume` keys in several places to make volume configuration more consistent across `worker`, `etcd` and `controller`.

Doing so would allow us to (1) remove duplicated code by reusing `model.RootVolume`, `model.EC2Instance` across Etcd/Worker/Controller (2) provide users more consistent view of configuration among controller, etcd, worker nodes.

After the changes, `cluster.yaml` would look like:

```yaml
worker:
  nodePools:
  - name: pool1
    count: 3
    instanceType: t2.medium
    rootVolume:
      size: 100
      type: gp2
      iops: 0
  - name: pool2
    spotFleet:
      launchSpecifications:
      - rootVolume:
          size: 100
          type: gp2
          iops: 0

controller:
  count: 3
  createTimeout: PT15M
  instanceType: t2.medium
  rootVolume:
    size: 30
    type: gp2
    iops: 0

etcd:
  count: 3
  instanceType: t2.medium
  tenancy: default
  rootVolume:
    size: 30
    type: gp2
    iops: 0
  dataVolume:
    size: 30
    type: gp2
    iops: 0
    ephemeral: false
    encrypted: false
```

instead of the current:

```yaml
worker:
  nodePools:
    name: pool1
    count: 3
    instanceType: t2.medium
    rootVolumeSize: 100
    rootVolumeType: gp2
    rootVolumeIOPS: 0
  - name: pool2
    spotFleet:
      launchSpecifications:
      - rootVolumeSize: 100
        rootVolumeType: gp2
        rootVolumeIOPS: 0

controllerCount: 3
controllerCreateTimeout: PT15M
controllerInstanceType: t2.medium
controllerRootVolumeSize: 30
controllerRootVolumeType: gp2
controllerRootVolumeIOPS: 0

etcdCount: 3
etcdInstanceType: t2.medium
etcdRootVolumeSize: 30
etcdRootVolumeType: gp2
etcdRootVolumeIOPS: 0
etcdDataVolumeEphemeral: false
etcdDataVolumeSize: 30
etcdDataVolumeType: gp2
etcdDataVolumeIOPS: 0
etcdDataVolumeEncrypted: false
etcdTenancy: default
```
