### ISSUE TITLE
No 'global' customSettings

### ISSUE THREAD

**Issue by jollinshead** [kubernetes-incubator/kube-aws#377]
If a cluster configuration contains customSettings variables required by both controllers and workers alike, there is no way to reference the variables via {{ .CustomSettings.XXXX }} in both controllers and workers without duplicating the customSettings variables in cluster.yaml.
Related to: https://github.com/coreos/kube-aws/issues/346

I propose a 'global' customSettings to be defined in cluster.yaml (which can be used in both controllers and workers); in addition to nodepool/controller specific customSettings that would override any existing global values.

**Comment by jollinshead** [comment]
A temporary workaround is to define customSettings at the start of cluster.yaml and reference the parameters in the nodePool section(s).

e.g.
```
# customSettings to be defined at the start of the file for now...
customSettings: &customSettings
 myVar1:
  val: ABC
  val2: DEF
 myVar2:
  anotherVal: 123

# Unique name of Kubernetes cluster. In order to deploy
# more than one cluster into the same AWS account, this
# name must not conflict with an existing cluster.

.........................
.........................
.........................

worker:
  nodePools:
    - # Name of this node pool. Must be unique among all the node pools in this cluster
      name: nodepool1

      .........................
      .........................
      .........................

      # User-provided YAML map available in control-plane's stack-template.json
      customSettings: *customSettings
```
