### ISSUE TITLE
Infer subnets when using 'controller: loadBalancer'

### ISSUE THREAD

**Issue by jollinshead** [kubernetes-incubator/kube-aws#416]
Currently, if we specify subnets in the controller and want to use a loadBalancer we have to duplicate our subnet entries in both 'subnets:' and 'loadBalancer:' :
```
controller:
  subnets:
    - name: PreDefinedSubnet1
  loadBalancer:
    private: true
    subnets:
      - name: PreDefinedSubnet1
```
Whereas the 'loadBalancer:' could infer the subnets defined above. 
Desired configuration: 
```
controller:
  subnets:
    - name: PreDefinedSubnet1
  loadBalancer:
    private: true
```
However, if subnets are not specified in 'loadBalancer:' kube-aws attempts to create subnets, but since they already exist the operation fails.
