### ISSUE TITLE
`kube-aws update` seems to unnecessarily recreate ASGs

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#427]
Since 0.9.4 there is new implementation of node pools. And it's not possible to update only concrete node pool. We experienced weird behaviour when we adding / removing / updating node pool. When we run `kube-aws update ...` all node pools (worker autoscaling group) initiate update even when they have no changes. Ex. we have _monitoring_ pool (we don't make any change here) and adding _staging_ pool after `kube-aws update ...` CF Stack for monitoring pool is updating and recreating autoscaling group for no reason.

**Comment by mumoshu** [comment]
Hi Patrik! Thanks for trying kube-aws.
Just a quick question but could you share me an example cluster.yaml to
reproduce the issue?
2017年3月21日(火) 21:52 Patrik Votoček <notifications@github.com>:

**Comment by Vrtak-CZ** [comment]
Btw we are using kube-aws `0.9.4` (latest stable)

```yaml```
clusterName: k8s-cluster
externalDNSName: kubernetes.ourdomain.com
amiId: "ami-4829072e"
createRecordSet: true
hostedZoneId: "Z3AAAAAAAAAAAA"
keyName: patrik-ntb
region: eu-west-1
kmsKeyArn: "arn:aws:kms:eu-west-1:1111111111111:key/ffffffff-4590-4cab-b3eb-999999999999"

controller:
  autoScalingGroup:
    minSize: 1
    maxSize: 3
  subnets:
    - name: MasterPrivateSubnet1
    - name: MasterPrivateSubnet2
    - name: MasterPrivateSubnet3
  loadBalancer:
    private: false
    subnets:
      - name: MasterPublicSubnet1
      - name: MasterPublicSubnet2
      - name: MasterPublicSubnet3

controllerInstanceType: t2.medium
workerCount: 0

worker:
  nodePools:
    - name: staging
      count: 1
      spotPrice: 0.03
      instanceType: r4.large
      subnets:
        - name: StagingPrivateSubnet1
        - name: StagingPrivateSubnet2
      targetGroup:
        enabled: true
        arns:
          - arn:aws:elasticloadbalancing:eu-west-1:1111111111111:targetgroup/k8s-staging-tg/1111111111111111
        securityGroupIds:
          - sg-bb07f1c2
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/pool: staging
        kube-aws.coreos.com/allocation: spot
        k8s.ourdomain.com/pool-namespace: staging

etcdCount: 1

etcd:
  subnets:
    - name: MasterPrivateSubnet1
    - name: MasterPrivateSubnet2
    - name: MasterPrivateSubnet3

etcdInstanceType: t2.medium

vpcId: vpc-aaaaaaaa
vpcCIDR: "10.11.0.0/16"

subnets:
  - name: MasterPublicSubnet1
    availabilityZone: eu-west-1a
    idFromStackOutput: network-management-public-az1
  - name: MasterPublicSubnet2
    availabilityZone: eu-west-1b
    idFromStackOutput: network-management-public-az2
  - name: MasterPublicSubnet3
    availabilityZone: eu-west-1c
    idFromStackOutput: network-management-public-az3
  - name: MasterPrivateSubnet1
    availabilityZone: eu-west-1a
    idFromStackOutput: network-management-private-az1
  - name: MasterPrivateSubnet2
    availabilityZone: eu-west-1b
    idFromStackOutput: network-management-private-az2
  - name: MasterPrivateSubnet3
    availabilityZone: eu-west-1c
    idFromStackOutput: network-management-private-az3

  - name: StagingPrivateSubnet1
    availabilityZone: eu-west-1a
    instanceCIDR: "10.11.141.0/25"
    private: true
    routeTable:
      idFromStackOutput: network-private-route-table
  - name: StagingPrivateSubnet2
    availabilityZone: eu-west-1b
    instanceCIDR: "10.11.141.128/25"
    private: true
    routeTable:
      idFromStackOutput: network-private-route-table

  - name: ProductionPrivateSubnet1
    availabilityZone: eu-west-1a
    instanceCIDR: "10.11.131.0/24"
    private: true
    routeTable:
      idFromStackOutput: network-private-route-table
  - name: ProductionPrivateSubnet2
    availabilityZone: eu-west-1b
    instanceCIDR: "10.11.132.0/24"
    private: true
    routeTable:
      idFromStackOutput: network-private-route-table
  - name: ProductionPrivateSubnet3
    availabilityZone: eu-west-1c
    instanceCIDR: "10.11.133.0/24"
    private: true
    routeTable:
      idFromStackOutput: network-private-route-table

kubernetesVersion: v1.5.4_coreos.0
```

when i adding this node-pool:

```yaml
- name: management
  count: 1
  spotPrice: 0.03
  instanceType: r4.large
  subnets:
    - name: MasterPrivateSubnet1
    - name: MasterPrivateSubnet2
    - name: MasterPrivateSubnet3
  targetGroup:
    enabled: true
    arns:
      - arn:aws:elasticloadbalancing:eu-west-1:1111111111111:targetgroup/k8s-management-tg/1111111111111111
    securityGroupIds:
      - sg-caed2ab3
  nodeLabels:
    kube-aws.coreos.com/role: worker
    kube-aws.coreos.com/pool: management
    kube-aws.coreos.com/allocation: spot
    k8s.ourdomain.com/pool-namespace: management
    k8s.ourdomain.com/monitoring: enabled
  elasticFileSystemId: fs-778c4fbe
```

It causes update _staging_ CF Stack (recreating autoscaling group) for no reason because i just added one more node pool (_management_).
