### ISSUE TITLE
Bug: Output says default endpoint managed by user

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#485]
On latest master, set `externalDNSName` and `hostedZoneId` to something and `createRecordSet: true`

~~Output of `render stack` says:~~
Output of `validate` says:

```
WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "k8s-OBFUSCATED" managed by YOU!
```

However, I think this is not true - the endpoint it managed by kube-aws.

**Comment by mumoshu** [comment]
@c-knowles Thanks for the report 👍 
However I can't reproduce it - could you verify that `hostedZoneId` is also specified?

**Comment by c-knowles** [comment]
Yes it, updated above.

**Comment by mumoshu** [comment]
@c-knowles Hmm, that's odd... Would you mind sharing me an example cluster.yaml to reproduce the issue?

**Comment by c-knowles** [comment]
Yep sure. It's an entirely new cluster I've been using to test the rescheduler. I've cut out all cluster.yaml comments and I'm left with just this:

```
clusterName: k8s-dev-v1
externalDNSName: k8s-dev-v1.REDACTED
createRecordSet: true
hostedZoneId: REDACTED
keyName: REDACTED
region: eu-west-1
kmsKeyArn: "arn:aws:kms:eu-west-1:REDACTED"
controller:
 autoScalingGroup:
   minSize: 2
   maxSize: 3
   rollingUpdateMinInstancesInService: 1
 subnets:
   - name: ManagedPublicSubnet1
   - name: ManagedPublicSubnet2
   - name: ManagedPublicSubnet3
worker:
  nodePools:
    - name: nodepool1
      subnets:
        - name: ManagedPublicSubnet1
    - name: nodepool2
      subnets:
        - name: ManagedPublicSubnet2
    - name: nodepool3
      subnets:
        - name: ManagedPublicSubnet3
subnets:
  - name: ManagedPublicSubnet1
    availabilityZone: eu-west-1a
    instanceCIDR: "10.0.100.0/24"
  - name: ManagedPublicSubnet2
    availabilityZone: eu-west-1b
    instanceCIDR: "10.0.101.0/24"
  - name: ManagedPublicSubnet3
    availabilityZone: eu-west-1c
    instanceCIDR: "10.0.102.0/24"
addons:
  rescheduler:
    enabled: true
```
