### ISSUE TITLE
Worker node pool takes much time to create IAM role and instance profile

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#500]
![image](https://cloud.githubusercontent.com/assets/22009/24688239/a9321392-19f9-11e7-9ef0-27c1ccf3f3bc.png)

Can we just create a default worker role/instance profile in a control-plane stack and then import them to worker node pool stacks so that we can cut 2 or 3 min down per an additional worker node pool?

**Comment by mumoshu** [comment]
@redbaron @c-knowles @danielfm Do you have any thoughts on this?

**Comment by c-knowles** [comment]
Would `IAMRoleWorker` then need to be shared also? `IAMInstanceProfileWorker` refers to it and since the worker CF refers to controlplane CF but not vice versa, I think this would be the case.

If we did this, these are the switches we have in `IAMRoleWorker` which we'd have to consider the original use case and whether those need overrides or not:
1. `.ManagedIamRoleName`, probably ok to share between pools
1. `.Kube2IamSupport.Enabled`, share between pools
1. `.AssetsEncryptionEnabled`
1. `.WaitSignal.Enabled`, probably ok to share between pools
1. `.AwsNodeLabels.Enabled`
1. `.ClusterAutoscalerSupport.Enabled`
1. `.SpotFleet.Enabled`, do not think this can be shared between pools
1. `.LoadBalancer.Enabled` / `.TargetGroup.Enabled`

**Comment by mumoshu** [comment]
@c-knowles Ah, good catch! It seems to be harder than I had initially thought then.

**Comment by Fsero** [comment]
would not be better to give nodepools the ability to attach a preexisting IAM role and we optionally could create one worker role in control plane to attach?

**Comment by mumoshu** [comment]
@Fsero sounds cool but I'm wondering how we could implement an intuitive
configuration syntax for that.
Also, how would you like to ensure that an iam role provided by you has
enough policies for what features are enabled for the node pool?
2017年4月6日(木) 22:08 Fabián Sellés Rosa <notifications@github.com>:

**Comment by Fsero** [comment]
@mumoshu i'm not sure either about how implement this in a sane / easy way but i'm eager to write a PoC for that if it's interesting. One naive approach will be create a new key under worker block named like WorkerUseExistingIamRoleArn and attach the arn.

Regarding the second question i think the easiest way to achieve that is to create a customer managed policy (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html) that way you can ensure that the list of permissions listed on the managed policy is the minimum set required.

Both features combined also opens the way for people that want to have extra policies, because you would create an external IAM role, attach the managed policy and add others policies inline for your particular use case.

**Comment by c-knowles** [comment]
@Fsero I think that may be covered by https://github.com/kubernetes-incubator/kube-aws/issues/340?

**Comment by mumoshu** [comment]
@Fsero Btw, the most time consuming seems to be a creation of an instance profile, rather than an iam role according to my screen capture above.
We need something like `WorkerUseExistingInstanceProfileName` then

**Comment by mumoshu** [comment]
Now, I'm considering to create `IAMRole<Hash>` and `InstanceProfile<Hash>` on a "control-plane" stack. `<Hash>`  can be computed by hashing the list of values of flags sorted by their names.
The list of flags contains what @c-knowles noted in the [above comment](https://github.com/kubernetes-incubator/kube-aws/issues/500#issuecomment-292055102).
`InstanceProfile<Hash>` can be imported from a node pool stack by name hence avoiding to create an instance profile per node pool stack.

**Comment by mumoshu** [comment]
Also, we can introduce `instanceProfile` which defaults to a `InstanceProfile<Hash>` in control-plane like:

```yaml
worker:
  nodePools:
  - name: pool
    instanceProfile:
      idFromStackOutput: <ControlPlaneStackName>-<InstanceProfile<Hash>>
```

and optionally able to be customized to provide an existing instance profile:

```yaml:
worker:
  nodePools:
  - name: pool
    instanceProfile:
      id: <ExistingInstanceProfileName>
```

**Comment by Fsero** [comment]
@mumoshu the IAMRole<Hash> part doesnt play nice with kube2iam scenarios where you want to the IAM role to be stable, that means the option to survive between cluster recreations. As you said the most time consuming part is the creation of instanceprofile and it should be possible to attach to an existing instanceprofile in nodepools and create an instance profile in controlplane attached to an stable IAM Role name like $CLUSTER-IamRole-Worker.

so i think that your idea of extending worker config to accept instanceprofiles is :+1: , but i will add an iam block in cluster.yaml like the following to handle Roles.

`iam:
   worker:
      managed: true 
      # kube-aws will create an IAM role named like ${AWS:Stack}-IamRoleWorker-$RANDOMID
...
`

`iam:
   worker:
      managed: true
      NamedRole: YourNamedRole 
      # kube-aws will create an IAM role named like ${AWS:Region}-YourNamedRole
..
`
the region is to follow the AWS Named Roles recommendations to avoid clashes between regions.



`iam:
   worker: 
      managed: false
      ExistingWorkerRoleArn: arn:aws:iam::980851552428:role/Role
  controller: 
      managed: false
      ExistingControllerRoleArn: arn:aws:iam::980851552428:role/Role
  etcd: 
      managed: false
      ExistingEtcdRoleArn: arn:aws:iam::980851552428:role/Role
  
`
Then in the controlplane stack we just need to create an InstanceProfile attached to a role created by kube-aws or to an existing one, as discussed previously the way to ensure existing roles has enough permissions is to use a customer managed policy.

**Comment by Fsero** [comment]
@c-knowles i think that one is one piece of the puzzle, yes :smile:

**Comment by mumoshu** [comment]
@Fsero Thanks for your feedbacks!
Several things:
* Is `NamedRole` equivalent to `(worker|controller).managedIamRoleName` which already exists in cluster.yaml?
* I prefer worker/controller/etcd specific settings to reside under `worker`, `controller`, `etcd` respectively, rather than `iam.(worker|controller|etcd)`
* `managed: false` seems to be redundant - Specifying `ExistingWorkerRoleArn` would imply `managed: false` in your example, right?
* Does `iam.worker.ExistingWorkerRoleArn` get applied to all the worker node pools? Or just one of them? If it was latter, it won't work... Each node pool would need a different policies hence role.
* However I now understand the needs to stabilize role names after the possible change - so how about:

```yaml
worker:
  nodePools:
  - name: pool1
    managedIamRoleName: myRole1
    kube2iamSupport:
      enabled: true
  - name: pool2
    # As pool2 has a set of iam policies different from that of pool 1, if we set the `managedIamRoleName` to myRole1 would be a validation error!
    managedIamRoleName: myRole2
    kube2iamSupport:
      enabled: true
    awsNodeLabels:
      enabled: true
```

and then kube-aws creating IAM roles and instance profiles whose names are suffixed with "myRole1" and "myRole2" respectively in a control-plane stack?

To be extra clear, the following case should result in a validation error:

```yaml
worker:
  nodePools:
  - name: pool
    instanceProfile:
      id: <ExistingInstanceProfileName>
    # You can't customize the role name because you've specified an unmanaged instance profile with an existing IAM role associated to it!
    managedIamRoleName: myRole1
```

And the following should be valid as long as the existing instance profile has a trusted iam role already attached:

```yaml
worker:
  nodePools:
  - name: pool
    instanceProfile:
      id: <ExistingInstanceProfileName>
    kube2IamSupport:
      enabled: true
```
