### ISSUE TITLE
Docker bip configuration change

### ISSUE THREAD

**Issue by qpaulson** [kubernetes-incubator/kube-aws#502]
I'm having an issue with my cluster connecting to my private docker registry.
My registry is on a network within my organization on a 172.17.x.x network.

Unfortunately, I've tracked it down to the fact that this is the default BIP configuration for docker so I cannot route to my personal network as all requests are trying to be routed to docker.

I've found some cloud-init configuration that allows me to change the bip docker config, and I can do it manually via EC2 and a new instance of CoreOS, however I cannot figure out the "correct" way to do this with kube-aws..  My initial thought was to inject my cloud-init snippet into the cloud-config-worker yaml file before issuing the up command, but this seems hokey. 

Something like this is what I need to add:
coreos:
  units:
    - name: docker.service
      drop-ins:
        - name: 10-docker.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--bip=1.2.3.4/24 --fixed-cidr=1.2.3.4/24"

Is there a way to add/modify the generated cloud-init yaml via kube-aws?

Thanks

**Comment by mumoshu** [comment]
Hi @qpaulson, thanks as always for trying kube-aws!
I believe injecting your snippets into cloud-config files is a correct way, especially when you rely on [the git-based workflow @redbaron suggests](https://github.com/kubernetes-incubator/kube-aws/issues/462).
On the other hand, I understand that some users want to complete all the customizations in cluster.yaml.

How about enabling to customize `DOCKER_OPTS` in cluster.yaml like suggested in #134?

```yaml
docker:
  options:
  - bip: 1.2.3.4/24
  - fixed-cidr: 1.2.3.4/24
  # To keep the kube-aws's default docker opts: DOCKER_OPTS=--log-opt max-size=50m --log-opt max-file=3
  - log-opt: maxsize=50m
  - log-opt: max-files=3
```

@redbaron Would you like the configuration syntax above? Or more simpler ones like https://github.com/kubernetes-incubator/kube-aws/issues/134#issuecomment-271747021?
Regarding the latter, I'm afraid that users forget to include the default `log-opt`s in their own `docker.opts` string ❓
