### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#509]
Would it be useful/possible to introduce "kube-aws plugins" to define sets of configurations and resources(settings, k8s manifests, required iam policies, etc) used to extend kube-aws, without complicating the core of kube-aws?

For example, I guess with the feature, #507 can be implemented as a plugin composed of:

## Design 1

* `plugins/enabled/`
  * `<unique name of an instance of plugin e.g. cluster-dump>/`
    * `controller`
      * `manifests/`
         * `cluster-dump.yaml.tmpl` with the content of [cluster-dump.yaml](https://github.com/kubernetes-incubator/kube-aws/pull/507/files#diff-ef25536c536667a40b993d4d24ab7567R795)
      * `iam-policies/`
        * `allow-puts-to-s3-path.json.tmpl` with the content of [the iam policy required by cluster-dump](https://github.com/kubernetes-incubator/kube-aws/pull/507/files#diff-7824eb2dc187893e9c52944adc99cebcR331)

Intentions:

* The directory is named `plugins/enabled/<unique name of an instance of plugin>` so that
  * we can later introduce `plugins/available/<unique name of a plugin>` for defining a plugin=a template of instances of plugin
* The `controller` directory is there to place controller node specific files and settings

## Design 2 

* `plugins/available/`
  * `<unique name of a plugin e.g. cluster-dump>/`
    * `controller`
      * `manifests/`
         * `cluster-dump.yaml.tmpl`
      * `iam-policies/`
        * `allow-puts-to-s3-path.json.tmpl`
* `cluster.yaml`
  * With the new configuration key to allow enabling and customizing plugins
     ```yaml
     clusterName: ***
     externalDNSName: ***
     kmsKeyARN: ***
     *snip*
     plugins:
       clusterDump:
       - pluginName: <unique name of a plugin e.g. cluster-dump>
           s3Prefix: <customs3prefix_to_where_cluster_is_dumped>
       rescheduler:
       - pluginName: rescheduler
    ```

and we bundle default plugins into kube-aws binaries, but putting files to `plugins/available` would allow customizing a default plugin.

---

@c-knowles I can't locate the exact link to it but if I remember correctly, we've discussed before about introducing "plugins" to make kube-aws extendable by users?

**Comment by jeremyd** [comment]
I think that yes, many plugins of this style are simply needing to add to the cloud-config units or files section, with this PR this can be done in a generic way. https://github.com/kubernetes-incubator/kube-aws/pull/510 ; 

There is the need for additional IAM configuration in the PR for S3 dumps.  Perhaps IAM is the other configuration option that could be implemented generically.

**Comment by c-knowles** [comment]
@mumoshu I think plugins or addons have been discussed in a few places. The ones I can think of:
* [Addons discussion for rescheduler](https://github.com/kubernetes-incubator/kube-aws/issues/118#issuecomment-267946228)
* [Hooks for snippets of CF](https://github.com/kubernetes-incubator/kube-aws/issues/96#issuecomment-263835808)
* [Custom IAM polices](https://github.com/kubernetes-incubator/kube-aws/issues/340#issuecomment-281682323)
* [Restricted SSH access](https://github.com/kubernetes-incubator/kube-aws/issues/338#issuecomment-285213770)

Many kubernetes addons or even some application kube-aws users deploy require them to edit various aspects of the cluster. It could be edited IAM, adding RBAC policies, adding CF resources or various other things. Ultimately as we know, we need to decide how many of these we wish to actively support as top tier features. There's ways to do all of the above with @redbaron's git workflow without changing kube-aws at all. So one option is to only support that method.

I've always thought plugins would be good so we get a bit of both worlds - 1) we stop having to encapsulate each and every feature/addon into kube-aws and 2) we still allow users to more easily connect their additions in, not just well know addons like we support but anything they wish.

I would go as far as saying some things currently implemented in kube-aws as top tier features should actually be removed and just use the plugin system. For example, the rescheduler and kube2iam probably belong there.

If we go the plugin way, I think we should provide a `contrib` folder with plugins that are at least validated at a basic level.

As for the designs, I'm not sure I fully understand the intentions of 1 but I think I prefer 2.
* Do we wish to add as well as manifests and IAM policies? Good to start simple though.
* I was also thinking that even "core" aspects should be plugins that are enabled by default, maybe even impossible to switch off. We could try at first to separate out something like RBAC or the autoscaler and have them use the exact same plugin mechanism. I've used a few systems which are entirely pluggable like Serverless or Metalsmith and a lot of the power comes from the built in features using the same plugin mechanism.

**Comment by mumoshu** [comment]
@jeremyd @c-knowles Thanks for feedbacks 👍 

Regarding the IAM configuration part of the imaginary plugin system, would you like the `iam-policies` directory in the above examples?

**Comment by c-knowles** [comment]
Seems a reasonable start to me but also happy if we start with a single use case.

**Comment by mumoshu** [comment]
I'm extending the design 2 of the plugin system like shown below - @c-knowles @jeremyd Would you like it? Which part do you need for the first release of the "plugin system" feature?

* `<kube-aws root>/builtin/plugins/`
  * `<unique name of a plugin e.g. cluster-dump>/`
    * `plugin.yaml`

      ```yaml
      # plugin.yaml defines "parameters" correspond to `arguments` passed via top-level/controller's/worker's `pluginConfgurations.<pluginName>` in cluster.yaml
      controller:
        parameters:
          myVar: 
            type: string
      worker:
        parameters:
          myVar:
            type: string          
      ```
    * `worker/` worker specific customizations
    * `controller/` controller specific customizations
      *  `node/` controller node specific customizations
         * `manifests/` k8s manifests persisted under /srv/kubernetes/manifests to be deployed to k8s via kubectl apply -f
           * `cluster-dump.yaml.tmpl`
         * `static-pods/` k8s static pods persistend under /etc/kubernetes/manifests to be deployed via kubelet --pod-manifest-path
           * `your-static-pod-spec.yaml.tmpl`
      * `cfn-resources/` 
        * `your-single-required-cfn-resource.json.tmpl`
        * `iam-policies/` iam policies added to the managed IAMRoleController
          * `allow-puts-to-s3-path.json.tmpl`

* `your work tree/`
  * `adhoc-plugins/`
    * `<unique name of your adhoc plugin e.g. myCustomizations>`/
  * `cluster.yaml`
    * With the new configuration key to allow enabling and customizing plugins

      ```yaml
      clusterName: ***
      externalDNSName: ***
      kmsKeyARN: ***
      *snip*

      # All the plugins needs to be enabled under the `enablePlugins` key in a cluster.yaml
      enabledPlugins:
      #- <unique name of a plugin e.g. cluster-dump in lowerCamelCase>:
      #  myKeyDefinedInThePluginYaml: foo
      - clusterDump:
        s3Prefix: <customs3prefix_to_where_cluster_is_dumped>
      - rescheduler:
        enabled: true

      # If you'd like to customize settings not for the whole cluster but just for controller nodes...
      controller:
        pluginConfigurations:
          clusterDump: #Only a plugin enabled under enablePlugins can be configured
            dumpInterval: 1h
            keptRevisions: 3

      # If you'd like to customize settings passed to a plugin per node pool...
      worker:
        nodePools:
        - name: pool1
          pluginConfigurations:
            nameOfPlugin:
              myVar: foo
        - name: pool2
          pluginConfigurations:
            nameOfPlugin:
              myVar: bar
      ```
