### ISSUE TITLE
Expected way to access API server from pods on HA controllers

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#512]
### Summary

I finally managed to work on my comment from https://github.com/kubernetes-incubator/kube-aws/issues/409#issuecomment-286950126 to figure out what is going on. I tried quite a few combinations of connectivity from Daemon Set pods to API server in a HA controller environment and there seems to be some problems. I'm not entirely sure of the root cause. I have not tested with a single controller.

My current tests show:
1. `dnsPolicy: ClusterFirst` + `KUBERNETES_SERVICE_HOST` env variable has issues on only some controllers
1. `dnsPolicy: Default` + `KUBERNETES_SERVICE_HOST` env variable has issues on all controllers (expected I think)
1. `dnsPolicy: ClusterFirst` + `externalDNSName` from `cluster.yaml` seems ok
1. `dnsPolicy: ClusterFirst` + `kubernetes.default.svc.cluster.local` has issues on only some controllers even in containers that will resolve that domain correctly (I'm aware that some images don't play nicely with kube DNS)

So 3 seems to work ok but I'm still not sure 1/4 are the expected behaviour. The slightly confusing bit for me is that when I say "some" above it is because when I was initially diagnosing this problem I went about terminating controller nodes via AWS to see if brand new nodes had the same problems. In the case of 4, sometimes both controllers would work fine and sometimes just one would work but usually neither! With 1, the situation seems to be similar but most of the time neither of the controllers work.

It could be me misconfiguring, but the intermittent behaviour makes me think something else is wrong. The environment variable `KUBERNETES_SERVICE_HOST` is used by some apps/addons to access the API server via service accounts so I think it should work ok. `kubernetes.default.svc.cluster.local` should definitely certainly work with `ClusterFirst` DNS.

### Steps to reproduce
1. Spin up a cluster with HA controller, I used 2 controllers
2. Deploy the Daemon Set below, it just periodically tries to connect to the API server. There are a few combinations in there which can be tried
3. Follow the logs on the containers running on the controllers, you should see it times out while trying to connect:
```
✗ stern --since 1m --namespace=kube-system service-account-test
+ service-account-test-9q0wk › test
service-account-test-9q0wk test connect: Operation timed out
service-account-test-9q0wk test connect:errno=110
service-account-test-9q0wk test verify depth is 1
```
4. If you don't see timeouts, try terminating a controller node and check the behaviour on the new node that replaces it.

### Details
I don't have anything particularly complex in the cluster.yaml but can share it if needed. I checked the environment variables in pods that are timing out all it always looks fine:
```
KUBERNETES_SERVICE_HOST=10.3.0.1
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
```

### Workaround
As above I found 3 works so setting `KUBERNETES_SERVICE_HOST` in the Daemon Set to the value of `externalDNSName` from `cluster.yaml` the problems go away, at least in my initial tests. In my case this DNS name keeps changing as it is versioned with the cluster so I would probably define a more static internal endpoint using https://github.com/kubernetes-incubator/kube-aws/issues/373. If we have any apps using `kubernetes.default.svc.cluster.local` then it becomes a bit more tricky (since some are not ours).

----

### Test Daemon Set

```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: service-account-test
  namespace: kube-system
  labels:
    k8s-app: service-account-test
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: service-account-test
  template:
    metadata:
      labels:
        k8s-app: service-account-test
        kubernetes.io/cluster-service: "true"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key": "node.alpha.kubernetes.io/ismaster", "effect": "NoSchedule"}]'
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: test
          image: centurylink/openssl
          command:
            - '/bin/sh'
            - '-c'
            # dnsPolicy: ClusterFirst + KUBERNETES_SERVICE_HOST = issue on some controllers
            # dnsPolicy: Default + KUBERNETES_SERVICE_HOST = issue on all controllers
            - 'while true; do echo "Q" | openssl s_client -showcerts -connect $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -verify 1 -verify_return_error; sleep 30; done'

            # dnsPolicy: ClusterFirst + `externalDNSName` = ok
            # - 'while true; do echo "Q" | openssl s_client -showcerts -connect <externalDNSName from cluster.yaml>:$KUBERNETES_SERVICE_PORT -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -verify 1 -verify_return_error; sleep 30; done'

            # dnsPolicy: ClusterFirst + `kubernetes.default.svc.cluster.local` = intermittent
            # - 'while true; do echo "Q" | openssl s_client -showcerts -connect kubernetes.default.svc.cluster.local:443 -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -verify 1 -verify_return_error; sleep 30; done'
```
