### ISSUE TITLE
Statefulset: unresponsive container, locked in pending state

### ISSUE THREAD

**Issue by PuKoren** [kubernetes-incubator/kube-aws#536]
Hello there,

kube-aws version used for the cluster: `v0.9.5-rc.6`

## Statefulsets becomes unresponsive randomly
Sometimes (randomly it seems), one of the containers become unresponsive (impossible to `exec`, other services timeout when trying to reach it, and no CPU/MEM info available on the dashboard).
I'm forced to kill them with `--grace-period=0 --force` (killing them softly put them in `deleting` state forever)

This happens with or without mounted volume

## Then, restarting pods with EBS mounted fails to restart
The following happen when an EBS volume is mounted and I kill the unresponsive pod:
Then once killed, the new pod is locked in `Pending` state. Only way to solve it for now is to drop the Statefulset, remove the volumes and the AWS EBS disk, and and then to create the Statefulset again.

After a while:
```
Unable to mount volumes for pod "mysql-0_preprod(f73a4d10-202d-11e7-9e20-0676cd8703f5)": timeout expired waiting for volumes to attach/mount for pod "preprod"/"mysql-0". list of unattached/unmounted volumes=[mysql-data default-token-gndwg]
kubelet ip-xx-xx-xx-xx.eu-west-1.compute.internal
warning
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "preprod"/"mysql-0". list of unattached/unmounted volumes=[mysql-data default-token-gndwg]
kubelet ip-xx-xx-xx-xx.eu-west-1.compute.internal
```

### The statefulset used:
```yml
apiVersion: v1
kind: Service
metadata:
  namespace: preprod
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: preprod
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 999
      containers:
      - name: mysql
        imagePullPolicy: Always
        image: mariadb:latest
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql
              key: db
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "ebs"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 25Gi

```

### And storage class used:
```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

`kubectl describe pvc` (while pod locked in Pending state) :
```
Name:		mysql-data-mysql-0
Namespace:	preprod
StorageClass:	ebs
Status:		Bound
Volume:		pvc-e66446ff-0fe5-11e7-a814-0676cd8703f5
Labels:		app=mysql
Capacity:	25Gi
Access Modes:	RWO
No events.
```

How can I recover my Statefulset without recreating it? (I would like to not lose data)

**update**: restarting the worker node fixes this issue

## Informations
region: eu-west-1
kube-aws used: `v0.9.5-rc.6`
