### ISSUE TITLE
Horizontal Pod Autoscaler (HPA): Current CPU: <unknown>

### ISSUE THREAD

**Issue by PuKoren** [kubernetes-incubator/kube-aws#549]
Hello,

I try to setup an HPA (Horizontal Pod Autoscaler) on one of my deployments using the latest version of kube-aws (`0.9.6-rc.2`).

However it seems to fail to monitor the CPU usage, and prints the following:
```bash
kubectl get hpa
NAME          REFERENCE                TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
drone-agent   Deployment/drone-agent   <unknown> / 40%   1         6         1          25m
```

There is my deployment setup:
```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
  labels:
    app: drone-agent
  namespace: devtools
spec:
  template:
    metadata:
      labels:
        app: drone-agent
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: drone-agent
        image: drone/drone:0.5
        args: ["agent"]
# Removed non-relevant configuration here
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drone-agent
  namespace: devtools
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: drone-agent
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 40
status:
  currentReplicas: 1
  desiredReplicas: 1
```

In the Dashboard, the HPA page shows: `Current CPU Utilization:%`

In all the monitoring pages, it seems that CPU is monitored based on the number of cores and not in %. Could this be linked?
