### ISSUE TITLE
Cluster with apiEndpoints should allow glue security groups added to the controller nodes

### ISSUE THREAD

**Issue by jcastillo-cb** [kubernetes-incubator/kube-aws#560]
Version: v0.9.6-rc.2
When using an unmanaged loadBalancer in apiEndoints as follows:
```
apiEndpoints:
- name: myapi
  dnsName: <NAME>
  loadBalancer:
    id: <ELB_NAME>
```

The API doesn't automatically get security group configuration attached that allows incoming traffic through the ELB. This means you can't reach the API through the loadBalancer.

We need something like this added to the controller:

```
controller:
  autoScalingGroup:
    minSize: 3
    maxSize: 3
    rollingUpdateMinInstancesInService: 2
  securityGroupIds:
  - sg-#####
  subnets:
    - name: ClusterSubnet01
    - name: ClusterSubnet02
    - name: ClusterSubnet03
```

Maybe other option would be to add the securityGroups to the apiEndpoint itself?? (This is accepted by kube-aws however the security group is not assigned to the controllers) 

```
apiEndpoints:
- name: myapi
  dnsName: <NAME>
  loadBalancer:
    id: <ELB_NAME>
    securityGroupIds:
    - sg-######
```
