### ISSUE TITLE
Why ETCD EIPs are created when etcd cluster is private subnets?

### ISSUE THREAD

**Issue by mazzy89** [kubernetes-incubator/kube-aws#611]
What I'd like to achieve is to build a k8s cluster in HA mode. 3 AZ, 3 public subnets (one for every AZ), 3 private subnets (one for every AZ). Control Plane and Node Pool in private subnets. An ElasticLoad Balancer launched across three public subnets which allow to reach the k8s api. 3 NAT Gateways launched in the three AZ. A Bastion Host to ssh in the cluster. What I'm asking is if it's possible to achieve such configuration with kube-aws and if yes which resources I need to create by  myself. In other way I'm trying to put in private subnets all the cluster and expose less possible. Here a tutorial of how this is achieved [7 Steps to keep the web servers private on AWS](https://www.linkedin.com/pulse/7-steps-keep-web-servers-private-aws-mohammed-vasowala)

**Comment by redbaron** [comment]
did you even try kube-aws before asking?

**Comment by mazzy89** [comment]
Not yet @redbaron Trying to customize `cluster.yml` with all the parameters especially networking but get lost in that section

**Comment by c-knowles** [comment]
Hi @mazzy89, yes I think with many options it's a bit easy to get lost. We're working on better documentation in https://github.com/kubernetes-incubator/kube-aws/issues/534.

> 3 AZ, 3 public subnets (one for every AZ), 3 private subnets (one for every AZ).

For this bit, just define the subnets as you wish under `subnets`, there are many different options so I suggest start simple and tailor to your use case. For example, this would give you a basic managed setup in `eu-west`:
```yaml
subnets:
  - name: ManagedPrivateSubnet1
    private: true
    availabilityZone: eu-west-1a
    instanceCIDR: "10.0.1.0/24"
  - name: ManagedPrivateSubnet2
    private: true
    availabilityZone: eu-west-1b
    instanceCIDR: "10.0.2.0/24"
  - name: ManagedPrivateSubnet3
    private: true
    availabilityZone: eu-west-1c
    instanceCIDR: "10.0.3.0/24"
  - name: ManagedPublicSubnet1
    private: false
    availabilityZone: eu-west-1a
    instanceCIDR: "10.0.4.0/24"
  - name: ManagedPublicSubnet2
    private: false
    availabilityZone: eu-west-1b
    instanceCIDR: "10.0.5.0/24"
  - name: ManagedPublicSubnet3
    private: false
    availabilityZone: eu-west-1c
    instanceCIDR: "10.0.6.0/24"
```

However, should you wish to reuse some of your existing infrastructure often the IDs of those can be referenced. For example, to reuse an existing NAT Gateway:
```yaml
  - name: ManagedPrivateSubnetWithExistingNGW1
    private: true
    availabilityZone: eu-west-1a
    instanceCIDR: "10.0.1.0/24"
    natGateway:
      idFromStackOutput: vpc-nat-gateway-1
```

Look through the commented out block of `cluster.yaml` between `subnets:` and `serviceCIDR:` for more info on the options.

> Control Plane and Node Pool in private subnets. 

A bit like this (I took other mandatory options out of the example for brevity):
```yaml
controller:
  subnets:
    - name: ManagedPrivateSubnet1
    - name: ManagedPrivateSubnet2
    - name: ManagedPrivateSubnet3

worker:
  nodePools:
    - name: worker-pool-a
      subnets:
        - name: ManagedPrivateSubnet1
    - name: worker-pool-b
      subnets:
        - name: ManagedPrivateSubnet2
    - name: worker-pool-c
      subnets:
        - name: ManagedPrivateSubnet3
```

> An ElasticLoad Balancer launched across three public subnets which allow to reach the k8s api.

Take a look at `apiEndpoints`. You'll want something like this (I haven't tried this option before myself):

```yaml
apiEndpoints:
  - name: default
    loadBalancer:
      subnets:
        - name: ManagedPublicSubnet1
        - name: ManagedPublicSubnet2
        - name: ManagedPublicSubnet3
```

> 3 NAT Gateways launched in the three AZ.

Should be done with the above private subnets I believe.

> A Bastion Host to ssh in the cluster. 

Not supported by kube-aws, you would need to have a separate stack inside the same VPC. I'd recommend keeping your VPC setup entirely separate and using the `vpcId` and `internetGatewayId` options in kube-aws. That way you can easily add another subnet containing your bastion host which then has access to the appropriate VPC CIDRs and you can create/recreate multiple k8s clusters inside the same VPC without cluster updates interfering with VPC/bastion/other clusters etc. There are tonnes of examples of how to setup and customise a VPC, for example [here](https://engblog.nextdoor.com/building-vpcs-with-cloudformation-templates-c5d2c1f8c10f). In this scenario kube-aws would be managing its own subnets but in your existing VPC, then the IGW/NAT setup is up to you.

**Comment by mazzy89** [comment]
@c-knowles thanks for the clarification. This example has been not only useful but it helped me to clarify a concept which I totally misunderstood of NodePool (my bad). So at the end for such this kind of scenario it's definitely better to create an VPC by myself and then use the IDs of the resources (IGW/NAT) in the `cluster.yml` file

**Comment by mazzy89** [comment]
@c-knowles I'm running the version `0.9.5` but `apiEndpoints` is not there. Is it in the version `0.9.6`, isn't it?

**Comment by mazzy89** [comment]
@c-knowles I've tried to run the cluster after you recommend me those config but the problem is that I get the error from AWS that I exceeded the number of EIPs. This is caused by the fact kube-aws create a NAT gateway per every private subnet and assign an EIP and then an ETCD EIP is created per every nodes. In my case I set up 3 nodes. Now the question is why even if I've specified this under etcd:

```yaml
subnets:
    # References subnets defined under the top-level `subnets` key by their names
    - name: ManagedPrivateSubnetA
    - name: ManagedPrivateSubnetB
    - name: ManagedPrivateSubnetC
``` 

EIPs are created by the stack?
