### ISSUE TITLE
Validation error when deploying spotfleet node pool

### ISSUE THREAD

**Issue by paalkr** [kubernetes-incubator/kube-aws#617]
Hi 

I get this error when doing a kube-aws validate --s3-uri s3://bucket/folder, using kube-aws 0.9.6 final

```
Validating UserData and stack template...
Error: Error while rendering template : template: stack-templates/root.json.tmpl:37:29: executing "stack-templates/root.json.tmpl" at <$p.TemplateURL>: error calling TemplateURL: failed to get template url: failed to get template url: Error while rendering template : failed to render to str : failed to render : invalid character 'a' looking for beginning of value:
json syntax error (offset=458), in this region:
-------
{
    "Type": "AWS::EC2::SpotFleet",
    "Properties": {
      "SpotFleetRequestConfigData": {
        "IamFleetRole": arn:aws:iam::XXXXXXXXXXXXXXXXXX:role/aws-ec2-spot-fleet-role,
        "AllocationStrategy": "diversified",
        "TargetCapacity": 32,
        "SpotPrice": "0.10",

-------
```
pool definition from cluster.yaml

```
    - name: spotfleet
      createTimeout: PT25M     
      subnets:
      - name: gdo-vpc-PrivateSubnetA
      - name: gdo-vpc-PrivateSubnetB
      - name: gdo-vpc-PrivateSubnetC
      # clusterAutoscaler:
        # minSize: 1
        # maxSize: 10
      # clusterAutoscalerSupport:
        # enable: true
      awsNodeLabels:
        enabled: true        
      securityGroupIds:
        - sg-0825a971
      kube2IamSupport:
        enabled: true
      managedIamRoleName: "k8sWorkerRole"
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        cputype: spot
      taints:
      - key: cputype
        value: spot
        effect: NoSchedule            
      waitSignal:
        enabled: true
        maxBatchSize: 1
      spotFleet:
        targetCapacity: 32
        iamFleetRoleArn: "arn:aws:iam::XXXXXXXXXXXXXX:role/aws-ec2-spot-fleet-role"

        # Price per unit hour = Price per instance hour / num of weighted capacity for the instance
        # Defaults to "0.06"
        spotPrice: 0.10

        # Disk size (GiB) per unit
        # Disk size for each launch specification defaults to unitRootVolumeSize * weightedCapacity
        # unitRootVolumeSize: 50

        # Disk type for worker node (one of standard, io1, or gp2)
        # Can be overridden in each launch specification
        # rootVolumeType: gp2

        # Number of I/O operations per second (IOPS) per unit. Leave blank if rootVolumeType is not io1
        # IOPS for each launch specification defaults to unitRootVolumeIOPS * weightedCapacity
        # unitRootVolumeIOPS: 0

        launchSpecifications:
        - weightedCapacity: 4
          instanceType: r4.xlarge
          # Price per instance hour
          # Defaults to worker.spotFleet.spotPrice * weightedCapacity if omitted
          #spotPrice:
          rootVolume:
            size: 100
            type: gp2

        - weightedCapacity: 4
          instanceType: r3.xlarge
          # Price per instance hour
          # Defaults to worker.spotFleet.spotPrice * weightedCapacity if omitted
          #spotPrice:
          rootVolume:
            size: 100
            type: gp2            

        - weightedCapacity: 8
          instanceType: r4.2xlarge
          # Price per instance hour
          # Defaults to worker.spotFleet.spotPrice * weightedCapacity if omitted
          #spotPrice:
          rootVolume:
            size: 100
            type: gp2
```
