### ISSUE TITLE
Unable to predict DNS names of Etcd instances (need this for monitoring)

### ISSUE THREAD

**Issue by ivanilves** [kubernetes-incubator/kube-aws#638]
Hi all [from the `kube-aws` newbie]!

Got an issue: Unable to predict or discover DNS names of Etcd instances.

When I deploy new cluster with kube-aws, I also need to deploy DataDog (my monitoring solution of choice) and point it to the DNS names (or to IPs) of the Etcd instances. However I can not predict or discover these DNS or IP addresses from DataDog agent (I run it as a pod inside DS).

I could do it with  `memberIdentityProvider: eni` but it is marked as [EXPERIMENTAL], so I doubt if such noob as I should use it.

Could I somehow discover Etcd instance addresses while still using conservative `memberIdentityProvider: eip` setting?

...

or maybe there is a way to pull and run custom [DataDog] Docker container inside every Etcd instance?

Thanks!

**Comment by jeremyd** [comment]
Hi @ivanilves , I use the customFiles and customSystemdUnits config options in the etcd group of settings in order to drop-in my monitoring agent (I use telegraf).  So I know this would work for your datadog agent.  Not sure about finding the EIPs, although the EIP shouldn't change for the lifetime of a cluster if that helps...

taken from the cluster.yaml doc:
```
etcd:
#  # User defined files that will be added to the Etcd cluster cloud-init configuration in the "write_files:" section.
#  customFiles:
#    - path: "/etc/rkt/auth.d/docker.json"
#      permissions: 0600
#      content: |
#        { "rktKind": "dockerAuth", "rktVersion": "v1", ... }
#   
#  # User defined systemd units that will be added to the Etcd cluster cloud-init configuration in the "units:" section.
#  customSystemdUnits:
#    - name: monitoring.service
#      command: start
#      enable: true
#      content: |
#        [Unit]
#        Description=Example Custom Service
#        [Service]
#        ExecStart=/bin/rkt run --set-env TAGS=Controller ...
```

**Comment by mumoshu** [comment]
Hi @ivanilves, thanks for trying kube-aws!

How can you provide your dd-agent DNS names or IPs of etcd nodes?
Via a configuration file mounted to a dd-agent pod, or a command-line argument?
I guess the last one mile would vary according to that.

Anyway, I guess you can use the `awsEnvironment` setting to populate environment variables containing DNS names of etcd nodes by writing to /etc/environment:

```
experimental:
  # Used to provide `/etc/environment` env vars with values from arbitrary CloudFormation refs
  awsEnvironment:
    enabled: true
    environment:
      ETCD0_EIP: '{ "Ref" : "Etcd0EIP" }'
      ETCD1_EIP: '{ "Ref" : "Etcd1EIP" }'
      ETCD2_EIP: '{ "Ref" : "Etcd2EIP" }'
```

On top of that, `customSystemdUnits` could be used to obtain, transform and then pass those environment variables to dd-agent(s).
