### ISSUE TITLE
kube-aws up fails due to wrong security group configuration

### ISSUE THREAD

**Issue by olliiiver** [kubernetes-incubator/kube-aws#658]
Hi,

I was happy to build a cluster from scratch by using kube-aws version v0.9.6. However, if I want to add a cluster into an existing VPC, it seems that the VMs cannot communicate between each other via external EIP due to wrong security group configuration. Existing route table has an IGW attached to 0.0.0.0/0.

My cluster.yaml looks like this

```
clusterName: my-cube
apiEndpoints:
-
  name: default
  dnsName: ...
  loadBalancer:
    createRecordSet: false
keyName: ...
region: eu-central-1
kmsKeyArn: "..."
worker:
  nodePools:
    -
      name: nodepool1
vpcId: vpc-...
vpcCIDR: "10.26.0.0/16"
subnets:
  - name: KubePublic
    availabilityZone: eu-central-1a
    instanceCIDR: "10.26.50.0/22"
    private: false
    routeTable:
       id: rtb-...
addons:
  rescheduler:
    enabled: false
```

kube-aws up fails withe the following message

```
CREATE_FAILED AWS::CloudFormation::Stack my-cube The following resource(s) failed to create: [Controlplane].
CREATE_FAILED AWS::CloudFormation::Stack Controlplane Embedded stack arn:aws:cloudformation:eu-central-1:245309753215:stack/my-cube-Controlplane-EDDT7ZV2KC6E/652d0750-3ade-11e7-a2c6-50a68ad4f2fe was not successfully created: The following resource(s) failed to create: [Controllers].
```

Inside controller VM the following message is shown

```
May 17 09:08:04 ip-10-26-49-226.eu-central-1.compute.internal etcdctl[7130]: Error:  dial tcp 52.58.223.218:2379: i/o timeout
```

It seems that security groups are referencing each other ([security-groups.txt](https://github.com/kubernetes-incubator/kube-aws/files/1007186/security-groups.txt)). If I change inbound rules manually during creation, the cluster can be set up, but why are security groups created in a wrong way?
