### ISSUE TITLE
ETCD nodes are being deployed into the wrong subnets

### ISSUE THREAD

**Issue by richiemarshall** [kubernetes-incubator/kube-aws#679]
Hi, I've specified the subnets I want my etcd nodes deployed into but they're being deployed elsewhere. 

I want the nodes in private, un-manged subnets (along with the controllers and workers) but they are being deployed into the public subnets and allocated public IPs. 

The controllers and workers _are_ getting deployed into the correct subnets. This is on 0.9.6

Am I doing something wrong or is this unintentional?

## cluster.yaml snippet
```
etcd:
  count: 3
  instanceType: t2.small
  dataVolume:
    size: 30
    type: gp2
    iops: 0
    encrypted: true
    ephemeral: false
  subnets:
    - name: private-a
    - name: private-b
    
    
worker:
  apiEndpointName: proofcore
  nodePools:
    - name: nodepool-a
      subnets:
       - name: private-a
    - name: nodepool-b
      subnets:
       - name: private-b
       
subnets:
   - name: public-a
     availabilityZone: eu-west-2a
     id: "subnet-1c68b167"
     routeTable:
      id: "rtb-a450edcd"
   - name: public-b
     availabilityZone: eu-west-2b
     id: "subnet-28d92965"
     routeTable:
       id: "rtb-a450edcd"
   - name: private-a
     availabilityZone: eu-west-2a
     id: "subnet-416ab33a"
     routeTable:
       id: "rtb-a6328fcf"
   - name: private-b
     availabilityZone: eu-west-2b
     id: "subnet-e0d828ad"
     routeTable:
       id: "rtb-79328f10"

```
