### ISSUE TITLE
kube-dns not loading updated configmap

### ISSUE THREAD

**Issue by mgreenwald-pm** [kubernetes-incubator/kube-aws#688]
Hi, I tried updating my kube-dns as per the blog post about upstream DNS servers and the config data isn't loading into kube-dns:

```
I0531 23:03:36.916165       1 sync_configmap.go:107] ConfigMap kube-system:kube-dns was created
I0531 23:03:36.916210       1 dns.go:198] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[]}
```

Here is my configmap [kube-dns.yaml]:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"blah.domain.com": ["1.1.1.2"]}
```

Created with this command:

`kubectl create configmap kube-dns --from-file=configmaps/kube-dns.yaml --namespace=kube-system`

I saw issue #584 and was wondering if this upstream DNS server feature is even supported in release v0.9.6? Or will it be supported in v0.9.7?

Any help appreciated.

Referenced blog post:
http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html?m=1
