### ISSUE TITLE
Invalid memory address or nil pointer dereference on validation

### ISSUE THREAD

**Issue by mgreenwald-pm** [kubernetes-incubator/kube-aws#714]
I ran `kube-aws validate --s3-uri s3://s3-bucket-name` and got this error:

Version 0.9.7-rc.3

```
# kube-aws validate --s3-uri s3://s3-bucket-name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xdd0 pc=0x5f8f85]

goroutine 1 [running]:
panic(0xc66be0, 0xc42000e070)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes-incubator/kube-aws/core/root/config.ConfigFromBytes(0xc4201d8000, 0xde5d, 0xe05d, 0xde5d, 0xe05d, 0x0)
    /go/src/github.com/kubernetes-incubator/kube-aws/core/root/config/config.go:91 +0x265
github.com/kubernetes-incubator/kube-aws/core/root/config.ConfigFromFile(0xd927bf, 0xc, 0xd8d0b4, 0xc4201d6000, 0x0)
    /go/src/github.com/kubernetes-incubator/kube-aws/core/root/config/config.go:190 +0x77
github.com/kubernetes-incubator/kube-aws/core/root.ClusterFromFile(0xd927bf, 0xc, 0xd91a33, 0xb, 0xda81bd, 0x20, 0xda40cf, 0x1c, 0xda1a3a, 0x1a, ...)
    /go/src/github.com/kubernetes-incubator/kube-aws/core/root/cluster.go:110 +0x4d
github.com/kubernetes-incubator/kube-aws/cmd.runCmdValidate(0x13ddce0, 0xc4201ca3c0, 0x0, 0x2, 0x0, 0x0)
    /go/src/github.com/kubernetes-incubator/kube-aws/cmd/validate.go:46 +0x18f
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).execute(0x13ddce0, 0xc4201ca360, 0x2, 0x2, 0x13ddce0, 0xc4201ca360)
    /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:620 +0x247
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13dd3e0, 0x0, 0x0, 0x0)
    /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:699 +0x367
github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0x13dd3e0, 0xc420169f50, 0xc420000340)
    /go/src/github.com/kubernetes-incubator/kube-aws/vendor/github.com/spf13/cobra/command.go:658 +0x2b
main.main()
    /go/src/github.com/kubernetes-incubator/kube-aws/main.go:10 +0x2d
```
I've seen similar errors referenced before, but they are marked as resolved. #202 #204

**Comment by redbaron** [comment]
@mgreenwald-pm , which version do you run? can you provide cluster.yaml so that I can try to reproduce it?

**Comment by mgreenwald-pm** [comment]
@redbaron 

Here it is:
```
clusterName: name
releaseChannel: stable
sshAccessAllowedSourceCIDRs:
- 10.10.0.0/16
apiEndpoints:
- 
  name: name
  dnsName: subdomain.domain.com.
  loadBalancer:
    createRecordSet: true
    subnets:
    - name: ManagedPubSubnet1a
    recordSetTTL: 300
    hostedZone:
      id: AUGH1458JKI1L
keyName: kube-aws-key
region: us-east-1
kmsKeyArn: "arn:aws:kms:us-east-1:243876258767:key/802b99c2-38e6-4865-be56-5056948a3b59"
controller:
  subnets:
    - name: ManagedPrivSubnet1a
worker:
  nodePools:
    -
      name: nodepool1a
      subnets:
      - name: ManagedPrivSubnet1a
      volumeMounts:
      - type: "gp2"
        size: 150
        device: "/dev/xvdf"
        path: "/var/lib/docker"
      instanceType: m3.medium
      rootVolume:
        size: 8
        type: gp2
      autoScalingGroup:
        minSize: 3
        maxSize: 6
        rollingUpdateMinInstancesInService: 1
etcd:
  count: 3
  instanceType: t2.medium
  rootVolume:
    size: 24
    type: gp2
  subnets:
     - name: ManagedPrivSubnet1a
  version: 3.2.1
vpcCIDR: "10.15.0.0/16"
subnets:
- name: ManagedPubSubnet1a
  private: false
  availabilityZone: us-east-1a
  instanceCIDR: 10.15.0.0/24
- name: ManagedPrivSubnet1a
  private: true
  availabilityZone: us-east-1a
  instanceCIDR: 10.15.1.0/24
serviceCIDR: "10.3.0.0/24"
podCIDR: "10.2.0.0/16"
dnsServiceIP: 10.3.0.10
useCalico: true
containerRuntime: docker
addons:
  clusterAutoscaler:
    enabled: false
  rescheduler:
    enabled: false
experimental:
    taints:
      - key: dedicated
        value: search
        effect: NoSchedule
```
