### ISSUE TITLE
SpotFleet instances not registered in ALB target groups.

### ISSUE THREAD

**Issue by Cptn727** [kubernetes-incubator/kube-aws#719]
I've been trying to add a SpotFleet to my cluster, but it doesn't seem to add the nodes to the ALB target groups, although it *does* add them to the ELBs. Nodes in other pools (even non-fleet spot) get added to both ELBs and ALB target groups properly. It's not a very serious problem, because any node in the cluster should be able to handle the traffic and get it to the right pod, so as long as the SpotFleet isn't the only nodepool, things will work. Still, it seems like it should be consistent with the other pools' behavior.

```
kube-aws version v0.9.6-rc.5
```

I've included the worker portion of the cluster.yaml (identifying data such as ARNs, SG IDs or account IDs have been modified).
```
worker:
  nodePools:
    - name: m44xlargeAZA
      subnets:
      - name: k8s-worker-AZ1a
      securityGroupIds:
        - sg-rtz74bxr
      instanceType: m4.4xlarge
      kubernetesVersion: v1.6.2_coreos.0
      autoScalingGroup:
        minSize: 1
        maxSize: 2
        rollingUpdateMinInstancesInService: 1
      clusterAutoscaler:
        minSize: 1
        maxSize: 1
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/nodepool: m44xlargeAZA
        kube-aws.coreos.com/spotrequest: false
      targetGroup:
        enabled: true
        arns:
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-http/mi66h51hghvn5oa5
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-https/zz4fk7wmdr5486mh
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-http/0ltb8u93nd0qkhdf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-https/v9kqvjpxso8qhcfc
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-http/ij6jgdy3pe1bqvib
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-https/g6c73ggpsjn3vveg
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-http/fpsc3u2lqh0guggf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-https/5hr6b25oarp13570
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-http/ce5tqk01xmr6updl
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-https/a6fpm3kov9kvl2k7
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-http/9r6tj6dczrglluwm
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-https/sz6qgzkrj095s0px
        securityGroupIds: [ "sg-rtz74bxr" ]
      loadBalancer:
        enabled: true
        names: [ "useast1k8s01-elb-public", "useast1k8s01-elb-public-dom1" ]
        securityGroupIds: [ "sg-rtz74bxr" ]
      clusterAutoscalerSupport:
        enabled: true
      kube2IamSupport:
        enabled: true
    - name: m44xlargeAZE
      subnets:
      - name: k8s-worker-AZ1e
      securityGroupIds:
        - sg-rtz74bxr
      instanceType: m4.4xlarge
      kubernetesVersion: v1.6.2_coreos.0
      autoScalingGroup:
        minSize: 1
        maxSize: 2
        rollingUpdateMinInstancesInService: 1
      clusterAutoscaler:
        minSize: 1
        maxSize: 1
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/nodepool: m44xlargeAZE
        kube-aws.coreos.com/spotrequest: false
      targetGroup:
        enabled: true
        arns:
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-http/mi66h51hghvn5oa5
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-https/zz4fk7wmdr5486mh
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-http/0ltb8u93nd0qkhdf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-https/v9kqvjpxso8qhcfc
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-http/ij6jgdy3pe1bqvib
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-https/g6c73ggpsjn3vveg
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-http/fpsc3u2lqh0guggf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-https/5hr6b25oarp13570
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-http/ce5tqk01xmr6updl
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-https/a6fpm3kov9kvl2k7
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-http/9r6tj6dczrglluwm
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-https/sz6qgzkrj095s0px
        securityGroupIds: [ "sg-rtz74bxr" ]
      loadBalancer:
        enabled: true
        names: [ "useast1k8s01-elb-public", "useast1k8s01-elb-public-dom1" ]
        securityGroupIds: [ "sg-rtz74bxr" ]
      clusterAutoscalerSupport:
        enabled: true
      kube2IamSupport:
        enabled: true
    - name: m42xlSPOT
      spotPrice: 0.48
      subnets:
      - name: k8s-worker-AZ1e
      - name: k8s-worker-AZ1a
      securityGroupIds:
        - sg-rtz74bxr
      instanceType: m4.2xlarge
      kubernetesVersion: v1.6.2_coreos.0
      autoScalingGroup:
        minSize: 1
        maxSize: 6
        rollingUpdateMinInstancesInService: 2
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/nodepool: m42xlSPOT
        kube-aws.coreos.com/spotrequest: true
      targetGroup:
        enabled: true
        arns:
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-http/mi66h51hghvn5oa5
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-https/zz4fk7wmdr5486mh
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-http/0ltb8u93nd0qkhdf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-https/v9kqvjpxso8qhcfc
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-http/ij6jgdy3pe1bqvib
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-https/g6c73ggpsjn3vveg
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-http/fpsc3u2lqh0guggf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-https/5hr6b25oarp13570
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-http/ce5tqk01xmr6updl
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-https/a6fpm3kov9kvl2k7
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-http/9r6tj6dczrglluwm
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-https/sz6qgzkrj095s0px
        securityGroupIds: [ "sg-rtz74bxr" ]
      loadBalancer:
        enabled: true
        names: [ "useast1k8s01-elb-public", "useast1k8s01-elb-public-dom1" ]
        securityGroupIds: [ "sg-rtz74bxr" ]
      clusterAutoscalerSupport:
        enabled: true
      kube2IamSupport:
        enabled: true
    - name: c44xlSPOT
      spotPrice: 0.86
      subnets:
      - name: k8s-worker-AZ1e
      securityGroupIds:
        - sg-rtz74bxr
      instanceType: c4.4xlarge
      kubernetesVersion: v1.6.2_coreos.0
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 1
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/nodepool: c44xlSPOT
        kube-aws.coreos.com/spotrequest: true
      targetGroup:
        enabled: true
        arns:
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-http/mi66h51hghvn5oa5
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-https/zz4fk7wmdr5486mh
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-http/0ltb8u93nd0qkhdf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-https/v9kqvjpxso8qhcfc
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-http/ij6jgdy3pe1bqvib
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-https/g6c73ggpsjn3vveg
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-http/fpsc3u2lqh0guggf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-https/5hr6b25oarp13570
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-http/ce5tqk01xmr6updl
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-https/a6fpm3kov9kvl2k7
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-http/9r6tj6dczrglluwm
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-https/sz6qgzkrj095s0px
        securityGroupIds: [ "sg-rtz74bxr" ]
      loadBalancer:
        enabled: true
        names: [ "useast1k8s01-elb-public", "useast1k8s01-elb-public-dom1" ]
        securityGroupIds: [ "sg-rtz74bxr" ]
      clusterAutoscalerSupport:
        enabled: true
      kube2IamSupport:
        enabled: true
    - name: SpotFleet00
      subnets:
      - name: k8s-worker-AZ1e
      securityGroupIds:
        - sg-rtz74bxr
      kubernetesVersion: v1.6.2_coreos.0
      nodeDrainer:
        enabled: true
      nodeLabels:
        kube-aws.coreos.com/role: worker
        kube-aws.coreos.com/nodepool: SpotFleet00
        kube-aws.coreos.com/spotrequest: true
      targetGroup:
        enabled: true
        arns:
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-http/mi66h51hghvn5oa5
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-filtered-https/zz4fk7wmdr5486mh
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-http/0ltb8u93nd0qkhdf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-private-https/v9kqvjpxso8qhcfc
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-http/ij6jgdy3pe1bqvib
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom1-public-https/g6c73ggpsjn3vveg
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-http/fpsc3u2lqh0guggf
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-filtered-https/5hr6b25oarp13570
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-http/ce5tqk01xmr6updl
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-private-https/a6fpm3kov9kvl2k7
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-http/9r6tj6dczrglluwm
        - arn:aws:elasticloadbalancing:us-east-1:000000000001:targetgroup/useast1k8s01-dom2-public-https/sz6qgzkrj095s0px
      loadBalancer:
        enabled: true
        names: [ "useast1k8s01-elb-public", "useast1k8s01-elb-public-dom1" ]
      clusterAutoscalerSupport:
        enabled: true
      kube2IamSupport:
        enabled: true
      spotFleet:
        targetCapacity: 48
        launchSpecifications:
        - weightedCapacity: 8
          instanceType: c4.4xlarge
          spotPrice: 0.32
        - weightedCapacity: 4
          instanceType: c4.2xlarge
          spotPrice: 0.16
        - weightedCapacity: 2
          instanceType: c4.xlarge
          spotPrice: 0.08
        - weightedCapacity: 1
          instanceType: c4.large
          spotPrice: 0.04
```

Please let me know if I can provide any additional information or perform any extra testing that might be helpful/useful.
