### ISSUE TITLE
etcd3 snapshot restore not reproducible following docs

### ISSUE THREAD

**Issue by juniorsysadmin** [kubernetes-incubator/kube-aws#729]
Testing with c67b4699d29 , I am unable to restore a cluster from a snapshot. This could of course be user error on my part. I have:
- a cluster.yaml with
```
etcd:
  count: 3
  disasterRecovery:
    automated: false # also tried true, same result
  snapshot:
    automated: true
  version: 3.1.3

kubernetesVersion: v1.6.4_coreos.0

experimental:
  plugins:
    rbac:
      enabled: true
```

- enabled s3 bucket versioning
- waited for ETCD_CLUSTER_FAILURE_PERIOD_LIMIT to expire (which I believe is 10 minutes by default) after stopping etcd-member.service on each etcd node
- performed the 'Manually restoring a cluster from etcd snapshot' steps by uploading a previous snapshot.db to the s3 bucket, but run `systemctl start etcd-member.service` with `--no-block` since the first node will wait until there is quorum

Any ideas?

**Comment by mumoshu** [comment]
Hi @juniorsysadmin, thanks for trying kube-aws 👍 
Perhaps your etcd nodes already have locally cached versions of the snapshot `/var/run/coreos/etcdadm/snapshots/etcd<your etcd node's index>.db` inside?
`snapshot.db` gets downloaded from s3 only when a local version is missing in the etcd node.
 
If that's the case, would you mind removing `/var/run/coreos/etcdadm/snapshots/etcd<your etcd node's index>.db` on every etcd node before starting etcd-member.service to see if it works?

**Comment by juniorsysadmin** [comment]
> Perhaps your etcd nodes already have locally cached versions of the snapshot /var/run/coreos/etcdadm/snapshots/etcd<your etcd node's index>.db inside?

No - just retried. Same result when this directory is empty on all nodes.

**Comment by mumoshu** [comment]
@juniorsysadmin Hmm, that's odd. Sorry but would you mind helping me investigating further, by sharing me the output of `journalctl` on one of etcd nodes?

Could you also clarify how you were unable to restore an etcd cluster - what were the deltas between your expectation and the actual behavior of the manual restoration process?

**Comment by juniorsysadmin** [comment]
@mumoshu etcd logs from etcd0, etcd1 and etcd2 attached

[etc2.txt](https://github.com/kubernetes-incubator/kube-aws/files/1137754/etc2.txt)
[etc1.txt](https://github.com/kubernetes-incubator/kube-aws/files/1137753/etc1.txt)
[etc0.txt](https://github.com/kubernetes-incubator/kube-aws/files/1137755/etc0.txt)

Steps performed:
1) Working cluster with cluster.yaml as above
2) Enable s3 bucket versioning
3) Create a configmap.yaml:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: foobar
    config: env
  name: env-config
data:
  EXAMPLEA: "I am an OLD value"
```

4)

```
kubectl create -f configmap.yaml
```

5) Wait until the next snapshot is performed and arrives in the s3 bucket and copy it off
6) Change configmap.yaml
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: foobar
    config: env
  name: env-config
data:
  EXAMPLEA: "I am a NEW value"
```
7) 
```
kubectl update -f configmap.yaml
```
8) Ensure /var/run/coreos/etcdadm/snapshots/etcd* does not contain a snapshot on each node

9) Stop all etcd services on all 3 etcd nodes:

```
ssh -i $aws_key_pair core@$host sudo systemctl stop etcd-member.service
```

10) Wait an extended period of time for ETCD_CLUSTER_FAILURE_PERIOD_LIMIT to expire

11) Upload the previous snapshot to the s3 bucket

12) Run
```
systemctl start etcd-member.service with --no-block
```
on each etcd node

13)
```
kubectl describe configmap env-config
```
still shows the NEW value, not the old one
