### ISSUE TITLE
Unable to deploy cluster if subnets are specified

### ISSUE THREAD

**Issue by lwolf** [kubernetes-incubator/kube-aws#768]
Hi,
I'm trying to deploy HA cluster using kube-aws, but as soon as I add subnets definition as shown in documentation, deployment fails with the following error. Without subnets everything works great.

```
kube-aws up --s3-uri s3://<bucket>
Creating AWS resources. Please wait. It may take a few minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [Controlplane].

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack production The following resource(s) failed to create: [Controlplane].
CREATE_FAILED AWS::CloudFormation::Stack Controlplane Embedded stack arn:aws:cloudformation:eu-central-1:<EDITED-STACK-ID> was not successfully created: The following resource(s) failed to create: [InternetGateway, IAMRoleEtcd, VPC, Etcd2EIP, Etcd1EIP, NatGatewayManagedPrivateSubnet1EIP, NatGatewayManagedPrivateSubnet2EIP, NatGatewayManagedPrivateSubnet3EIP, Etcd0EIP].
```

here is my cluster.yaml
```
clusterName: cluster
releaseChannel: stable
apiEndpoints:
- name: default
  dnsName: cluster.<domain>
  loadBalancer:
    createRecordSet: true
    subnets:
    - name: ManagedPublicSubnet1
    - name: ManagedPublicSubnet2
    - name: ManagedPublicSubnet3

    hostedZone:
      id: "EDITED"

region: eu-central-1
kmsKeyArn: "EDITED"

controller:
  instanceType: t2.medium

  autoScalingGroup:
    minSize: 3
    maxSize: 3

  subnets:
    - name: ManagedPublicSubnet1
    - name: ManagedPublicSubnet2
    - name: ManagedPublicSubnet3

worker:
  nodePools:
  - name: nodepool1
    instanceType: t2.medium
    waitSignal:
      enabled: true
      maxBatchSize: 1

    autoScalingGroup:
      minSize: 1
      maxSize: 5
      rollingUpdateMinInstancesInService: 2
    autoscaling:
      clusterAutoscaler:
        enabled: true
    clusterAutoscalerSupport:
      enabled: true

    nodeDrainer:
      enabled: true
    subnets:
      - name: ManagedPublicSubnet1

  - name: nodepool2
    instanceType: t2.medium
    waitSignal:
      enabled: true
      maxBatchSize: 1

    autoScalingGroup:
      minSize: 1
      maxSize: 5
      rollingUpdateMinInstancesInService: 2
    autoscaling:
      clusterAutoscaler:
        enabled: true
    clusterAutoscalerSupport:
      enabled: true

    nodeDrainer:
      enabled: true

    subnets:
      - name: ManagedPublicSubnet2

etcd:
  count: 3
  instanceType: t2.medium

  rootVolume:
    size: 30
    type: gp2
    iops: 0

  dataVolume:
    size: 30
    type: gp2
    iops: 0
    encrypted: true
    ephemeral: false

  version: 3.2.1
  snapshot:
    automated: true

  disasterRecovery:
    automated: true

  subnets:
    - name: ManagedPrivateSubnet1
    - name: ManagedPrivateSubnet2
    - name: ManagedPrivateSubnet3

vpcCIDR: "10.1.0.0/16"

subnets:
  - name: ManagedPublicSubnet1
    availabilityZone: eu-central-1a
    instanceCIDR: "10.1.0.0/24"
  - name: ManagedPublicSubnet2
    availabilityZone: eu-central-1b
    instanceCIDR: "10.1.1.0/24"
  - name: ManagedPublicSubnet3
    availabilityZone: eu-central-1c
    instanceCIDR: "10.1.2.0/24"

  - name: ManagedPrivateSubnet1
    private: true
    availabilityZone: eu-central-1a
    instanceCIDR: "10.1.10.0/24"

  - name: ManagedPrivateSubnet2
    private: true
    availabilityZone: eu-central-1b
    instanceCIDR: "10.1.11.0/24"

  - name: ManagedPrivateSubnet3
    private: true
    availabilityZone: eu-central-1c
    instanceCIDR: "10.1.12.0/24"

```
