### ISSUE TITLE
etcd degradation

### ISSUE THREAD

**Issue by igayoso** [kubernetes-incubator/kube-aws#795]
Hi,

We're using kube-aws for kubernetes production cluster. After few weeks working without problems we saw etcd instance on degradation state. Instances have high load (between 5 and 8) with around 30% CPU and near 3Gb RAM usage. Two days after see this "problem" finally etcd go down and we had to reboot instances to get fresh etcd. Later we upgraded to last etcd version but after few days we saw again degradation problem with these instances.

We are using t2.small instances with 3 etcd on different zones. We will move to m4 instance type because looks like t instance type with burstable option is not enough and we are spending all the credits but I want add some logs and screenshots with the problem. Also I am not sure if etcd is not working well and is "eating" all the memory and this is the reason of load.

Someone with similar problems? Let me know if you need more info, logs, whatever...

Screenshots:
![selection_001](https://user-images.githubusercontent.com/1875941/28582448-bb6751b2-7165-11e7-9a0e-6751f8c47868.png)
![selection_002](https://user-images.githubusercontent.com/1875941/28582449-bb6e7fbe-7165-11e7-971a-710601a42e41.png)
![selection_003](https://user-images.githubusercontent.com/1875941/28582450-bb6ea412-7165-11e7-844d-d565922d0a63.png)
![selection_004](https://user-images.githubusercontent.com/1875941/28582452-bb8ca4c6-7165-11e7-9868-c336efa96066.png)
![selection_005](https://user-images.githubusercontent.com/1875941/28582451-bb89e434-7165-11e7-8dfc-a64e677c118b.png)

etcd container logs:
[logs-etcd-0.txt](https://github.com/kubernetes-incubator/kube-aws/files/1174059/logs-etcd-0.txt)
[logs-etcd-1.txt](https://github.com/kubernetes-incubator/kube-aws/files/1174060/logs-etcd-1.txt)
[logs-etcd-2.txt](https://github.com/kubernetes-incubator/kube-aws/files/1174061/logs-etcd-2.txt)

**Comment by danielfm** [comment]
I'm not sure t2.small instances are a good choice for your etcd cluster. Like you said, I'd go with at least a t2.medium, or with an instance with a more predictable baseline performance, such as m4.*. I'd also be careful to choose an appropriate configuration for the EBS volume, with a good balance of storage size and IOPS. Having a good disk IO performance is critical for etcd as well.

Out of curiosity, this cluster has how many nodes (controllers+workers)?

**Comment by redbaron** [comment]
interesting that it is `rkt run` which takes most of CPU. There is also etcdctl on another screenshot. @igayoso, are you using automatic etcd snapshotting by any chance?

**Comment by igayoso** [comment]
@danielfm sorry but I'm using t2.medium instead t2.small. Finally we will move to m4. I was looking to disk IOPS and looks fine, no high IO on the disk. Cluster has 2 controllers (m3.large) , 3 etcd (t2.medium) and 3 workers (m3.large).

@redbaron yep, is strange `rkt run` is taking mot of CPU. We are using automatic etcd snapshotting, could be the reason or something related?

**Comment by redbaron** [comment]
Are you using 0.9.7? More specifically this change https://github.com/kubernetes-incubator/kube-aws/pull/705 should be replacing `rkt run` with `docker run`

**Comment by igayoso** [comment]
We're using v0.9.7-rc.4 @redbaron

**Comment by redbaron** [comment]
Try 0.9.7, it could be that rkt fix wasn't added until final release

**Comment by igayoso** [comment]
#705 was included on rc-4 but thanks for help @redbaron . Finally we moved to m4 and after few hours looks fine. I will keep you posted...

**Comment by redbaron** [comment]
So we need to eliminate rkt run from other calls, can you please check where they are coming from and update this ticket or maybe open PR to do a similar change to #705 if you have time?

Moving to a bigger instance just gives you more time, CPU usage seems to be steadily grow over time, so at some moment you'll have same problem.

**Comment by igayoso** [comment]
@redbaron sure, I will do, no problem. About CPU you're right. Sorry for fast upgrade but it is a production service and we can not take risk. I will continue monitoring and I will update as soon as I have any news.

**Comment by igayoso** [comment]
Sorry for delay. I was testing and checking logs from rkt but I can't see anything strange. Also we moved to C4 instances and no more problems. Basically with C4 instances we didn't have credits and/or limited CPU so this was the mainly reason of the degradation. I was checking same version in the same cluster and compare between both and no problems with rkt or similar. I think you can close the ticket if you are agree please. Thanks!!

**Comment by igayoso** [comment]
After a few days with bigger instance we saw similar behaviors and CPU were increasing like in the past but with more time because we don't have CPU limitations. Yesterday we upgrade k8s cluster and moved to docker instead rkt. We will see next days...

**Comment by redbaron** [comment]
@igayoso , how it is holding up?

**Comment by igayoso** [comment]
Hi, 

I was checking minutes ago the graphs with similar issues. With bigger instances we will survive more days but looks like in 1 month we will have to restart etcd again so no news after rkt change. Another detail for these instances is that we have huge traffic on this cluster, I mean a lot of request from clients but I'm not sure if this is possible problem or not. Let me know if you want more tests or information please. Thanks! 
![image](https://user-images.githubusercontent.com/1875941/29574970-5a64d7c2-8763-11e7-812e-db48f96adfef.png)

**Comment by redbaron** [comment]
@igayoso , there is a PR to update Etcd to 3.2.5: https://github.com/kubernetes-incubator/kube-aws/pull/845 , if you apply similar changes you might find it behaving better (I recall somebody mentioned that 3.2.xxx had some CPU usage optimzations)

**Comment by redbaron** [comment]
While nodes are running, would you mind checking which process is the busiest?

**Comment by danielfm** [comment]
I'm experiencing a strange memory usage pattern after upgrading etcd from v3.1.3 to v3.2.6:

![image](https://user-images.githubusercontent.com/29534/29936187-ad401092-8e57-11e7-9e0d-acd4052252ab.png)

We can see very clearly the memory consumption used to stay stable until the update, after which the memory consumption wen't through the roof.

**Comment by redbaron** [comment]
@danielfm sounds like something worth reporting to etcd github

**Comment by flah00** [comment]
I feel like I've run into a similar issue, there was a [discussion](https://github.com/coreos/etcd/issues/8491) etcdadm-save and perhaps etcdadm-check having something to do with degradation. I decreased save frequency, in `userdata/cloud-config-etcd`, from every minute to every five minutes. I saw a baseline decrease in CPU usage, but CPU and "outbound traffic" are on an upward trend, still. I installed etcd 3.2.7 using kube-aws 0.9.8. My cluster.yaml enables both disaster recovery and snapshots.

The following snippet includes an extra unit, which runs on my etcd. I added the unit after CPU began mysteriously increasing. It certainly isn't the cause of my mysterious load.

```yaml
etcd:
  version: 3.2.7
  snapshot:
clusters
    automated: true
  disasterRecovery:
    automated: true
  count: 3
  subnets:
    - name: ManagedPrivateSubnet1d
  customFiles:
    - path: /etc/profile.d/aws.sh
      permissions: 0644
      owner: root:root
      content: |
        alias aws="docker run -v \$PWD:/work --workdir /work --env-file /etc/environment --rm quay.io/coreos/awscli aws"
    - path: /etc/sumologic-environment
      permissions: 0600
      owner: root:root
      # TODO MANUALLY MANAGED!
      content: |
        COLLECTOR_URL=...
        SOURCE_CATEGORY_PREFIX=zoo/
        LOG_FORMAT=text
        KUBERNETES_META=true
        FLUENTD_SOURCE=systemd
  customSystemdUnits:
    - name: fluentd-pos.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Setup fluentd pos directory
        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=/usr/bin/mkdir -p -m 1777 /var/run/fluentd-pos
    - name: sumologic.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Send logs to central server
        AssertFileNotEmpty=/etc/sumologic-environment
        Wants=docker.service
        After=docker.service
        [Service]
        ExecStartPre=/bin/sh -c '(eval $(docker run --rm --env-file /etc/environment quay.io/coreos/awscli aws ecr get-login --region us-east-1))'
        ExecStart=/usr/bin/docker run -l sumo=true -m 256m --cpu-quota=25000 --env-file /etc/sumologic-environment -v /var/lib/docker -v /var/lib/rkt -v /var/log:/mnt/log 221645429527.dkr.ecr.us-east-1.amazonaws.com/fluentd-kubernetes-sumologic:v1.5
        ExecStopPost=/usr/bin/docker rm $(/usr/bin/docker ps -aq --filter label=sumo=true)

```

<img width="1360" alt="screen shot 2017-09-16 at 11 02 34 am" src="https://user-images.githubusercontent.com/477982/30513276-9a6a4da6-9ace-11e7-8ec8-dcefb329223c.png">
