### ISSUE TITLE
Spot fleet bid price logic differs from AWS defaults

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#812]
## Issue

On setting up a spot fleet, I came across what seems to be a difference between default AWS and default kube-aws bid price logic for spot fleets.

According to the [CloudFormation docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html#cfn-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-spotprice) and the [Spot Fleet docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html#spot-price-overrides), `By default, the Spot fleet uses [the global Spot price] as the bid price for each of its launch specifications.`

However, the kube-aws default is `worker.spotFleet.spotPrice * weightedCapacity`.

I think maybe the confusion comes from this part of the AWS docs:
```
By default, the Spot price that you specify represents your bid price per instance hour.
When you use the instance weighting feature, the Spot price that you specify represents 
your bid price per unit hour. You can calculate your bid price per unit hour by dividing 
your bid price for an instance type by the number of units that it represents.
```

As far as I can see we always have instance weighting turned on in kube-aws and no flag to turn it off (but it is optional in CF).

## Example

Here is an example of the difference. Say we setup this basic spot fleet of C4 class instances:

```yaml
spotFleet:
  targetCapacity: 4
  spotPrice: 0.036
  launchSpecifications:
    - weightedCapacity: 1
      instanceType: c4.large
    - weightedCapacity: 2
      instanceType: c4.xlarge
    - weightedCapacity: 4
      instanceType: c4.2xlarge
```

Each larger instance step is double the CPU/memory of the one prior so normally we'd weight as 1/2/4 respectively.

Writing these values into CF directly, this spot fleet would mean:
* we want total capacity of 4 units made up of either 1 x c4.2xlarge, 2 x c4.xlarge, 4 x c4.large or some combination
* we want to bid 0.036 per weighted capacity

### Expected Result

We're using weighted spot fleet and the spot fleet bid price is the same here. Since the default AWS logic would be for the spot fleet bid price to represent the bid price _per unit hour_ and `(bid price per unit hour * weighted capacity == bid price per instance type)`, I'd expect bid prices of:
* 0.036 for c4.large
* 0.036 x 2 == 0.072 for c4.xlarge
* 0.036 x 4 == 0.144 for c4.2xlarge

### Actual Result

kube-aws seems to override the AWS default for spot fleet launch specifications with `worker.spotFleet.spotPrice * weightedCapacity`. So what we get inside the kube-aws generated CF template is:
* 0.036 for c4.large
* 0.072 for c4.xlarge
* 0.144 for c4.2xlarge

But then in AWS it will result in these bid values:
* 0.036 for c4.large
* 0.072 x 2 == 0.144 for c4.xlarge
* 0.144 x 4 == 0.576 for c4.2xlarge

### Workaround

Specifying overrides back to the AWS default does the trick:

```yaml
spotFleet:
  targetCapacity: 4
  spotPrice: 0.036
  launchSpecifications:
    - weightedCapacity: 1
      instanceType: c4.large
    - weightedCapacity: 2
      instanceType: c4.xlarge
      spotPrice: 0.036 # instance bid price with be 2x == 0.072
    - weightedCapacity: 4
      instanceType: c4.2xlarge
      spotPrice: 0.036 # instance bid price with be 4x == 0.144
```
