### ISSUE TITLE
Cannot destroy cluster

### ISSUE THREAD

**Issue by Phylu** [kubernetes-incubator/kube-aws#815]
If I try to destroy my kubernetes cluster, the CloudFormation stack cannot be destroyed.

Within the stack, I have the following subnet:

```
subnets:
  - name: prefix-ManagedPublicSubnet1-stage
    private: false
    availabilityZone: eu-central-1a
    instanceCIDR: "10.0.100.0/24"
```

Within this subnet, there exist two network interfaces that are still attached to the ELB connecting the subnet to the outside world. When destroying the stack, these interfaces are not considered and therefore the subnet cannot be destroyed. When the network interfaces are manually detached and deleted, the destroy succeeds.

**Comment by mumoshu** [comment]
@Phylu Hi, thank you very much for trying kube-aws and the feedback 👍 
Probably you've created k8s service(s) whose `Type` is `LoadBalancer`?
Then, you would need to `kubectl delete` them before running `kube-aws destroy`.
kube-aws tries its best not to accidentally delete resources NOT managed by kube-aws(what happens if the ELB was used to service workloads from users? You should retain it in such a case) hence the behavior.

**Comment by Phylu** [comment]
I will try that the next time, I destroy my cluster.
I just don't understand the case exactly. If I destroy the cluster, I expect everything within the cluster to disappear. Even the services, which I created.

The node pool which uses the subnet has a load balancer, but it is managed by kube-aws:
```
 nodePools:
    - # Name of this node pool. Must be unique among all the node pools in this cluster
      name: np-pub-1-stage
      - # References subnets defined under the top-level `subnets` key by their names
        name: prefix-ManagedPublicSubnet1-stage
      loadBalancer:
        enabled: true
      autoScalingGroup:
        minSize: 1
        maxSize: 2
        rollingUpdateMinInstancesInService: 1
        clusterAutoscaler:
          enabled: true
      nodeLabels:
        subnet: public
```
