### ISSUE TITLE
Node pool release channel configuration does not work

### ISSUE THREAD

**Issue by drywheat** [kubernetes-incubator/kube-aws#837]
### Versions

**kube-aws:** v0.9.7
**kubernetes:** v1.6.3+coreos.0

### Synopsis

I am currently using the CoreOS **stable** release channel for most of my cluster but I would like to configure my CICD node pool to use the **alpha** channel; this has a newer version of Docker that supports staged-builds.  Adding the following configuration lines to `cluster.yaml` and running `kube-aws update` affects no change whatsoever. In AWS, I see the top-level CF stack for the cluster check for an update and then exit immediately thereafter. 

```yaml
  nodePools:
    - name: cicd-node-pool
      releaseChannel: alpha
      subnets:
        - name: sn-app-0
        - name: sn-app-1
        - name: sn-app-2
      securityGroupIds:
        - sg-XXXXXXXX
      instanceType: t2.large
      createTimeout: PT25M

      autoScalingGroup:
        minSize: 2
        maxSize: 4
        rollingUpdateMinInstancesInService: 1

      nodeLabels:
        kube-aws.coreos.com/nodepool: cicd
      taints:
        - key: dedicated
          value: cicd
          effect: NoExecute
```

I tried to (1) create a _new_ node pool using the alpha channel and (b) updating an existing node pool to use alpha channel. In both cases the node pool ended up using the stable channel.

Please let me know if I can provide any further information.
