### ISSUE TITLE
Common mistake: single API endpoint with apiAccessAllowedSourceCIDRs

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#868]
When you have only one public API endpoint with non-empty `apiAccessAllowedSourceCIDRs` configured, kubelets in worker nodes will be unable to connect apiserver and hence no worker nodes will be shown in `kubectl get node`.

It is considered so because kubelets tries to communicate via public IPs of worker nodes as the API endpoint ELB is `internet-facing` one.

If you would like to configure `apiAccessAllowedSourceCIDRs`, almost certainly what you would want is two API endpoints. One is for internal communication between apiserver and worker kubelets, and another for external communication with admins.

A good cluster.yaml would look like:

```yaml
apiEndpoints:
- name: privateEndpoint
- name: publicEndpoint
  apiAccessAllowedSourceCIDRs:
  - ...

worker:
  apiEndpointName: privateEndpoint
```

While a bad cluster.yaml would look like:

```
apiEndpoints:
- name: publicEndpoint
  apiAccessAllowedSourceCIDRs:
  - ...
```

We will almost certainly want an additional validation to reject configurations like the bad one.
