### ISSUE TITLE
etcd /metrics returns empty result

### ISSUE THREAD

**Issue by VinceMD** [kubernetes-incubator/kube-aws#890]
I'm setting up Prometheus to gather metrics and as part of this setup, it will fetch metrics from `ETCD_NODE:2379/metrics`

I've opened the ETCD security group to the world on 2379 for time being.

But the curl command returns an empty response: 

`curl -L my-etcdnode-0:2379/metrics`

Is there a way to open this so that my Prometheus pod running inside Kubernetes can access the etc metrics?

**Comment by mumoshu** [comment]
@VinceMD Hi!
Honestly, I'm not very familiar with the `/metrics` endpoint.

However, anyway, are you sure you can access it without authentication?
AFAICS, to access 2379 with `etcdctl` you'd need to configure CA cert, client key/cert for the endpoint like:

```
ETCDCTL_CA_FILE=/etc/ssl/certs/ca.pem
ETCDCTL_CERT_FILE=/etc/ssl/certs/etcd-client.pem
ETCDCTL_KEY_FILE=/etc/ssl/certs/etcd-client-key.pem
```

So my guess is they're required for tls client authn even when you're using curl.

**Comment by VinceMD** [comment]
Hi @mumoshu!
 right. That makes things more complicated.  I expected an error. Not an empty result 
Need to see if Prometheus can read a certificate or a secret to connect to a metric endpoint

**Comment by VinceMD** [comment]
Help from the Prometheus Operator peeps:

# can  ServiceMonitor use credentials or certificates to read a metric end point?

# Answer:
https://coreos.com/operators/prometheus/docs/0.11.1/api.html#endpoint (edited)
etcd only serves the metrics endpoint over a the https handler, so the scheme actually needs to be `https`
and then you can specify the cert in the https://coreos.com/operators/prometheus/docs/0.11.1/api.html#tlsconfig (edited)
for your cert to be available to prometheus you need to mount a secret into the Prometheus Pod
you can do that by specifying an list of secrets in the prometheus object
https://coreos.com/operators/prometheus/docs/0.11.1/api.html#prometheusspec (edited)

I will try that and close the ticket. Hopefully we can

**Comment by VinceMD** [comment]
I was able to use the certificates to pull data from etcd metrics endpoint. Still blocked with Prometheus Operator as it expects IP addresses Kube endpoint and does not seem to work with DNS. 
https://github.com/coreos/prometheus-operator/issues/571

Closing this ticket as it's probably not something that can be solved via kube-aws? 
Unless I could make the certificate work for the IP address as well as the DNS?

**Comment by danielfm** [comment]
I use Prometheus to scrape data from our etcd cluster; the configuration is something like this:

```yaml
- job_name: etcd
  scheme: https

  tls_config:
    ca_file: /etc/kubernetes/ssl/ca.pem
    cert_file: /etc/kubernetes/ssl/etcd-client.pem
    key_file: /etc/kubernetes/ssl/etcd-client-key.pem

  ec2_sd_configs:
    - region: sa-east-1

  relabel_configs:
  # TODO: Edit regex to match only etcd nodes from current cluster
  - source_labels: [__meta_ec2_tag_kubernetes_io_cluster_NAME, __meta_ec2_tag_kube_aws_role]
    regex: "true;etcd"
    action: keep
  - source_labels: [__meta_ec2_public_dns_name]
    regex:  '(.*)'
    target_label: __address__
    replacement: '${1}:2379'
  - action: labelmap
    regex: __meta_ec2_instance_(.+)
    replacement: 'instance_${1}'
```

But, as you can see, we still need access to the etcd certificates. Since I'm using the Prometheus Helm chart for this, it provides a way to add arbitrary host path mounts via values, something like this:

```yaml
# ...
server:
  # ...

  # Maps the hosts /etc/kubernetes so the container has access to etcd client certs
  extraHostPathMounts:
    - name: kube
      hostPath: /etc/kubernetes
      mountPath: /etc/kubernetes
      readOnly: true
```

Finally, in `cluster.yaml`, I attach custom security groups to worker nodes, etcd nodes, and controllers, so I can add extra rules when necessary. In this case, I added an inbound rule to etcd nodes from worker nodes on port 2379.

![image](https://user-images.githubusercontent.com/29534/29918313-69aeefe2-8e1b-11e7-8f8a-0481c7476ed1.png)
