### ISSUE TITLE
Reimplementing tagging of spot instances managed by a fleet

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#901]
A worker node backed by a spot instance managed by a spot fleet runs the `tag-spot-instance.service` systemd unit to tag the spot instance with:

* the cluster name tag required by k8s and
* other utility tags defined by kube-aws.

As @paalkr pointed out in #803, this can be done via cloudformation today.

https://aws.amazon.com/about-aws/whats-new/2017/07/tag-your-spot-fleet-ec2-instances/

**Comment by c-knowles** [comment]
Ah, this would be good for monitoring. We are currently using a custom tag in `cluster.yaml` with the environment name and then we filter to that plus `aws:cloudformation:logical-id` == `Workers` to plot how many workers in an environment. We're using Datadog. Unfortunately right now in a spot fleet the instances receive neither of those tags so they are missing from the totals. Happy to change this to whatever we come up with, just need a way to segregate workers from other nodes and switch between environments.

**Comment by c-knowles** [comment]
@mumoshu it seems this is not exposed via CF as of today? I couldn't find tags anywhere in the docs but it does seem available via the CLI.

**Comment by mumoshu** [comment]
@c-knowles I've researched how the SpotRequestConfigData containing tags look like when it was generated in AWS console:

```json
{
  "IamFleetRole": "arn:aws:iam::myaccountid:role/myrole",
  "AllocationStrategy": "lowestPrice",
  "TargetCapacity": 1,
  "SpotPrice": "0.128",
  "ValidFrom": "2017-11-22T04:44:53Z",
  "ValidUntil": "2018-11-22T04:44:53Z",
  "TerminateInstancesWithExpiration": true,
  "LaunchSpecifications": [
    {
      "ImageId": "ami-2a69be4c",
      "InstanceType": "c3.large",
      "KeyName": "mykey",
      "BlockDeviceMappings": [
        {
          "DeviceName": "/dev/xvda",
          "Ebs": {
            "DeleteOnTermination": true,
            "VolumeType": "gp2",
            "VolumeSize": 8,
            "SnapshotId": "snap-123456788"
          }
        }
      ],
      "TagSpecifications": [
        {
          "ResourceType": "instance",
          "Tags": [
            {
              "Key": "Foo",
              "Value": "Bar"
            }
          ]
        }
      ]
    }
  ],
  "Type": "maintain"
}
```

So - it seems like we now have `TagSpecifications` per launch specification, even though it isn't documented yet.

**Comment by mumoshu** [comment]
Update: CloudFormation assumes it as an unsupported property, anyway 😢 

> +00:02:58	Spot	CREATE_FAILED           		Workers               	"Encountered unsupported property TagSpecifications"

**Comment by c-knowles** [comment]
😢 that’s a shame, shall we wait for reinvent next week or try to get this in now? I can work on it.

**Comment by mumoshu** [comment]
@c-knowles Would it be enough for you if I add support for `worker.nodePools[].customTags` to EC2 instances managed by spot fleets?
Not a bit deal but I'd like to avoid tagging `aws:cloudformation:logical-id` in tag-spot-instance.service because I just feel like imitating Cfn's role.

**Comment by mumoshu** [comment]
For record, what we have today is:
![image](https://user-images.githubusercontent.com/22009/33129179-68fd64e0-cfd2-11e7-95f5-e48f311d1d87.png)

**Comment by c-knowles** [comment]
@mumoshu I think AWS rejects tags starting with `aws:`? So to make it more uniform we'd need to do some work on the instance level tags rather than CF stack inherited ones. In terms on monitoring, I think most users would like to differentiate between:
1. clusters in the same account
1. controllers, workers, etcd
1. node pools

**Comment by c-knowles** [comment]
Ah yes - [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions) are the docs for tag restrictions.

**Comment by mumoshu** [comment]
@c-knowles Makes sense. How about this?

```yaml
worker:
  nodePools:
  - name: pool1
     instanceTags:
       myrole: worker
       type: ondemand
     # Propagated to (hopefully, it's up to cfn) all the stack resources for the pool1 stack
     stackTags:
       env: prod
  - name: pool2
     spotFleet:
       targetCapacity: 2
     # Propagated to EC2 instances managed by this spot fleet (via tag-spot-instance.service)
     instanceTags:
       myrole: worker
       type: spot
     # Propagated to (hopefully, it's up to cfn) all the stack resources for the pool2 stack
     stackTags:
       env: prod

controller:
  instanceTags:
    myrole: controller
    type: ondemand
  # invalid as controller nodes don't have a dedicated cfn stack
  # stackTags:

etcd:
  instanceTags:
    myrole: etcd
    type: ondemand
  # invalid as etcd nodes don't have a dedicated cfn stack
  # stackTags:

# Propagated to both controller and etcd nodes
stackTags:
  env: prod
```
