### ISSUE TITLE
kube2iam support for kube-resources-autosave

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#912]
This issue is extracted from https://github.com/kubernetes-incubator/kube-aws/issues/823#issuecomment-320604056

When `kube2iam` is enabled, `kube-resources-autosave` as of today requires the IAM worker role to have permissions for the autosaving. The IAM worker role is discovered via the flag `--auto-discover-default-role` of `kube2iam` but the flag will be removed sooner or later to improve security, which will result in `kube-resources-autosave` to be unfunctional.

To keep the compatibility between `kube-resources-autosave` and `kube2iam` even after the role auto discovery is disabled, we should manage an IAM role dedicated to `kube-resources-autosave` which is discovered and assumed to be used by the autosave app via the kube2iam annotation.

cc @jollinshead

**Comment by whereisaaron** [comment]
I have `kube2iam` enabled with `kube-resources-autosave` on 0.9.9 and I still have the `--auto-discover-default-role` flag for `kube2iam`. However `kube-resources-autosave-pusher` is now failing. It does work without `kube2iam` running.

From your description above this should still work?

kube-resources-autosave-pusher errors are like this:
```
move failed: kube-resources-autosave/complete/2018-01-05_23-45-41/prometheus/roles.json to s3://my-cluster/kube-aws/clusters/my-cluster/backup/2018-01-05_23-45-41/prometheus/roles.json Unable to locate credentials
```

kube2iam settings:
```
            containers:
              - image: {{.Kube2IAMImage.RepoWithTag}}
                name: kube2iam
                args:
                  - "--app-port=8282"
                  - "--auto-discover-base-arn"
                  - "--auto-discover-default-role"
                  - "--iptables=true"
                  - "--host-ip=$(HOST_IP)"
```
