### ISSUE TITLE
The deprecated and removed configuration key `hostedZoneId` is remaining in cluster.yaml

### ISSUE THREAD

**Issue by mumoshu** [kubernetes-incubator/kube-aws#933]
We can safely remove the old key `hostedZoneId` from cluster.yaml as it has been already commented out by default and replaced by `apiEndpoints[].hostedZone.id`  since v0.9.7.

**Comment by mumoshu** [comment]
cc @j5ik2o Thx for letting me
notice this in our 1on1 session. I'm going to fix this soon :+wink:

**Comment by jeremyd** [comment]
Same with mapPublicIPs.  This still exists in cluster.yaml but validation fails because it's an invalid key (needs to be in subnets: for it to work).

**Comment by drywheat** [comment]
Is there a way to avoid mapping public IPs right now that `mapPublicIPs` is no longer valid? If I understand @jeremyd correctly, do I need to add that key under subnets?

```yaml
vpc:
  id: vpc-XXXXXX
  subnets:
      - name: myExistingSN
         availabilityZone: us-east-1a
         id: subnet-XXXXXX
         mapPublicIPs: false
```
