### ISSUE TITLE
 podpresets don't seem to apply

### ISSUE THREAD

**Issue by luck02** [kubernetes-incubator/kube-aws#935]
I was attempting to enable podpresets on a test cluster.

Based on what I was able to glean from:
* https://kubernetes.io/docs/admin/admission-controllers/#how-do-i-turn-on-an-admission-control-plug-in
* https://kubernetes.io/docs/tasks/inject-data-application/podpreset/
* https://github.com/kubernetes-incubator/kube-aws/blob/3e19289831b61d99e0d782c02e84ae0d5588e40f/core/controlplane/config/templates/cluster.yaml#L1148

I added the following to my cluster.yaml:
```
experimental:
  auditLog:
    enabled: true
    logpath: /dev/stdout
  admission:
    podpreset:
      enabled: true
```

I seem to have the API enabled (I think that's default for 1.7), I can create a podpreset.  But when I try to create a pod that should have it applied that fails to apply.  

I've gotten this working in minikube, it's possible there's something wrong with my templates but it seems unlikely.  

I'm hoping I'm missing something obvious.

Thanks!
