### ISSUE TITLE
nodepool.iam.statements seemingly have no effect

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#939]
I have following config:

```
workers:
  nodepools:
    - name: a
       iam:
         statements:
           - effect: ....
             resources: ....
```

no errors are given on `kube-aws-up` , but created nodepool IAMRole doesn't have specified permissions
