### ISSUE TITLE
Bring back dex out of the box

### ISSUE THREAD

**Issue by redbaron** [kubernetes-incubator/kube-aws#947]
Dex can be exposed via apiserver using proxy subresource. RBAC can be configured to let anonymous access to dex:

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dex-proxy-access
rules:
- apiGroups: [""]
  resources:
  - services/proxy
  verbs: ["get", "post"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dex-anonymous-auth
subjects:
- kind: Group
  name: system:unauthenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dex-proxy-access
  apiGroup: rbac.authorization.k8s.io
```

Then clients can do:

```
`curl -v -k "https://APISERVER:6443/api/v1/namespaces/kube-system/services/https:dex:dex/proxy/dex/.well-known/openid-cofiguration"`
```

without need of ELBs
