### ISSUE TITLE
kube-proxy no longer supports *any command line options -- support kube 1.8

### ISSUE THREAD

**Issue by jeremyd** [kubernetes-incubator/kube-aws#976]
We need to move --cluster-cidr into a config file for kube-proxy.  With kube 1.8, the command line options are fully depricated and the error is observed:
```
kube-proxy-wzccp kube-proxy W1012 17:28:13.637563       1 server.go:191] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
```

current command line is:
```
/hyperkube proxy --kubeconfig=/etc/kubernetes/kubeconfig/kube-proxy.yaml --cluster-cidr=10.2.0.0/16
```

Reference issue: https://github.com/kubernetes/kubernetes/issues/50041  I'm still looking for an example config, we can output one with kube proxy --write-config-to ...

**Comment by jeremyd** [comment]
output from docker exec into kube-proxy container and running:
/hyperkube proxy --kubeconfig=/etc/kubernetes/kubeconfig/kube-proxy.yaml --cluster-cidr=10.2.0.0/16 --write-config-to kubeproxy.conf

cat kubeproxy.conf
```
apiVersion: componentconfig/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /etc/kubernetes/kubeconfig/kube-proxy.yaml
  qps: 5
clusterCIDR: 10.2.0.0/16
configSyncPeriod: 15m0s
conntrack:
  max: 0
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
featureGates: ""
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  minSyncPeriod: 0s
  scheduler: ""
  syncPeriod: 0s
kind: KubeProxyConfiguration
metricsBindAddress: 127.0.0.1:10249
mode: ""
oomScoreAdj: -999
portRange: ""
resourceContainer: /kube-proxy
udpTimeoutMilliseconds: 250ms
```
