### ISSUE TITLE
Question: Where are kube-system configs defined (scaledown)

### ISSUE THREAD

**Issue by luck02** [kubernetes-incubator/kube-aws#982]
Specifically, to enable scale-down we need to specify Pod Disruption Budgets:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: heapster-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: heapster
```

However, it seems (At least for us) that the heapster deployment is defined with a single pod, what's the recommended practice?  Is there something we can do in the cluster.yaml to configure that?  Or is it generally recommended to have a follow up script that executes the required changes.

Thanks!
